!+
! Module equality_mod
!
! This module defines a set of functions which overload the equality operator ("==").
! These functions test for equality between instances of a given structure. 
!
! This file is generated as a by product of the Bmad/C++ interface code generation
! The code generation files can be found in cpp_bmad_interface.
!
! DO NOT EDIT THIS FILE DIRECTLY! 
!- 

module equality_mod
use test_struct_defs

interface operator (==)
  module procedure eq_wake_lr, eq_wake, eq_all_encompassing
end interface

contains

!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_wake_lr (f1, f2) result (is_eq)

implicit none

type(wake_lr_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[integer8, 0, NOT]
is_eq = is_eq .and. (f1%aaa == f2%aaa)
!! f_side.equality_test[integer, 0, NOT]
is_eq = is_eq .and. (f1%bbb == f2%bbb)
!! f_side.equality_test[character, 0, NOT]
is_eq = is_eq .and. (f1%file == f2%file)
!! f_side.equality_test[real, 0, NOT]
is_eq = is_eq .and. (f1%t_ref == f2%t_ref)
!! f_side.equality_test[real, 0, NOT]
is_eq = is_eq .and. (f1%freq_spread == f2%freq_spread)

end function eq_wake_lr

!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_wake (f1, f2) result (is_eq)

implicit none

type(wake_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[type, 0, NOT]
is_eq = is_eq .and. (f1%sr == f2%sr)

end function eq_wake

!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_all_encompassing (f1, f2) result (is_eq)

implicit none

type(all_encompassing_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[real, 0, NOT]
is_eq = is_eq .and. (f1%real_rp_0d == f2%real_rp_0d)
!! f_side.equality_test[real, 1, NOT]
is_eq = is_eq .and. all(f1%real_rp_1d == f2%real_rp_1d)
!! f_side.equality_test[real, 2, NOT]
is_eq = is_eq .and. all(f1%real_rp_2d == f2%real_rp_2d)
!! f_side.equality_test[real, 3, NOT]
is_eq = is_eq .and. all(f1%real_rp_3d == f2%real_rp_3d)
!! f_side.equality_test[real, 0, PTR]

is_eq = is_eq .and. (associated(f1%real_rp_0d_ptr) .eqv. associated(f2%real_rp_0d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_0d_ptr)) is_eq = (f1%real_rp_0d_ptr == f2%real_rp_0d_ptr)
!! f_side.equality_test[real, 1, PTR]
is_eq = is_eq .and. (associated(f1%real_rp_1d_ptr) .eqv. associated(f2%real_rp_1d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_1d_ptr)) is_eq = all(shape(f1%real_rp_1d_ptr) == shape(f2%real_rp_1d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_1d_ptr)) is_eq = all(f1%real_rp_1d_ptr == f2%real_rp_1d_ptr)
!! f_side.equality_test[real, 2, PTR]
is_eq = is_eq .and. (associated(f1%real_rp_2d_ptr) .eqv. associated(f2%real_rp_2d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_2d_ptr)) is_eq = all(shape(f1%real_rp_2d_ptr) == shape(f2%real_rp_2d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_2d_ptr)) is_eq = all(f1%real_rp_2d_ptr == f2%real_rp_2d_ptr)
!! f_side.equality_test[real, 3, PTR]
is_eq = is_eq .and. (associated(f1%real_rp_3d_ptr) .eqv. associated(f2%real_rp_3d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_3d_ptr)) is_eq = all(shape(f1%real_rp_3d_ptr) == shape(f2%real_rp_3d_ptr))
if (.not. is_eq) return
if (associated(f1%real_rp_3d_ptr)) is_eq = all(f1%real_rp_3d_ptr == f2%real_rp_3d_ptr)
!! f_side.equality_test[real, 1, ALLOC]
is_eq = is_eq .and. (allocated(f1%real_rp_1d_alloc) .eqv. allocated(f2%real_rp_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_rp_1d_alloc)) is_eq = all(shape(f1%real_rp_1d_alloc) == shape(f2%real_rp_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_rp_1d_alloc)) is_eq = all(f1%real_rp_1d_alloc == f2%real_rp_1d_alloc)
!! f_side.equality_test[real, 2, ALLOC]
is_eq = is_eq .and. (allocated(f1%real_rp_2d_alloc) .eqv. allocated(f2%real_rp_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_rp_2d_alloc)) is_eq = all(shape(f1%real_rp_2d_alloc) == shape(f2%real_rp_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_rp_2d_alloc)) is_eq = all(f1%real_rp_2d_alloc == f2%real_rp_2d_alloc)
!! f_side.equality_test[real, 3, ALLOC]
is_eq = is_eq .and. (allocated(f1%real_rp_3d_alloc) .eqv. allocated(f2%real_rp_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_rp_3d_alloc)) is_eq = all(shape(f1%real_rp_3d_alloc) == shape(f2%real_rp_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_rp_3d_alloc)) is_eq = all(f1%real_rp_3d_alloc == f2%real_rp_3d_alloc)
!! f_side.equality_test[real, 0, NOT]
is_eq = is_eq .and. (f1%real_dp_0d == f2%real_dp_0d)
!! f_side.equality_test[real, 1, NOT]
is_eq = is_eq .and. all(f1%real_dp_1d == f2%real_dp_1d)
!! f_side.equality_test[real, 2, NOT]
is_eq = is_eq .and. all(f1%real_dp_2d == f2%real_dp_2d)
!! f_side.equality_test[real, 3, NOT]
is_eq = is_eq .and. all(f1%real_dp_3d == f2%real_dp_3d)
!! f_side.equality_test[real, 0, PTR]

is_eq = is_eq .and. (associated(f1%real_dp_0d_ptr) .eqv. associated(f2%real_dp_0d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_0d_ptr)) is_eq = (f1%real_dp_0d_ptr == f2%real_dp_0d_ptr)
!! f_side.equality_test[real, 1, PTR]
is_eq = is_eq .and. (associated(f1%real_dp_1d_ptr) .eqv. associated(f2%real_dp_1d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_1d_ptr)) is_eq = all(shape(f1%real_dp_1d_ptr) == shape(f2%real_dp_1d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_1d_ptr)) is_eq = all(f1%real_dp_1d_ptr == f2%real_dp_1d_ptr)
!! f_side.equality_test[real, 2, PTR]
is_eq = is_eq .and. (associated(f1%real_dp_2d_ptr) .eqv. associated(f2%real_dp_2d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_2d_ptr)) is_eq = all(shape(f1%real_dp_2d_ptr) == shape(f2%real_dp_2d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_2d_ptr)) is_eq = all(f1%real_dp_2d_ptr == f2%real_dp_2d_ptr)
!! f_side.equality_test[real, 3, PTR]
is_eq = is_eq .and. (associated(f1%real_dp_3d_ptr) .eqv. associated(f2%real_dp_3d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_3d_ptr)) is_eq = all(shape(f1%real_dp_3d_ptr) == shape(f2%real_dp_3d_ptr))
if (.not. is_eq) return
if (associated(f1%real_dp_3d_ptr)) is_eq = all(f1%real_dp_3d_ptr == f2%real_dp_3d_ptr)
!! f_side.equality_test[real, 1, ALLOC]
is_eq = is_eq .and. (allocated(f1%real_dp_1d_alloc) .eqv. allocated(f2%real_dp_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_dp_1d_alloc)) is_eq = all(shape(f1%real_dp_1d_alloc) == shape(f2%real_dp_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_dp_1d_alloc)) is_eq = all(f1%real_dp_1d_alloc == f2%real_dp_1d_alloc)
!! f_side.equality_test[real, 2, ALLOC]
is_eq = is_eq .and. (allocated(f1%real_dp_2d_alloc) .eqv. allocated(f2%real_dp_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_dp_2d_alloc)) is_eq = all(shape(f1%real_dp_2d_alloc) == shape(f2%real_dp_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_dp_2d_alloc)) is_eq = all(f1%real_dp_2d_alloc == f2%real_dp_2d_alloc)
!! f_side.equality_test[real, 3, ALLOC]
is_eq = is_eq .and. (allocated(f1%real_dp_3d_alloc) .eqv. allocated(f2%real_dp_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_dp_3d_alloc)) is_eq = all(shape(f1%real_dp_3d_alloc) == shape(f2%real_dp_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%real_dp_3d_alloc)) is_eq = all(f1%real_dp_3d_alloc == f2%real_dp_3d_alloc)
!! f_side.equality_test[complex, 0, NOT]
is_eq = is_eq .and. (f1%complex_dp_0d == f2%complex_dp_0d)
!! f_side.equality_test[complex, 1, NOT]
is_eq = is_eq .and. all(f1%complex_dp_1d == f2%complex_dp_1d)
!! f_side.equality_test[complex, 2, NOT]
is_eq = is_eq .and. all(f1%complex_dp_2d == f2%complex_dp_2d)
!! f_side.equality_test[complex, 3, NOT]
is_eq = is_eq .and. all(f1%complex_dp_3d == f2%complex_dp_3d)
!! f_side.equality_test[complex, 0, PTR]

is_eq = is_eq .and. (associated(f1%complex_dp_0d_ptr) .eqv. associated(f2%complex_dp_0d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_0d_ptr)) is_eq = (f1%complex_dp_0d_ptr == f2%complex_dp_0d_ptr)
!! f_side.equality_test[complex, 1, PTR]
is_eq = is_eq .and. (associated(f1%complex_dp_1d_ptr) .eqv. associated(f2%complex_dp_1d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_1d_ptr)) is_eq = all(shape(f1%complex_dp_1d_ptr) == shape(f2%complex_dp_1d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_1d_ptr)) is_eq = all(f1%complex_dp_1d_ptr == f2%complex_dp_1d_ptr)
!! f_side.equality_test[complex, 2, PTR]
is_eq = is_eq .and. (associated(f1%complex_dp_2d_ptr) .eqv. associated(f2%complex_dp_2d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_2d_ptr)) is_eq = all(shape(f1%complex_dp_2d_ptr) == shape(f2%complex_dp_2d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_2d_ptr)) is_eq = all(f1%complex_dp_2d_ptr == f2%complex_dp_2d_ptr)
!! f_side.equality_test[complex, 3, PTR]
is_eq = is_eq .and. (associated(f1%complex_dp_3d_ptr) .eqv. associated(f2%complex_dp_3d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_3d_ptr)) is_eq = all(shape(f1%complex_dp_3d_ptr) == shape(f2%complex_dp_3d_ptr))
if (.not. is_eq) return
if (associated(f1%complex_dp_3d_ptr)) is_eq = all(f1%complex_dp_3d_ptr == f2%complex_dp_3d_ptr)
!! f_side.equality_test[complex, 1, ALLOC]
is_eq = is_eq .and. (allocated(f1%complex_dp_1d_alloc) .eqv. allocated(f2%complex_dp_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%complex_dp_1d_alloc)) is_eq = all(shape(f1%complex_dp_1d_alloc) == shape(f2%complex_dp_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%complex_dp_1d_alloc)) is_eq = all(f1%complex_dp_1d_alloc == f2%complex_dp_1d_alloc)
!! f_side.equality_test[complex, 2, ALLOC]
is_eq = is_eq .and. (allocated(f1%complex_dp_2d_alloc) .eqv. allocated(f2%complex_dp_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%complex_dp_2d_alloc)) is_eq = all(shape(f1%complex_dp_2d_alloc) == shape(f2%complex_dp_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%complex_dp_2d_alloc)) is_eq = all(f1%complex_dp_2d_alloc == f2%complex_dp_2d_alloc)
!! f_side.equality_test[complex, 3, ALLOC]
is_eq = is_eq .and. (allocated(f1%complex_dp_3d_alloc) .eqv. allocated(f2%complex_dp_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%complex_dp_3d_alloc)) is_eq = all(shape(f1%complex_dp_3d_alloc) == shape(f2%complex_dp_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%complex_dp_3d_alloc)) is_eq = all(f1%complex_dp_3d_alloc == f2%complex_dp_3d_alloc)
!! f_side.equality_test[integer, 0, NOT]
is_eq = is_eq .and. (f1%int_0d == f2%int_0d)
!! f_side.equality_test[integer, 1, NOT]
is_eq = is_eq .and. all(f1%int_1d == f2%int_1d)
!! f_side.equality_test[integer, 2, NOT]
is_eq = is_eq .and. all(f1%int_2d == f2%int_2d)
!! f_side.equality_test[integer, 3, NOT]
is_eq = is_eq .and. all(f1%int_3d == f2%int_3d)
!! f_side.equality_test[integer, 0, PTR]

is_eq = is_eq .and. (associated(f1%int_0d_ptr) .eqv. associated(f2%int_0d_ptr))
if (.not. is_eq) return
if (associated(f1%int_0d_ptr)) is_eq = (f1%int_0d_ptr == f2%int_0d_ptr)
!! f_side.equality_test[integer, 1, PTR]
is_eq = is_eq .and. (associated(f1%int_1d_ptr) .eqv. associated(f2%int_1d_ptr))
if (.not. is_eq) return
if (associated(f1%int_1d_ptr)) is_eq = all(shape(f1%int_1d_ptr) == shape(f2%int_1d_ptr))
if (.not. is_eq) return
if (associated(f1%int_1d_ptr)) is_eq = all(f1%int_1d_ptr == f2%int_1d_ptr)
!! f_side.equality_test[integer, 2, PTR]
is_eq = is_eq .and. (associated(f1%int_2d_ptr) .eqv. associated(f2%int_2d_ptr))
if (.not. is_eq) return
if (associated(f1%int_2d_ptr)) is_eq = all(shape(f1%int_2d_ptr) == shape(f2%int_2d_ptr))
if (.not. is_eq) return
if (associated(f1%int_2d_ptr)) is_eq = all(f1%int_2d_ptr == f2%int_2d_ptr)
!! f_side.equality_test[integer, 3, PTR]
is_eq = is_eq .and. (associated(f1%int_3d_ptr) .eqv. associated(f2%int_3d_ptr))
if (.not. is_eq) return
if (associated(f1%int_3d_ptr)) is_eq = all(shape(f1%int_3d_ptr) == shape(f2%int_3d_ptr))
if (.not. is_eq) return
if (associated(f1%int_3d_ptr)) is_eq = all(f1%int_3d_ptr == f2%int_3d_ptr)
!! f_side.equality_test[integer, 1, ALLOC]
is_eq = is_eq .and. (allocated(f1%int_1d_alloc) .eqv. allocated(f2%int_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%int_1d_alloc)) is_eq = all(shape(f1%int_1d_alloc) == shape(f2%int_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%int_1d_alloc)) is_eq = all(f1%int_1d_alloc == f2%int_1d_alloc)
!! f_side.equality_test[integer, 2, ALLOC]
is_eq = is_eq .and. (allocated(f1%int_2d_alloc) .eqv. allocated(f2%int_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%int_2d_alloc)) is_eq = all(shape(f1%int_2d_alloc) == shape(f2%int_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%int_2d_alloc)) is_eq = all(f1%int_2d_alloc == f2%int_2d_alloc)
!! f_side.equality_test[integer, 3, ALLOC]
is_eq = is_eq .and. (allocated(f1%int_3d_alloc) .eqv. allocated(f2%int_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%int_3d_alloc)) is_eq = all(shape(f1%int_3d_alloc) == shape(f2%int_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%int_3d_alloc)) is_eq = all(f1%int_3d_alloc == f2%int_3d_alloc)
!! f_side.equality_test[integer8, 0, NOT]
is_eq = is_eq .and. (f1%int8_0d == f2%int8_0d)
!! f_side.equality_test[integer8, 1, NOT]
is_eq = is_eq .and. all(f1%int8_1d == f2%int8_1d)
!! f_side.equality_test[integer8, 2, NOT]
is_eq = is_eq .and. all(f1%int8_2d == f2%int8_2d)
!! f_side.equality_test[integer8, 3, NOT]
is_eq = is_eq .and. all(f1%int8_3d == f2%int8_3d)
!! f_side.equality_test[integer8, 0, PTR]

is_eq = is_eq .and. (associated(f1%int8_0d_ptr) .eqv. associated(f2%int8_0d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_0d_ptr)) is_eq = (f1%int8_0d_ptr == f2%int8_0d_ptr)
!! f_side.equality_test[integer8, 1, PTR]
is_eq = is_eq .and. (associated(f1%int8_1d_ptr) .eqv. associated(f2%int8_1d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_1d_ptr)) is_eq = all(shape(f1%int8_1d_ptr) == shape(f2%int8_1d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_1d_ptr)) is_eq = all(f1%int8_1d_ptr == f2%int8_1d_ptr)
!! f_side.equality_test[integer8, 2, PTR]
is_eq = is_eq .and. (associated(f1%int8_2d_ptr) .eqv. associated(f2%int8_2d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_2d_ptr)) is_eq = all(shape(f1%int8_2d_ptr) == shape(f2%int8_2d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_2d_ptr)) is_eq = all(f1%int8_2d_ptr == f2%int8_2d_ptr)
!! f_side.equality_test[integer8, 3, PTR]
is_eq = is_eq .and. (associated(f1%int8_3d_ptr) .eqv. associated(f2%int8_3d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_3d_ptr)) is_eq = all(shape(f1%int8_3d_ptr) == shape(f2%int8_3d_ptr))
if (.not. is_eq) return
if (associated(f1%int8_3d_ptr)) is_eq = all(f1%int8_3d_ptr == f2%int8_3d_ptr)
!! f_side.equality_test[integer8, 1, ALLOC]
is_eq = is_eq .and. (allocated(f1%int8_1d_alloc) .eqv. allocated(f2%int8_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%int8_1d_alloc)) is_eq = all(shape(f1%int8_1d_alloc) == shape(f2%int8_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%int8_1d_alloc)) is_eq = all(f1%int8_1d_alloc == f2%int8_1d_alloc)
!! f_side.equality_test[integer8, 2, ALLOC]
is_eq = is_eq .and. (allocated(f1%int8_2d_alloc) .eqv. allocated(f2%int8_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%int8_2d_alloc)) is_eq = all(shape(f1%int8_2d_alloc) == shape(f2%int8_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%int8_2d_alloc)) is_eq = all(f1%int8_2d_alloc == f2%int8_2d_alloc)
!! f_side.equality_test[integer8, 3, ALLOC]
is_eq = is_eq .and. (allocated(f1%int8_3d_alloc) .eqv. allocated(f2%int8_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%int8_3d_alloc)) is_eq = all(shape(f1%int8_3d_alloc) == shape(f2%int8_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%int8_3d_alloc)) is_eq = all(f1%int8_3d_alloc == f2%int8_3d_alloc)
!! f_side.equality_test[logical, 0, NOT]
is_eq = is_eq .and. (f1%logical_0d .eqv. f2%logical_0d)
!! f_side.equality_test[logical, 1, NOT]
is_eq = is_eq .and. all(f1%logical_1d .eqv. f2%logical_1d)
!! f_side.equality_test[logical, 2, NOT]
is_eq = is_eq .and. all(f1%logical_2d .eqv. f2%logical_2d)
!! f_side.equality_test[logical, 3, NOT]
is_eq = is_eq .and. all(f1%logical_3d .eqv. f2%logical_3d)
!! f_side.equality_test[logical, 0, PTR]

is_eq = is_eq .and. (associated(f1%logical_0d_ptr) .eqv. associated(f2%logical_0d_ptr))
if (.not. is_eq) return
if (associated(f1%logical_0d_ptr)) is_eq = (f1%logical_0d_ptr .eqv. f2%logical_0d_ptr)
!! f_side.equality_test[type, 0, NOT]
is_eq = is_eq .and. (f1%type_0d == f2%type_0d)
!! f_side.equality_test[type, 1, NOT]
is_eq = is_eq .and. all(f1%type_1d == f2%type_1d)
!! f_side.equality_test[type, 2, NOT]
is_eq = is_eq .and. all(f1%type_2d == f2%type_2d)
!! f_side.equality_test[type, 3, NOT]
is_eq = is_eq .and. all(f1%type_3d == f2%type_3d)
!! f_side.equality_test[type, 0, PTR]

is_eq = is_eq .and. (associated(f1%type_0d_ptr) .eqv. associated(f2%type_0d_ptr))
if (.not. is_eq) return
if (associated(f1%type_0d_ptr)) is_eq = (f1%type_0d_ptr == f2%type_0d_ptr)
!! f_side.equality_test[type, 1, PTR]
is_eq = is_eq .and. (associated(f1%type_1d_ptr) .eqv. associated(f2%type_1d_ptr))
if (.not. is_eq) return
if (associated(f1%type_1d_ptr)) is_eq = all(shape(f1%type_1d_ptr) == shape(f2%type_1d_ptr))
if (.not. is_eq) return
if (associated(f1%type_1d_ptr)) is_eq = all(f1%type_1d_ptr == f2%type_1d_ptr)
!! f_side.equality_test[type, 2, PTR]
is_eq = is_eq .and. (associated(f1%type_2d_ptr) .eqv. associated(f2%type_2d_ptr))
if (.not. is_eq) return
if (associated(f1%type_2d_ptr)) is_eq = all(shape(f1%type_2d_ptr) == shape(f2%type_2d_ptr))
if (.not. is_eq) return
if (associated(f1%type_2d_ptr)) is_eq = all(f1%type_2d_ptr == f2%type_2d_ptr)
!! f_side.equality_test[type, 3, PTR]
is_eq = is_eq .and. (associated(f1%type_3d_ptr) .eqv. associated(f2%type_3d_ptr))
if (.not. is_eq) return
if (associated(f1%type_3d_ptr)) is_eq = all(shape(f1%type_3d_ptr) == shape(f2%type_3d_ptr))
if (.not. is_eq) return
if (associated(f1%type_3d_ptr)) is_eq = all(f1%type_3d_ptr == f2%type_3d_ptr)
!! f_side.equality_test[type, 1, ALLOC]
is_eq = is_eq .and. (allocated(f1%type_1d_alloc) .eqv. allocated(f2%type_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%type_1d_alloc)) is_eq = all(shape(f1%type_1d_alloc) == shape(f2%type_1d_alloc))
if (.not. is_eq) return
if (allocated(f1%type_1d_alloc)) is_eq = all(f1%type_1d_alloc == f2%type_1d_alloc)
!! f_side.equality_test[type, 2, ALLOC]
is_eq = is_eq .and. (allocated(f1%type_2d_alloc) .eqv. allocated(f2%type_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%type_2d_alloc)) is_eq = all(shape(f1%type_2d_alloc) == shape(f2%type_2d_alloc))
if (.not. is_eq) return
if (allocated(f1%type_2d_alloc)) is_eq = all(f1%type_2d_alloc == f2%type_2d_alloc)
!! f_side.equality_test[type, 3, ALLOC]
is_eq = is_eq .and. (allocated(f1%type_3d_alloc) .eqv. allocated(f2%type_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%type_3d_alloc)) is_eq = all(shape(f1%type_3d_alloc) == shape(f2%type_3d_alloc))
if (.not. is_eq) return
if (allocated(f1%type_3d_alloc)) is_eq = all(f1%type_3d_alloc == f2%type_3d_alloc)

end function eq_all_encompassing
end module
