//+
// C++ side of the Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY!
//-

#include "converter_templates.h"
#include "cpp_bmad_classes.h"
#include <iostream>
#include <sstream>

using namespace Bmad;
