//+
// C++ equality functions for Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY!
//-

#include <iostream>
#include <vector>
#include <string>

#include "cpp_bmad_classes.h"
#include "bmad_std_typedef.h"

using namespace std;

using std::vector, std::string;

//---------------------------------------------------

template <class T>
bool is_all_equal(const vector<T> &vec1, const vector<T> &vec2) {
  if (vec1.size() != vec2.size())
    return false;
  for (size_t i = 0; i < vec1.size(); i++) {
    if (!(vec1[i] == vec2[i]))
      return false;
  }
  return true;
}

template <class T>
bool is_all_equal(const vector<vector<T>> &mat1,
                  const vector<vector<T>> &mat2) {
  if (mat1.size() != mat2.size())
    return false;
  for (size_t i = 0; i < mat1.size(); i++) {
    if (mat1[i].size() != mat2[i].size())
      return false;
    for (size_t j = 0; j < mat1[i].size(); j++) {
      if (!(mat1[i][j] == mat2[i][j]))
        return false;
    }
  }
  return true;
}

template <class T>
bool is_all_equal(const vector<vector<vector<T>>> &tensor1,
                  const vector<vector<vector<T>>> &tensor2) {
  if (tensor1.size() != tensor2.size())
    return false;
  for (size_t i = 0; i < tensor1.size(); i++) {
    if (tensor1[i].size() != tensor2[i].size())
      return false;
    for (size_t j = 0; j < tensor1[i].size(); j++) {
      if (tensor1[i][j].size() != tensor2[i][j].size())
        return false;
      for (size_t k = 0; k < tensor1[i][j].size(); k++) {
        if (!(tensor1[i][j][k] == tensor2[i][j][k]))
          return false;
      }
    }
  }
  return true;
}

//---------------------------------------------------

template bool is_all_equal(const Array<Bool> &, const Array<Bool> &);
template bool is_all_equal(const Array<Complex> &, const Array<Complex> &);
template bool is_all_equal(const Array<Real> &, const Array<Real> &);
template bool is_all_equal(const Array<Int> &, const Array<Int> &);
template bool is_all_equal(const Array<string> &, const Array<string> &);

template bool is_all_equal(const Matrix<Bool> &, const Matrix<Bool> &);
template bool is_all_equal(const Matrix<Complex> &, const Matrix<Complex> &);
template bool is_all_equal(const Matrix<Real> &, const Matrix<Real> &);
template bool is_all_equal(const Matrix<Int> &, const Matrix<Int> &);

template bool is_all_equal(const Tensor<Complex> &, const Tensor<Complex> &);
template bool is_all_equal(const Tensor<Real> &, const Tensor<Real> &);
template bool is_all_equal(const Tensor<Int> &, const Tensor<Int> &);
