//+
// C++ equality functions for Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY!
//-

#include "cpp_bmad_classes.h"
#include <iostream>
#include <stdlib.h>

using namespace std;

//---------------------------------------------------

template <class T>
bool is_all_equal(const vector<T> &vec1, const vector<T> &vec2) {
  if (vec1.size() != vec2.size())
    return false;
  for (size_t i = 0; i < vec1.size(); i++) {
    if (!(vec1[i] == vec2[i]))
      return false;
  }
  return true;
}

template <class T>
bool is_all_equal(const vector<vector<T>> &mat1,
                  const vector<vector<T>> &mat2) {
  if (mat1.size() != mat2.size())
    return false;
  for (size_t i = 0; i < mat1.size(); i++) {
    if (mat1[i].size() != mat2[i].size())
      return false;
    for (size_t j = 0; j < mat1[i].size(); j++) {
      if (!(mat1[i][j] == mat2[i][j]))
        return false;
    }
  }
  return true;
}

template <class T>
bool is_all_equal(const vector<vector<vector<T>>> &tensor1,
                  const vector<vector<vector<T>>> &tensor2) {
  if (tensor1.size() != tensor2.size())
    return false;
  for (size_t i = 0; i < tensor1.size(); i++) {
    if (tensor1[i].size() != tensor2[i].size())
      return false;
    for (size_t j = 0; j < tensor1[i].size(); j++) {
      if (tensor1[i][j].size() != tensor2[i][j].size())
        return false;
      for (size_t k = 0; k < tensor1[i][j].size(); k++) {
        if (!(tensor1[i][j][k] == tensor2[i][j][k]))
          return false;
      }
    }
  }
  return true;
}

//---------------------------------------------------

template bool is_all_equal(const Bool_ARRAY &, const Bool_ARRAY &);
template bool is_all_equal(const Complex_ARRAY &, const Complex_ARRAY &);
template bool is_all_equal(const Real_ARRAY &, const Real_ARRAY &);
template bool is_all_equal(const Int_ARRAY &, const Int_ARRAY &);
template bool is_all_equal(const String_ARRAY &, const String_ARRAY &);

template bool is_all_equal(const Bool_MATRIX &, const Bool_MATRIX &);
template bool is_all_equal(const Complex_MATRIX &, const Complex_MATRIX &);
template bool is_all_equal(const Real_MATRIX &, const Real_MATRIX &);
template bool is_all_equal(const Int_MATRIX &, const Int_MATRIX &);

template bool is_all_equal(const Complex_TENSOR &, const Complex_TENSOR &);
template bool is_all_equal(const Real_TENSOR &, const Real_TENSOR &);
template bool is_all_equal(const Int_TENSOR &, const Int_TENSOR &);
