
!+
! Fortran side of the Bmad / C++ structure interface.
!
! This file is generated by the Bmad/C++ interface code generation.
! The code generation files can be found in cpp_bmad_interface.
!
! DO NOT EDIT THIS FILE DIRECTLY! 
!-

module bmad_cpp_convert_mod

use test_struct_defs
use fortran_cpp_utils
use, intrinsic :: iso_c_binding

!--------------------------------------------------------------------------

interface 
  subroutine wake_lr_to_f (C, Fp) bind(c)
    import c_ptr
    type(c_ptr), value :: C, Fp
  end subroutine
end interface

!--------------------------------------------------------------------------

interface 
  subroutine wake_to_f (C, Fp) bind(c)
    import c_ptr
    type(c_ptr), value :: C, Fp
  end subroutine
end interface

!--------------------------------------------------------------------------

interface 
  subroutine all_encompassing_to_f (C, Fp) bind(c)
    import c_ptr
    type(c_ptr), value :: C, Fp
  end subroutine
end interface

contains

!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!+
! Subroutine wake_lr_to_c (Fp, C) bind(c)
!
! Routine to convert a Bmad wake_lr_struct to a C++ CPP_wake_lr structure
!
! Input:
!   Fp -- type(c_ptr), value :: Input Bmad wake_lr_struct structure.
!
! Output:
!   C -- type(c_ptr), value :: Output C++ CPP_wake_lr struct.
!-

subroutine wake_lr_to_c (Fp, C) bind(c)

implicit none

interface
  !! f_side.to_c2_f2_sub_arg
  subroutine wake_lr_to_c2 (C, z_aaa, z_bbb, z_file, z_t_ref, z_freq_spread) bind(c)
    import c_bool, c_double, c_ptr, c_char, c_int, c_long, c_double_complex
    !! f_side.to_c2_type :: f_side.to_c2_name
    type(c_ptr), value :: C
    integer(c_long) :: z_aaa
    integer(c_int) :: z_bbb
    character(c_char) :: z_file(*)
    real(c_double) :: z_t_ref, z_freq_spread
  end subroutine
end interface

type(c_ptr), value :: Fp
type(c_ptr), value :: C
type(wake_lr_struct), pointer :: F
integer jd, jd1, jd2, jd3, lb1, lb2, lb3
!! f_side.to_c_var

!

call c_f_pointer (Fp, F)


!! f_side.to_c2_call
call wake_lr_to_c2 (C, F%aaa, F%bbb, trim(F%file) // c_null_char, F%t_ref, F%freq_spread)

end subroutine wake_lr_to_c

!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!+
! Subroutine wake_lr_to_f2 (Fp, ...etc...) bind(c)
!
! Routine used in converting a C++ CPP_wake_lr structure to a Bmad wake_lr_struct structure.
! This routine is called by wake_lr_to_c and is not meant to be called directly.
!
! Input:
!   ...etc... -- Components of the structure. See the wake_lr_to_f2 code for more details.
!
! Output:
!   Fp -- type(c_ptr), value :: Bmad wake_lr_struct structure.
!-

!! f_side.to_c2_f2_sub_arg
subroutine wake_lr_to_f2 (Fp, z_aaa, z_bbb, z_file, z_t_ref, z_freq_spread) bind(c)


implicit none

type(c_ptr), value :: Fp
type(wake_lr_struct), pointer :: F
integer jd, jd1, jd2, jd3, lb1, lb2, lb3
!! f_side.to_f2_var && f_side.to_f2_type :: f_side.to_f2_name
integer(c_long) :: z_aaa
integer(c_int) :: z_bbb
character(c_char) :: z_file(*)
real(c_double) :: z_t_ref, z_freq_spread

call c_f_pointer (Fp, F)

!! f_side.to_f2_trans[integer8, 0, NOT]
F%aaa = z_aaa
!! f_side.to_f2_trans[integer, 0, NOT]
F%bbb = z_bbb
!! f_side.to_f2_trans[character, 0, NOT]
call to_f_str(z_file, F%file)
!! f_side.to_f2_trans[real, 0, NOT]
F%t_ref = z_t_ref
!! f_side.to_f2_trans[real, 0, NOT]
F%freq_spread = z_freq_spread

end subroutine wake_lr_to_f2

!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!+
! Subroutine wake_to_c (Fp, C) bind(c)
!
! Routine to convert a Bmad wake_struct to a C++ CPP_wake structure
!
! Input:
!   Fp -- type(c_ptr), value :: Input Bmad wake_struct structure.
!
! Output:
!   C -- type(c_ptr), value :: Output C++ CPP_wake struct.
!-

subroutine wake_to_c (Fp, C) bind(c)

implicit none

interface
  !! f_side.to_c2_f2_sub_arg
  subroutine wake_to_c2 (C, z_sr) bind(c)
    import c_bool, c_double, c_ptr, c_char, c_int, c_long, c_double_complex
    !! f_side.to_c2_type :: f_side.to_c2_name
    type(c_ptr), value :: C
    type(c_ptr), value :: z_sr
  end subroutine
end interface

type(c_ptr), value :: Fp
type(c_ptr), value :: C
type(wake_struct), pointer :: F
integer jd, jd1, jd2, jd3, lb1, lb2, lb3
!! f_side.to_c_var

!

call c_f_pointer (Fp, F)


!! f_side.to_c2_call
call wake_to_c2 (C, c_loc(F%sr))

end subroutine wake_to_c

!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!+
! Subroutine wake_to_f2 (Fp, ...etc...) bind(c)
!
! Routine used in converting a C++ CPP_wake structure to a Bmad wake_struct structure.
! This routine is called by wake_to_c and is not meant to be called directly.
!
! Input:
!   ...etc... -- Components of the structure. See the wake_to_f2 code for more details.
!
! Output:
!   Fp -- type(c_ptr), value :: Bmad wake_struct structure.
!-

!! f_side.to_c2_f2_sub_arg
subroutine wake_to_f2 (Fp, z_sr) bind(c)


implicit none

type(c_ptr), value :: Fp
type(wake_struct), pointer :: F
integer jd, jd1, jd2, jd3, lb1, lb2, lb3
!! f_side.to_f2_var && f_side.to_f2_type :: f_side.to_f2_name
type(c_ptr), value :: z_sr

call c_f_pointer (Fp, F)

!! f_side.to_f2_trans[type, 0, NOT]
call wake_lr_to_f(z_sr, c_loc(F%sr))

end subroutine wake_to_f2

!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!+
! Subroutine all_encompassing_to_c (Fp, C) bind(c)
!
! Routine to convert a Bmad all_encompassing_struct to a C++ CPP_all_encompassing structure
!
! Input:
!   Fp -- type(c_ptr), value :: Input Bmad all_encompassing_struct structure.
!
! Output:
!   C -- type(c_ptr), value :: Output C++ CPP_all_encompassing struct.
!-

subroutine all_encompassing_to_c (Fp, C) bind(c)

implicit none

interface
  !! f_side.to_c2_f2_sub_arg
  subroutine all_encompassing_to_c2 (C, z_real_rp_0d, z_real_rp_1d, z_real_rp_2d, z_real_rp_3d, &
      z_real_rp_0d_ptr, n_real_rp_0d_ptr, z_real_rp_1d_ptr, n1_real_rp_1d_ptr, &
      z_real_rp_2d_ptr, n1_real_rp_2d_ptr, n2_real_rp_2d_ptr, z_real_rp_3d_ptr, &
      n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr, z_real_rp_1d_alloc, &
      n1_real_rp_1d_alloc, z_real_rp_2d_alloc, n1_real_rp_2d_alloc, n2_real_rp_2d_alloc, &
      z_real_rp_3d_alloc, n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc, &
      z_real_dp_0d, z_real_dp_1d, z_real_dp_2d, z_real_dp_3d, z_real_dp_0d_ptr, &
      n_real_dp_0d_ptr, z_real_dp_1d_ptr, n1_real_dp_1d_ptr, z_real_dp_2d_ptr, &
      n1_real_dp_2d_ptr, n2_real_dp_2d_ptr, z_real_dp_3d_ptr, n1_real_dp_3d_ptr, &
      n2_real_dp_3d_ptr, n3_real_dp_3d_ptr, z_real_dp_1d_alloc, n1_real_dp_1d_alloc, &
      z_real_dp_2d_alloc, n1_real_dp_2d_alloc, n2_real_dp_2d_alloc, z_real_dp_3d_alloc, &
      n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, n3_real_dp_3d_alloc, z_complex_dp_0d, &
      z_complex_dp_1d, z_complex_dp_2d, z_complex_dp_3d, z_complex_dp_0d_ptr, &
      n_complex_dp_0d_ptr, z_complex_dp_1d_ptr, n1_complex_dp_1d_ptr, z_complex_dp_2d_ptr, &
      n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr, z_complex_dp_3d_ptr, n1_complex_dp_3d_ptr, &
      n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr, z_complex_dp_1d_alloc, &
      n1_complex_dp_1d_alloc, z_complex_dp_2d_alloc, n1_complex_dp_2d_alloc, &
      n2_complex_dp_2d_alloc, z_complex_dp_3d_alloc, n1_complex_dp_3d_alloc, &
      n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc, z_int_0d, z_int_1d, z_int_2d, z_int_3d, &
      z_int_0d_ptr, n_int_0d_ptr, z_int_1d_ptr, n1_int_1d_ptr, z_int_2d_ptr, n1_int_2d_ptr, &
      n2_int_2d_ptr, z_int_3d_ptr, n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr, z_int_1d_alloc, &
      n1_int_1d_alloc, z_int_2d_alloc, n1_int_2d_alloc, n2_int_2d_alloc, z_int_3d_alloc, &
      n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc, z_int8_0d, z_int8_1d, z_int8_2d, &
      z_int8_3d, z_int8_0d_ptr, n_int8_0d_ptr, z_int8_1d_ptr, n1_int8_1d_ptr, z_int8_2d_ptr, &
      n1_int8_2d_ptr, n2_int8_2d_ptr, z_int8_3d_ptr, n1_int8_3d_ptr, n2_int8_3d_ptr, &
      n3_int8_3d_ptr, z_int8_1d_alloc, n1_int8_1d_alloc, z_int8_2d_alloc, n1_int8_2d_alloc, &
      n2_int8_2d_alloc, z_int8_3d_alloc, n1_int8_3d_alloc, n2_int8_3d_alloc, n3_int8_3d_alloc, &
      z_logical_0d, z_logical_1d, z_logical_2d, z_logical_3d, z_logical_0d_ptr, &
      n_logical_0d_ptr, z_type_0d, z_type_1d, z_type_2d, z_type_3d, z_type_0d_ptr, &
      n_type_0d_ptr, z_type_1d_ptr, n1_type_1d_ptr, z_type_2d_ptr, n1_type_2d_ptr, &
      n2_type_2d_ptr, z_type_3d_ptr, n1_type_3d_ptr, n2_type_3d_ptr, n3_type_3d_ptr, &
      z_type_1d_alloc, n1_type_1d_alloc, z_type_2d_alloc, n1_type_2d_alloc, n2_type_2d_alloc, &
      z_type_3d_alloc, n1_type_3d_alloc, n2_type_3d_alloc, n3_type_3d_alloc) bind(c)
    import c_bool, c_double, c_ptr, c_char, c_int, c_long, c_double_complex
    !! f_side.to_c2_type :: f_side.to_c2_name
    type(c_ptr), value :: C
    real(c_double) :: z_real_rp_0d, z_real_rp_1d(*), z_real_rp_2d(*), z_real_rp_3d(*), z_real_rp_0d_ptr, z_real_rp_1d_ptr(*), z_real_rp_2d_ptr(*)
    real(c_double) :: z_real_rp_3d_ptr(*), z_real_rp_1d_alloc(*), z_real_rp_2d_alloc(*), z_real_rp_3d_alloc(*), z_real_dp_0d, z_real_dp_1d(*), z_real_dp_2d(*)
    real(c_double) :: z_real_dp_3d(*), z_real_dp_0d_ptr, z_real_dp_1d_ptr(*), z_real_dp_2d_ptr(*), z_real_dp_3d_ptr(*), z_real_dp_1d_alloc(*), z_real_dp_2d_alloc(*)
    real(c_double) :: z_real_dp_3d_alloc(*)
    integer(c_int), value :: n_real_rp_0d_ptr, n1_real_rp_1d_ptr, n1_real_rp_2d_ptr, n2_real_rp_2d_ptr, n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr
    integer(c_int), value :: n1_real_rp_1d_alloc, n1_real_rp_2d_alloc, n2_real_rp_2d_alloc, n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc, n_real_dp_0d_ptr
    integer(c_int), value :: n1_real_dp_1d_ptr, n1_real_dp_2d_ptr, n2_real_dp_2d_ptr, n1_real_dp_3d_ptr, n2_real_dp_3d_ptr, n3_real_dp_3d_ptr, n1_real_dp_1d_alloc
    integer(c_int), value :: n1_real_dp_2d_alloc, n2_real_dp_2d_alloc, n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, n3_real_dp_3d_alloc, n_complex_dp_0d_ptr, n1_complex_dp_1d_ptr
    integer(c_int), value :: n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr, n1_complex_dp_3d_ptr, n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr, n1_complex_dp_1d_alloc, n1_complex_dp_2d_alloc
    integer(c_int), value :: n2_complex_dp_2d_alloc, n1_complex_dp_3d_alloc, n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc, n_int_0d_ptr, n1_int_1d_ptr, n1_int_2d_ptr
    integer(c_int), value :: n2_int_2d_ptr, n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr, n1_int_1d_alloc, n1_int_2d_alloc, n2_int_2d_alloc
    integer(c_int), value :: n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc, n_int8_0d_ptr, n1_int8_1d_ptr, n1_int8_2d_ptr, n2_int8_2d_ptr
    integer(c_int), value :: n1_int8_3d_ptr, n2_int8_3d_ptr, n3_int8_3d_ptr, n1_int8_1d_alloc, n1_int8_2d_alloc, n2_int8_2d_alloc, n1_int8_3d_alloc
    integer(c_int), value :: n2_int8_3d_alloc, n3_int8_3d_alloc, n_logical_0d_ptr, n_type_0d_ptr, n1_type_1d_ptr, n1_type_2d_ptr, n2_type_2d_ptr
    integer(c_int), value :: n1_type_3d_ptr, n2_type_3d_ptr, n3_type_3d_ptr, n1_type_1d_alloc, n1_type_2d_alloc, n2_type_2d_alloc, n1_type_3d_alloc
    integer(c_int), value :: n2_type_3d_alloc, n3_type_3d_alloc
    complex(c_double_complex) :: z_complex_dp_0d, z_complex_dp_1d(*), z_complex_dp_2d(*), z_complex_dp_3d(*), z_complex_dp_0d_ptr, z_complex_dp_1d_ptr(*), z_complex_dp_2d_ptr(*)
    complex(c_double_complex) :: z_complex_dp_3d_ptr(*), z_complex_dp_1d_alloc(*), z_complex_dp_2d_alloc(*), z_complex_dp_3d_alloc(*)
    integer(c_int) :: z_int_0d, z_int_1d(*), z_int_2d(*), z_int_3d(*), z_int_0d_ptr, z_int_1d_ptr(*), z_int_2d_ptr(*)
    integer(c_int) :: z_int_3d_ptr(*), z_int_1d_alloc(*), z_int_2d_alloc(*), z_int_3d_alloc(*)
    integer(c_long) :: z_int8_0d, z_int8_1d(*), z_int8_2d(*), z_int8_3d(*), z_int8_0d_ptr, z_int8_1d_ptr(*), z_int8_2d_ptr(*)
    integer(c_long) :: z_int8_3d_ptr(*), z_int8_1d_alloc(*), z_int8_2d_alloc(*), z_int8_3d_alloc(*)
    logical(c_bool) :: z_logical_0d, z_logical_1d(*), z_logical_2d(*), z_logical_3d(*), z_logical_0d_ptr
    type(c_ptr), value :: z_type_0d, z_type_0d_ptr
    type(c_ptr) :: z_type_1d(*), z_type_2d(*), z_type_3d(*), z_type_1d_ptr(*), z_type_2d_ptr(*), z_type_3d_ptr(*), z_type_1d_alloc(*)
    type(c_ptr) :: z_type_2d_alloc(*), z_type_3d_alloc(*)
  end subroutine
end interface

type(c_ptr), value :: Fp
type(c_ptr), value :: C
type(all_encompassing_struct), pointer :: F
integer jd, jd1, jd2, jd3, lb1, lb2, lb3
!! f_side.to_c_var
integer(c_int) :: n_real_rp_0d_ptr
integer(c_int) :: n1_real_rp_1d_ptr
integer(c_int) :: n1_real_rp_2d_ptr
integer(c_int) :: n2_real_rp_2d_ptr
integer(c_int) :: n1_real_rp_3d_ptr
integer(c_int) :: n2_real_rp_3d_ptr
integer(c_int) :: n3_real_rp_3d_ptr
integer(c_int) :: n1_real_rp_1d_alloc
integer(c_int) :: n1_real_rp_2d_alloc
integer(c_int) :: n2_real_rp_2d_alloc
integer(c_int) :: n1_real_rp_3d_alloc
integer(c_int) :: n2_real_rp_3d_alloc
integer(c_int) :: n3_real_rp_3d_alloc
integer(c_int) :: n_real_dp_0d_ptr
integer(c_int) :: n1_real_dp_1d_ptr
integer(c_int) :: n1_real_dp_2d_ptr
integer(c_int) :: n2_real_dp_2d_ptr
integer(c_int) :: n1_real_dp_3d_ptr
integer(c_int) :: n2_real_dp_3d_ptr
integer(c_int) :: n3_real_dp_3d_ptr
integer(c_int) :: n1_real_dp_1d_alloc
integer(c_int) :: n1_real_dp_2d_alloc
integer(c_int) :: n2_real_dp_2d_alloc
integer(c_int) :: n1_real_dp_3d_alloc
integer(c_int) :: n2_real_dp_3d_alloc
integer(c_int) :: n3_real_dp_3d_alloc
integer(c_int) :: n_complex_dp_0d_ptr
integer(c_int) :: n1_complex_dp_1d_ptr
integer(c_int) :: n1_complex_dp_2d_ptr
integer(c_int) :: n2_complex_dp_2d_ptr
integer(c_int) :: n1_complex_dp_3d_ptr
integer(c_int) :: n2_complex_dp_3d_ptr
integer(c_int) :: n3_complex_dp_3d_ptr
integer(c_int) :: n1_complex_dp_1d_alloc
integer(c_int) :: n1_complex_dp_2d_alloc
integer(c_int) :: n2_complex_dp_2d_alloc
integer(c_int) :: n1_complex_dp_3d_alloc
integer(c_int) :: n2_complex_dp_3d_alloc
integer(c_int) :: n3_complex_dp_3d_alloc
integer(c_int) :: n_int_0d_ptr
integer(c_int) :: n1_int_1d_ptr
integer(c_int) :: n1_int_2d_ptr
integer(c_int) :: n2_int_2d_ptr
integer(c_int) :: n1_int_3d_ptr
integer(c_int) :: n2_int_3d_ptr
integer(c_int) :: n3_int_3d_ptr
integer(c_int) :: n1_int_1d_alloc
integer(c_int) :: n1_int_2d_alloc
integer(c_int) :: n2_int_2d_alloc
integer(c_int) :: n1_int_3d_alloc
integer(c_int) :: n2_int_3d_alloc
integer(c_int) :: n3_int_3d_alloc
integer(c_int) :: n_int8_0d_ptr
integer(c_int) :: n1_int8_1d_ptr
integer(c_int) :: n1_int8_2d_ptr
integer(c_int) :: n2_int8_2d_ptr
integer(c_int) :: n1_int8_3d_ptr
integer(c_int) :: n2_int8_3d_ptr
integer(c_int) :: n3_int8_3d_ptr
integer(c_int) :: n1_int8_1d_alloc
integer(c_int) :: n1_int8_2d_alloc
integer(c_int) :: n2_int8_2d_alloc
integer(c_int) :: n1_int8_3d_alloc
integer(c_int) :: n2_int8_3d_alloc
integer(c_int) :: n3_int8_3d_alloc
integer(c_int) :: n_logical_0d_ptr
type(c_ptr) :: z_type_1d(3)
type(c_ptr) :: z_type_2d(3*4)
type(c_ptr) :: z_type_3d(3*4*5)
integer(c_int) :: n_type_0d_ptr
type(c_ptr), allocatable :: z_type_1d_ptr(:)
integer(c_int) :: n1_type_1d_ptr
type(c_ptr), allocatable :: z_type_2d_ptr(:)
integer(c_int) :: n1_type_2d_ptr
integer(c_int) :: n2_type_2d_ptr
type(c_ptr), allocatable :: z_type_3d_ptr(:)
integer(c_int) :: n1_type_3d_ptr
integer(c_int) :: n2_type_3d_ptr
integer(c_int) :: n3_type_3d_ptr
type(c_ptr), allocatable :: z_type_1d_alloc(:)
integer(c_int) :: n1_type_1d_alloc
type(c_ptr), allocatable :: z_type_2d_alloc(:)
integer(c_int) :: n1_type_2d_alloc
integer(c_int) :: n2_type_2d_alloc
type(c_ptr), allocatable :: z_type_3d_alloc(:)
integer(c_int) :: n1_type_3d_alloc
integer(c_int) :: n2_type_3d_alloc
integer(c_int) :: n3_type_3d_alloc

!

call c_f_pointer (Fp, F)

!! f_side.to_c_trans[real, 0, PTR]
n_real_rp_0d_ptr = 0
if (associated(F%real_rp_0d_ptr)) n_real_rp_0d_ptr = 1
!! f_side.to_c_trans[real, 1, PTR]
n1_real_rp_1d_ptr = 0
if (associated(F%real_rp_1d_ptr)) then
  n1_real_rp_1d_ptr = size(F%real_rp_1d_ptr, 1)
endif
!! f_side.to_c_trans[real, 2, PTR]
if (associated(F%real_rp_2d_ptr)) then
  n1_real_rp_2d_ptr = size(F%real_rp_2d_ptr, 1)
  n2_real_rp_2d_ptr = size(F%real_rp_2d_ptr, 2)
else
  n1_real_rp_2d_ptr = 0; n2_real_rp_2d_ptr = 0
endif
!! f_side.to_c_trans[real, 3, PTR]
if (associated(F%real_rp_3d_ptr)) then
  n1_real_rp_3d_ptr = size(F%real_rp_3d_ptr, 1)
  n2_real_rp_3d_ptr = size(F%real_rp_3d_ptr, 2)
  n3_real_rp_3d_ptr = size(F%real_rp_3d_ptr, 3)
else
  n1_real_rp_3d_ptr = 0; n2_real_rp_3d_ptr = 0; n3_real_rp_3d_ptr = 0
endif
!! f_side.to_c_trans[real, 1, ALLOC]
n1_real_rp_1d_alloc = 0
if (allocated(F%real_rp_1d_alloc)) then
  n1_real_rp_1d_alloc = size(F%real_rp_1d_alloc, 1)
endif
!! f_side.to_c_trans[real, 2, ALLOC]
if (allocated(F%real_rp_2d_alloc)) then
  n1_real_rp_2d_alloc = size(F%real_rp_2d_alloc, 1)
  n2_real_rp_2d_alloc = size(F%real_rp_2d_alloc, 2)
else
  n1_real_rp_2d_alloc = 0; n2_real_rp_2d_alloc = 0
endif
!! f_side.to_c_trans[real, 3, ALLOC]
if (allocated(F%real_rp_3d_alloc)) then
  n1_real_rp_3d_alloc = size(F%real_rp_3d_alloc, 1)
  n2_real_rp_3d_alloc = size(F%real_rp_3d_alloc, 2)
  n3_real_rp_3d_alloc = size(F%real_rp_3d_alloc, 3)
else
  n1_real_rp_3d_alloc = 0; n2_real_rp_3d_alloc = 0; n3_real_rp_3d_alloc = 0
endif
!! f_side.to_c_trans[real, 0, PTR]
n_real_dp_0d_ptr = 0
if (associated(F%real_dp_0d_ptr)) n_real_dp_0d_ptr = 1
!! f_side.to_c_trans[real, 1, PTR]
n1_real_dp_1d_ptr = 0
if (associated(F%real_dp_1d_ptr)) then
  n1_real_dp_1d_ptr = size(F%real_dp_1d_ptr, 1)
endif
!! f_side.to_c_trans[real, 2, PTR]
if (associated(F%real_dp_2d_ptr)) then
  n1_real_dp_2d_ptr = size(F%real_dp_2d_ptr, 1)
  n2_real_dp_2d_ptr = size(F%real_dp_2d_ptr, 2)
else
  n1_real_dp_2d_ptr = 0; n2_real_dp_2d_ptr = 0
endif
!! f_side.to_c_trans[real, 3, PTR]
if (associated(F%real_dp_3d_ptr)) then
  n1_real_dp_3d_ptr = size(F%real_dp_3d_ptr, 1)
  n2_real_dp_3d_ptr = size(F%real_dp_3d_ptr, 2)
  n3_real_dp_3d_ptr = size(F%real_dp_3d_ptr, 3)
else
  n1_real_dp_3d_ptr = 0; n2_real_dp_3d_ptr = 0; n3_real_dp_3d_ptr = 0
endif
!! f_side.to_c_trans[real, 1, ALLOC]
n1_real_dp_1d_alloc = 0
if (allocated(F%real_dp_1d_alloc)) then
  n1_real_dp_1d_alloc = size(F%real_dp_1d_alloc, 1)
endif
!! f_side.to_c_trans[real, 2, ALLOC]
if (allocated(F%real_dp_2d_alloc)) then
  n1_real_dp_2d_alloc = size(F%real_dp_2d_alloc, 1)
  n2_real_dp_2d_alloc = size(F%real_dp_2d_alloc, 2)
else
  n1_real_dp_2d_alloc = 0; n2_real_dp_2d_alloc = 0
endif
!! f_side.to_c_trans[real, 3, ALLOC]
if (allocated(F%real_dp_3d_alloc)) then
  n1_real_dp_3d_alloc = size(F%real_dp_3d_alloc, 1)
  n2_real_dp_3d_alloc = size(F%real_dp_3d_alloc, 2)
  n3_real_dp_3d_alloc = size(F%real_dp_3d_alloc, 3)
else
  n1_real_dp_3d_alloc = 0; n2_real_dp_3d_alloc = 0; n3_real_dp_3d_alloc = 0
endif
!! f_side.to_c_trans[complex, 0, PTR]
n_complex_dp_0d_ptr = 0
if (associated(F%complex_dp_0d_ptr)) n_complex_dp_0d_ptr = 1
!! f_side.to_c_trans[complex, 1, PTR]
n1_complex_dp_1d_ptr = 0
if (associated(F%complex_dp_1d_ptr)) then
  n1_complex_dp_1d_ptr = size(F%complex_dp_1d_ptr, 1)
endif
!! f_side.to_c_trans[complex, 2, PTR]
if (associated(F%complex_dp_2d_ptr)) then
  n1_complex_dp_2d_ptr = size(F%complex_dp_2d_ptr, 1)
  n2_complex_dp_2d_ptr = size(F%complex_dp_2d_ptr, 2)
else
  n1_complex_dp_2d_ptr = 0; n2_complex_dp_2d_ptr = 0
endif
!! f_side.to_c_trans[complex, 3, PTR]
if (associated(F%complex_dp_3d_ptr)) then
  n1_complex_dp_3d_ptr = size(F%complex_dp_3d_ptr, 1)
  n2_complex_dp_3d_ptr = size(F%complex_dp_3d_ptr, 2)
  n3_complex_dp_3d_ptr = size(F%complex_dp_3d_ptr, 3)
else
  n1_complex_dp_3d_ptr = 0; n2_complex_dp_3d_ptr = 0; n3_complex_dp_3d_ptr = 0
endif
!! f_side.to_c_trans[complex, 1, ALLOC]
n1_complex_dp_1d_alloc = 0
if (allocated(F%complex_dp_1d_alloc)) then
  n1_complex_dp_1d_alloc = size(F%complex_dp_1d_alloc, 1)
endif
!! f_side.to_c_trans[complex, 2, ALLOC]
if (allocated(F%complex_dp_2d_alloc)) then
  n1_complex_dp_2d_alloc = size(F%complex_dp_2d_alloc, 1)
  n2_complex_dp_2d_alloc = size(F%complex_dp_2d_alloc, 2)
else
  n1_complex_dp_2d_alloc = 0; n2_complex_dp_2d_alloc = 0
endif
!! f_side.to_c_trans[complex, 3, ALLOC]
if (allocated(F%complex_dp_3d_alloc)) then
  n1_complex_dp_3d_alloc = size(F%complex_dp_3d_alloc, 1)
  n2_complex_dp_3d_alloc = size(F%complex_dp_3d_alloc, 2)
  n3_complex_dp_3d_alloc = size(F%complex_dp_3d_alloc, 3)
else
  n1_complex_dp_3d_alloc = 0; n2_complex_dp_3d_alloc = 0; n3_complex_dp_3d_alloc = 0
endif
!! f_side.to_c_trans[integer, 0, PTR]
n_int_0d_ptr = 0
if (associated(F%int_0d_ptr)) n_int_0d_ptr = 1
!! f_side.to_c_trans[integer, 1, PTR]
n1_int_1d_ptr = 0
if (associated(F%int_1d_ptr)) then
  n1_int_1d_ptr = size(F%int_1d_ptr, 1)
endif
!! f_side.to_c_trans[integer, 2, PTR]
if (associated(F%int_2d_ptr)) then
  n1_int_2d_ptr = size(F%int_2d_ptr, 1)
  n2_int_2d_ptr = size(F%int_2d_ptr, 2)
else
  n1_int_2d_ptr = 0; n2_int_2d_ptr = 0
endif
!! f_side.to_c_trans[integer, 3, PTR]
if (associated(F%int_3d_ptr)) then
  n1_int_3d_ptr = size(F%int_3d_ptr, 1)
  n2_int_3d_ptr = size(F%int_3d_ptr, 2)
  n3_int_3d_ptr = size(F%int_3d_ptr, 3)
else
  n1_int_3d_ptr = 0; n2_int_3d_ptr = 0; n3_int_3d_ptr = 0
endif
!! f_side.to_c_trans[integer, 1, ALLOC]
n1_int_1d_alloc = 0
if (allocated(F%int_1d_alloc)) then
  n1_int_1d_alloc = size(F%int_1d_alloc, 1)
endif
!! f_side.to_c_trans[integer, 2, ALLOC]
if (allocated(F%int_2d_alloc)) then
  n1_int_2d_alloc = size(F%int_2d_alloc, 1)
  n2_int_2d_alloc = size(F%int_2d_alloc, 2)
else
  n1_int_2d_alloc = 0; n2_int_2d_alloc = 0
endif
!! f_side.to_c_trans[integer, 3, ALLOC]
if (allocated(F%int_3d_alloc)) then
  n1_int_3d_alloc = size(F%int_3d_alloc, 1)
  n2_int_3d_alloc = size(F%int_3d_alloc, 2)
  n3_int_3d_alloc = size(F%int_3d_alloc, 3)
else
  n1_int_3d_alloc = 0; n2_int_3d_alloc = 0; n3_int_3d_alloc = 0
endif
!! f_side.to_c_trans[integer8, 0, PTR]
n_int8_0d_ptr = 0
if (associated(F%int8_0d_ptr)) n_int8_0d_ptr = 1
!! f_side.to_c_trans[integer8, 1, PTR]
n1_int8_1d_ptr = 0
if (associated(F%int8_1d_ptr)) then
  n1_int8_1d_ptr = size(F%int8_1d_ptr, 1)
endif
!! f_side.to_c_trans[integer8, 2, PTR]
if (associated(F%int8_2d_ptr)) then
  n1_int8_2d_ptr = size(F%int8_2d_ptr, 1)
  n2_int8_2d_ptr = size(F%int8_2d_ptr, 2)
else
  n1_int8_2d_ptr = 0; n2_int8_2d_ptr = 0
endif
!! f_side.to_c_trans[integer8, 3, PTR]
if (associated(F%int8_3d_ptr)) then
  n1_int8_3d_ptr = size(F%int8_3d_ptr, 1)
  n2_int8_3d_ptr = size(F%int8_3d_ptr, 2)
  n3_int8_3d_ptr = size(F%int8_3d_ptr, 3)
else
  n1_int8_3d_ptr = 0; n2_int8_3d_ptr = 0; n3_int8_3d_ptr = 0
endif
!! f_side.to_c_trans[integer8, 1, ALLOC]
n1_int8_1d_alloc = 0
if (allocated(F%int8_1d_alloc)) then
  n1_int8_1d_alloc = size(F%int8_1d_alloc, 1)
endif
!! f_side.to_c_trans[integer8, 2, ALLOC]
if (allocated(F%int8_2d_alloc)) then
  n1_int8_2d_alloc = size(F%int8_2d_alloc, 1)
  n2_int8_2d_alloc = size(F%int8_2d_alloc, 2)
else
  n1_int8_2d_alloc = 0; n2_int8_2d_alloc = 0
endif
!! f_side.to_c_trans[integer8, 3, ALLOC]
if (allocated(F%int8_3d_alloc)) then
  n1_int8_3d_alloc = size(F%int8_3d_alloc, 1)
  n2_int8_3d_alloc = size(F%int8_3d_alloc, 2)
  n3_int8_3d_alloc = size(F%int8_3d_alloc, 3)
else
  n1_int8_3d_alloc = 0; n2_int8_3d_alloc = 0; n3_int8_3d_alloc = 0
endif
!! f_side.to_c_trans[logical, 0, PTR]
n_logical_0d_ptr = 0
if (associated(F%logical_0d_ptr)) n_logical_0d_ptr = 1
!! f_side.to_c_trans[type, 1, NOT]
do jd1 = 1, size(F%type_1d,1); lb1 = lbound(F%type_1d,1) - 1
  z_type_1d(jd1) = c_loc(F%type_1d(jd1+lb1))
enddo
!! f_side.to_c_trans[type, 2, NOT]
do jd1 = 1, size(F%type_2d,1); lb1 = lbound(F%type_2d,1) - 1
do jd2 = 1, size(F%type_2d,2); lb2 = lbound(F%type_2d,2) - 1
  z_type_2d(4*(jd1-1) + jd2) = c_loc(F%type_2d(jd1+lb1,jd2+lb2))
enddo; enddo
!! f_side.to_c_trans[type, 3, NOT]
do jd1 = 1, size(F%type_3d,1); lb1 = lbound(F%type_3d,1) - 1
do jd2 = 1, size(F%type_3d,2); lb2 = lbound(F%type_3d,2) - 1
do jd3 = 1, size(F%type_3d,3); lb3 = lbound(F%type_3d,3) - 1
  z_type_3d(5*4*(jd1-1) + 5*(jd2-1) + jd3) = c_loc(F%type_3d(jd1+lb1,jd2+lb2,jd3+lb3))
enddo; enddo; enddo
!! f_side.to_c_trans[type, 0, PTR]
n_type_0d_ptr = 0
if (associated(F%type_0d_ptr)) n_type_0d_ptr = 1
!! f_side.to_c_trans[type, 1, PTR]
 n1_type_1d_ptr = 0
if (associated(F%type_1d_ptr)) then
  n1_type_1d_ptr = size(F%type_1d_ptr); lb1 = lbound(F%type_1d_ptr, 1) - 1
  allocate (z_type_1d_ptr(n1_type_1d_ptr))
  do jd1 = 1, n1_type_1d_ptr
    z_type_1d_ptr(jd1) = c_loc(F%type_1d_ptr(jd1+lb1))
  enddo
endif
!! f_side.to_c_trans[type, 2, PTR]
if (associated(F%type_2d_ptr)) then
  n1_type_2d_ptr = size(F%type_2d_ptr, 1); lb1 = lbound(F%type_2d_ptr, 1) - 1
  n2_type_2d_ptr = size(F%type_2d_ptr, 2); lb2 = lbound(F%type_2d_ptr, 2) - 1
  allocate (z_type_2d_ptr(n1_type_2d_ptr * n2_type_2d_ptr))
  do jd1 = 1, n1_type_2d_ptr; do jd2 = 1, n2_type_2d_ptr
    z_type_2d_ptr(n2_type_2d_ptr*(jd1-1) + jd2) = c_loc(F%type_2d_ptr(jd1+lb1, jd2+lb2))
  enddo;  enddo
else
  n1_type_2d_ptr = 0; n2_type_2d_ptr = 0
endif
!! f_side.to_c_trans[type, 3, PTR]
if (associated(F%type_3d_ptr)) then
  n1_type_3d_ptr = size(F%type_3d_ptr, 1); lb1 = lbound(F%type_3d_ptr, 1) - 1
  n2_type_3d_ptr = size(F%type_3d_ptr, 2); lb2 = lbound(F%type_3d_ptr, 2) - 1
  n3_type_3d_ptr = size(F%type_3d_ptr, 3); lb3 = lbound(F%type_3d_ptr, 3) - 1
  allocate (z_type_3d_ptr(n1_type_3d_ptr * n2_type_3d_ptr * n3_type_3d_ptr))
  do jd1 = 1, n1_type_3d_ptr; do jd2 = 1, n2_type_3d_ptr; do jd3 = 1, n3_type_3d_ptr
    z_type_3d_ptr(n3_type_3d_ptr*n2_type_3d_ptr*(jd1-1) + n3_type_3d_ptr*(jd2-1) + jd3) = c_loc(F%type_3d_ptr(jd1+lb1, jd2+lb2, jd3+lb3))
  enddo;  enddo; enddo
else
  n1_type_3d_ptr = 0; n2_type_3d_ptr = 0; n3_type_3d_ptr = 0
endif
!! f_side.to_c_trans[type, 1, ALLOC]
 n1_type_1d_alloc = 0
if (allocated(F%type_1d_alloc)) then
  n1_type_1d_alloc = size(F%type_1d_alloc); lb1 = lbound(F%type_1d_alloc, 1) - 1
  allocate (z_type_1d_alloc(n1_type_1d_alloc))
  do jd1 = 1, n1_type_1d_alloc
    z_type_1d_alloc(jd1) = c_loc(F%type_1d_alloc(jd1+lb1))
  enddo
endif
!! f_side.to_c_trans[type, 2, ALLOC]
if (allocated(F%type_2d_alloc)) then
  n1_type_2d_alloc = size(F%type_2d_alloc, 1); lb1 = lbound(F%type_2d_alloc, 1) - 1
  n2_type_2d_alloc = size(F%type_2d_alloc, 2); lb2 = lbound(F%type_2d_alloc, 2) - 1
  allocate (z_type_2d_alloc(n1_type_2d_alloc * n2_type_2d_alloc))
  do jd1 = 1, n1_type_2d_alloc; do jd2 = 1, n2_type_2d_alloc
    z_type_2d_alloc(n2_type_2d_alloc*(jd1-1) + jd2) = c_loc(F%type_2d_alloc(jd1+lb1, jd2+lb2))
  enddo;  enddo
else
  n1_type_2d_alloc = 0; n2_type_2d_alloc = 0
endif
!! f_side.to_c_trans[type, 3, ALLOC]
if (allocated(F%type_3d_alloc)) then
  n1_type_3d_alloc = size(F%type_3d_alloc, 1); lb1 = lbound(F%type_3d_alloc, 1) - 1
  n2_type_3d_alloc = size(F%type_3d_alloc, 2); lb2 = lbound(F%type_3d_alloc, 2) - 1
  n3_type_3d_alloc = size(F%type_3d_alloc, 3); lb3 = lbound(F%type_3d_alloc, 3) - 1
  allocate (z_type_3d_alloc(n1_type_3d_alloc * n2_type_3d_alloc * n3_type_3d_alloc))
  do jd1 = 1, n1_type_3d_alloc; do jd2 = 1, n2_type_3d_alloc; do jd3 = 1, n3_type_3d_alloc
    z_type_3d_alloc(n3_type_3d_alloc*n2_type_3d_alloc*(jd1-1) + n3_type_3d_alloc*(jd2-1) + jd3) = c_loc(F%type_3d_alloc(jd1+lb1, jd2+lb2, jd3+lb3))
  enddo;  enddo; enddo
else
  n1_type_3d_alloc = 0; n2_type_3d_alloc = 0; n3_type_3d_alloc = 0
endif

!! f_side.to_c2_call
call all_encompassing_to_c2 (C, F%real_rp_0d, fvec2vec(F%real_rp_1d, 3), mat2vec(F%real_rp_2d, &
    3*4), tensor2vec(F%real_rp_3d, 3*4*5), F%real_rp_0d_ptr, n_real_rp_0d_ptr, &
    fvec2vec(F%real_rp_1d_ptr, n1_real_rp_1d_ptr), n1_real_rp_1d_ptr, mat2vec(F%real_rp_2d_ptr, &
    n1_real_rp_2d_ptr*n2_real_rp_2d_ptr), n1_real_rp_2d_ptr, n2_real_rp_2d_ptr, &
    tensor2vec(F%real_rp_3d_ptr, n1_real_rp_3d_ptr*n2_real_rp_3d_ptr*n3_real_rp_3d_ptr), &
    n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr, fvec2vec(F%real_rp_1d_alloc, &
    n1_real_rp_1d_alloc), n1_real_rp_1d_alloc, mat2vec(F%real_rp_2d_alloc, &
    n1_real_rp_2d_alloc*n2_real_rp_2d_alloc), n1_real_rp_2d_alloc, n2_real_rp_2d_alloc, &
    tensor2vec(F%real_rp_3d_alloc, &
    n1_real_rp_3d_alloc*n2_real_rp_3d_alloc*n3_real_rp_3d_alloc), n1_real_rp_3d_alloc, &
    n2_real_rp_3d_alloc, n3_real_rp_3d_alloc, F%real_dp_0d, fvec2vec(F%real_dp_1d, 3), &
    mat2vec(F%real_dp_2d, 3*4), tensor2vec(F%real_dp_3d, 3*4*5), F%real_dp_0d_ptr, &
    n_real_dp_0d_ptr, fvec2vec(F%real_dp_1d_ptr, n1_real_dp_1d_ptr), n1_real_dp_1d_ptr, &
    mat2vec(F%real_dp_2d_ptr, n1_real_dp_2d_ptr*n2_real_dp_2d_ptr), n1_real_dp_2d_ptr, &
    n2_real_dp_2d_ptr, tensor2vec(F%real_dp_3d_ptr, &
    n1_real_dp_3d_ptr*n2_real_dp_3d_ptr*n3_real_dp_3d_ptr), n1_real_dp_3d_ptr, &
    n2_real_dp_3d_ptr, n3_real_dp_3d_ptr, fvec2vec(F%real_dp_1d_alloc, n1_real_dp_1d_alloc), &
    n1_real_dp_1d_alloc, mat2vec(F%real_dp_2d_alloc, n1_real_dp_2d_alloc*n2_real_dp_2d_alloc), &
    n1_real_dp_2d_alloc, n2_real_dp_2d_alloc, tensor2vec(F%real_dp_3d_alloc, &
    n1_real_dp_3d_alloc*n2_real_dp_3d_alloc*n3_real_dp_3d_alloc), n1_real_dp_3d_alloc, &
    n2_real_dp_3d_alloc, n3_real_dp_3d_alloc, F%complex_dp_0d, fvec2vec(F%complex_dp_1d, 3), &
    mat2vec(F%complex_dp_2d, 3*4), tensor2vec(F%complex_dp_3d, 3*4*5), F%complex_dp_0d_ptr, &
    n_complex_dp_0d_ptr, fvec2vec(F%complex_dp_1d_ptr, n1_complex_dp_1d_ptr), &
    n1_complex_dp_1d_ptr, mat2vec(F%complex_dp_2d_ptr, &
    n1_complex_dp_2d_ptr*n2_complex_dp_2d_ptr), n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr, &
    tensor2vec(F%complex_dp_3d_ptr, &
    n1_complex_dp_3d_ptr*n2_complex_dp_3d_ptr*n3_complex_dp_3d_ptr), n1_complex_dp_3d_ptr, &
    n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr, fvec2vec(F%complex_dp_1d_alloc, &
    n1_complex_dp_1d_alloc), n1_complex_dp_1d_alloc, mat2vec(F%complex_dp_2d_alloc, &
    n1_complex_dp_2d_alloc*n2_complex_dp_2d_alloc), n1_complex_dp_2d_alloc, &
    n2_complex_dp_2d_alloc, tensor2vec(F%complex_dp_3d_alloc, &
    n1_complex_dp_3d_alloc*n2_complex_dp_3d_alloc*n3_complex_dp_3d_alloc), &
    n1_complex_dp_3d_alloc, n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc, F%int_0d, &
    fvec2vec(F%int_1d, 3), mat2vec(F%int_2d, 3*4), tensor2vec(F%int_3d, 3*4*5), F%int_0d_ptr, &
    n_int_0d_ptr, fvec2vec(F%int_1d_ptr, n1_int_1d_ptr), n1_int_1d_ptr, mat2vec(F%int_2d_ptr, &
    n1_int_2d_ptr*n2_int_2d_ptr), n1_int_2d_ptr, n2_int_2d_ptr, tensor2vec(F%int_3d_ptr, &
    n1_int_3d_ptr*n2_int_3d_ptr*n3_int_3d_ptr), n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr, &
    fvec2vec(F%int_1d_alloc, n1_int_1d_alloc), n1_int_1d_alloc, mat2vec(F%int_2d_alloc, &
    n1_int_2d_alloc*n2_int_2d_alloc), n1_int_2d_alloc, n2_int_2d_alloc, &
    tensor2vec(F%int_3d_alloc, n1_int_3d_alloc*n2_int_3d_alloc*n3_int_3d_alloc), &
    n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc, F%int8_0d, fvec2vec(F%int8_1d, 3), &
    mat2vec(F%int8_2d, 3*4), tensor2vec(F%int8_3d, 3*4*5), F%int8_0d_ptr, n_int8_0d_ptr, &
    fvec2vec(F%int8_1d_ptr, n1_int8_1d_ptr), n1_int8_1d_ptr, mat2vec(F%int8_2d_ptr, &
    n1_int8_2d_ptr*n2_int8_2d_ptr), n1_int8_2d_ptr, n2_int8_2d_ptr, tensor2vec(F%int8_3d_ptr, &
    n1_int8_3d_ptr*n2_int8_3d_ptr*n3_int8_3d_ptr), n1_int8_3d_ptr, n2_int8_3d_ptr, &
    n3_int8_3d_ptr, fvec2vec(F%int8_1d_alloc, n1_int8_1d_alloc), n1_int8_1d_alloc, &
    mat2vec(F%int8_2d_alloc, n1_int8_2d_alloc*n2_int8_2d_alloc), n1_int8_2d_alloc, &
    n2_int8_2d_alloc, tensor2vec(F%int8_3d_alloc, &
    n1_int8_3d_alloc*n2_int8_3d_alloc*n3_int8_3d_alloc), n1_int8_3d_alloc, n2_int8_3d_alloc, &
    n3_int8_3d_alloc, c_logic(F%logical_0d), fvec2vec(F%logical_1d, 3), mat2vec(F%logical_2d, &
    3*4), tensor2vec(F%logical_3d, 3*4*5), fscalar2scalar(F%logical_0d_ptr, n_logical_0d_ptr), &
    n_logical_0d_ptr, c_loc(F%type_0d), z_type_1d, z_type_2d, z_type_3d, c_loc(F%type_0d_ptr), &
    n_type_0d_ptr, z_type_1d_ptr, n1_type_1d_ptr, z_type_2d_ptr, n1_type_2d_ptr, &
    n2_type_2d_ptr, z_type_3d_ptr, n1_type_3d_ptr, n2_type_3d_ptr, n3_type_3d_ptr, &
    z_type_1d_alloc, n1_type_1d_alloc, z_type_2d_alloc, n1_type_2d_alloc, n2_type_2d_alloc, &
    z_type_3d_alloc, n1_type_3d_alloc, n2_type_3d_alloc, n3_type_3d_alloc)

end subroutine all_encompassing_to_c

!--------------------------------------------------------------------------
!--------------------------------------------------------------------------
!+
! Subroutine all_encompassing_to_f2 (Fp, ...etc...) bind(c)
!
! Routine used in converting a C++ CPP_all_encompassing structure to a Bmad all_encompassing_struct structure.
! This routine is called by all_encompassing_to_c and is not meant to be called directly.
!
! Input:
!   ...etc... -- Components of the structure. See the all_encompassing_to_f2 code for more details.
!
! Output:
!   Fp -- type(c_ptr), value :: Bmad all_encompassing_struct structure.
!-

!! f_side.to_c2_f2_sub_arg
subroutine all_encompassing_to_f2 (Fp, z_real_rp_0d, z_real_rp_1d, z_real_rp_2d, z_real_rp_3d, &
    z_real_rp_0d_ptr, n_real_rp_0d_ptr, z_real_rp_1d_ptr, n1_real_rp_1d_ptr, z_real_rp_2d_ptr, &
    n1_real_rp_2d_ptr, n2_real_rp_2d_ptr, z_real_rp_3d_ptr, n1_real_rp_3d_ptr, &
    n2_real_rp_3d_ptr, n3_real_rp_3d_ptr, z_real_rp_1d_alloc, n1_real_rp_1d_alloc, &
    z_real_rp_2d_alloc, n1_real_rp_2d_alloc, n2_real_rp_2d_alloc, z_real_rp_3d_alloc, &
    n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc, z_real_dp_0d, z_real_dp_1d, &
    z_real_dp_2d, z_real_dp_3d, z_real_dp_0d_ptr, n_real_dp_0d_ptr, z_real_dp_1d_ptr, &
    n1_real_dp_1d_ptr, z_real_dp_2d_ptr, n1_real_dp_2d_ptr, n2_real_dp_2d_ptr, &
    z_real_dp_3d_ptr, n1_real_dp_3d_ptr, n2_real_dp_3d_ptr, n3_real_dp_3d_ptr, &
    z_real_dp_1d_alloc, n1_real_dp_1d_alloc, z_real_dp_2d_alloc, n1_real_dp_2d_alloc, &
    n2_real_dp_2d_alloc, z_real_dp_3d_alloc, n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, &
    n3_real_dp_3d_alloc, z_complex_dp_0d, z_complex_dp_1d, z_complex_dp_2d, z_complex_dp_3d, &
    z_complex_dp_0d_ptr, n_complex_dp_0d_ptr, z_complex_dp_1d_ptr, n1_complex_dp_1d_ptr, &
    z_complex_dp_2d_ptr, n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr, z_complex_dp_3d_ptr, &
    n1_complex_dp_3d_ptr, n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr, z_complex_dp_1d_alloc, &
    n1_complex_dp_1d_alloc, z_complex_dp_2d_alloc, n1_complex_dp_2d_alloc, &
    n2_complex_dp_2d_alloc, z_complex_dp_3d_alloc, n1_complex_dp_3d_alloc, &
    n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc, z_int_0d, z_int_1d, z_int_2d, z_int_3d, &
    z_int_0d_ptr, n_int_0d_ptr, z_int_1d_ptr, n1_int_1d_ptr, z_int_2d_ptr, n1_int_2d_ptr, &
    n2_int_2d_ptr, z_int_3d_ptr, n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr, z_int_1d_alloc, &
    n1_int_1d_alloc, z_int_2d_alloc, n1_int_2d_alloc, n2_int_2d_alloc, z_int_3d_alloc, &
    n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc, z_int8_0d, z_int8_1d, z_int8_2d, &
    z_int8_3d, z_int8_0d_ptr, n_int8_0d_ptr, z_int8_1d_ptr, n1_int8_1d_ptr, z_int8_2d_ptr, &
    n1_int8_2d_ptr, n2_int8_2d_ptr, z_int8_3d_ptr, n1_int8_3d_ptr, n2_int8_3d_ptr, &
    n3_int8_3d_ptr, z_int8_1d_alloc, n1_int8_1d_alloc, z_int8_2d_alloc, n1_int8_2d_alloc, &
    n2_int8_2d_alloc, z_int8_3d_alloc, n1_int8_3d_alloc, n2_int8_3d_alloc, n3_int8_3d_alloc, &
    z_logical_0d, z_logical_1d, z_logical_2d, z_logical_3d, z_logical_0d_ptr, n_logical_0d_ptr, &
    z_type_0d, z_type_1d, z_type_2d, z_type_3d, z_type_0d_ptr, n_type_0d_ptr, z_type_1d_ptr, &
    n1_type_1d_ptr, z_type_2d_ptr, n1_type_2d_ptr, n2_type_2d_ptr, z_type_3d_ptr, &
    n1_type_3d_ptr, n2_type_3d_ptr, n3_type_3d_ptr, z_type_1d_alloc, n1_type_1d_alloc, &
    z_type_2d_alloc, n1_type_2d_alloc, n2_type_2d_alloc, z_type_3d_alloc, n1_type_3d_alloc, &
    n2_type_3d_alloc, n3_type_3d_alloc) bind(c)


implicit none

type(c_ptr), value :: Fp
type(all_encompassing_struct), pointer :: F
integer jd, jd1, jd2, jd3, lb1, lb2, lb3
!! f_side.to_f2_var && f_side.to_f2_type :: f_side.to_f2_name
real(c_double) :: z_real_rp_0d, z_real_rp_1d(*), z_real_rp_2d(*), z_real_rp_3d(*), z_real_dp_0d, z_real_dp_1d(*), z_real_dp_2d(*)
real(c_double) :: z_real_dp_3d(*)
type(c_ptr), value :: z_real_rp_0d_ptr, z_real_rp_1d_ptr, z_real_rp_2d_ptr, z_real_rp_3d_ptr, z_real_rp_1d_alloc, z_real_rp_2d_alloc, z_real_rp_3d_alloc
type(c_ptr), value :: z_real_dp_0d_ptr, z_real_dp_1d_ptr, z_real_dp_2d_ptr, z_real_dp_3d_ptr, z_real_dp_1d_alloc, z_real_dp_2d_alloc, z_real_dp_3d_alloc
type(c_ptr), value :: z_complex_dp_0d_ptr, z_complex_dp_1d_ptr, z_complex_dp_2d_ptr, z_complex_dp_3d_ptr, z_complex_dp_1d_alloc, z_complex_dp_2d_alloc, z_complex_dp_3d_alloc
type(c_ptr), value :: z_int_0d_ptr, z_int_1d_ptr, z_int_2d_ptr, z_int_3d_ptr, z_int_1d_alloc, z_int_2d_alloc, z_int_3d_alloc
type(c_ptr), value :: z_int8_0d_ptr, z_int8_1d_ptr, z_int8_2d_ptr, z_int8_3d_ptr, z_int8_1d_alloc, z_int8_2d_alloc, z_int8_3d_alloc
type(c_ptr), value :: z_logical_0d_ptr, z_type_0d, z_type_0d_ptr
real(c_double), pointer :: f_real_rp_0d_ptr, f_real_rp_1d_ptr(:), f_real_rp_2d_ptr(:), f_real_rp_3d_ptr(:), f_real_rp_1d_alloc(:), f_real_rp_2d_alloc(:), f_real_rp_3d_alloc(:)
real(c_double), pointer :: f_real_dp_0d_ptr, f_real_dp_1d_ptr(:), f_real_dp_2d_ptr(:), f_real_dp_3d_ptr(:), f_real_dp_1d_alloc(:), f_real_dp_2d_alloc(:), f_real_dp_3d_alloc(:)
integer(c_int), value :: n_real_rp_0d_ptr, n1_real_rp_1d_ptr, n1_real_rp_2d_ptr, n2_real_rp_2d_ptr, n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr
integer(c_int), value :: n1_real_rp_1d_alloc, n1_real_rp_2d_alloc, n2_real_rp_2d_alloc, n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc, n_real_dp_0d_ptr
integer(c_int), value :: n1_real_dp_1d_ptr, n1_real_dp_2d_ptr, n2_real_dp_2d_ptr, n1_real_dp_3d_ptr, n2_real_dp_3d_ptr, n3_real_dp_3d_ptr, n1_real_dp_1d_alloc
integer(c_int), value :: n1_real_dp_2d_alloc, n2_real_dp_2d_alloc, n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, n3_real_dp_3d_alloc, n_complex_dp_0d_ptr, n1_complex_dp_1d_ptr
integer(c_int), value :: n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr, n1_complex_dp_3d_ptr, n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr, n1_complex_dp_1d_alloc, n1_complex_dp_2d_alloc
integer(c_int), value :: n2_complex_dp_2d_alloc, n1_complex_dp_3d_alloc, n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc, n_int_0d_ptr, n1_int_1d_ptr, n1_int_2d_ptr
integer(c_int), value :: n2_int_2d_ptr, n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr, n1_int_1d_alloc, n1_int_2d_alloc, n2_int_2d_alloc
integer(c_int), value :: n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc, n_int8_0d_ptr, n1_int8_1d_ptr, n1_int8_2d_ptr, n2_int8_2d_ptr
integer(c_int), value :: n1_int8_3d_ptr, n2_int8_3d_ptr, n3_int8_3d_ptr, n1_int8_1d_alloc, n1_int8_2d_alloc, n2_int8_2d_alloc, n1_int8_3d_alloc
integer(c_int), value :: n2_int8_3d_alloc, n3_int8_3d_alloc, n_logical_0d_ptr, n_type_0d_ptr, n1_type_1d_ptr, n1_type_2d_ptr, n2_type_2d_ptr
integer(c_int), value :: n1_type_3d_ptr, n2_type_3d_ptr, n3_type_3d_ptr, n1_type_1d_alloc, n1_type_2d_alloc, n2_type_2d_alloc, n1_type_3d_alloc
integer(c_int), value :: n2_type_3d_alloc, n3_type_3d_alloc
complex(c_double_complex) :: z_complex_dp_0d, z_complex_dp_1d(*), z_complex_dp_2d(*), z_complex_dp_3d(*)
complex(c_double_complex), pointer :: f_complex_dp_0d_ptr, f_complex_dp_1d_ptr(:), f_complex_dp_2d_ptr(:), f_complex_dp_3d_ptr(:), f_complex_dp_1d_alloc(:), f_complex_dp_2d_alloc(:), f_complex_dp_3d_alloc(:)
integer(c_int) :: z_int_0d, z_int_1d(*), z_int_2d(*), z_int_3d(*)
integer(c_int), pointer :: f_int_0d_ptr, f_int_1d_ptr(:), f_int_2d_ptr(:), f_int_3d_ptr(:), f_int_1d_alloc(:), f_int_2d_alloc(:), f_int_3d_alloc(:)
integer(c_long) :: z_int8_0d, z_int8_1d(*), z_int8_2d(*), z_int8_3d(*)
integer(c_long), pointer :: f_int8_0d_ptr, f_int8_1d_ptr(:), f_int8_2d_ptr(:), f_int8_3d_ptr(:), f_int8_1d_alloc(:), f_int8_2d_alloc(:), f_int8_3d_alloc(:)
logical(c_bool) :: z_logical_0d, z_logical_1d(*), z_logical_2d(*), z_logical_3d(*)
logical(c_bool), pointer :: f_logical_0d_ptr
type(c_ptr) :: z_type_1d(*), z_type_2d(*), z_type_3d(*), z_type_1d_ptr(*), z_type_2d_ptr(*), z_type_3d_ptr(*), z_type_1d_alloc(*)
type(c_ptr) :: z_type_2d_alloc(*), z_type_3d_alloc(*)
type(wake_lr_struct), pointer :: f_type_0d_ptr

call c_f_pointer (Fp, F)

!! f_side.to_f2_trans[real, 0, NOT]
F%real_rp_0d = z_real_rp_0d
!! f_side.to_f2_trans[real, 1, NOT]
F%real_rp_1d = z_real_rp_1d(1:3)
!! f_side.to_f2_trans[real, 2, NOT]
call vec2mat(z_real_rp_2d, F%real_rp_2d)
!! f_side.to_f2_trans[real, 3, NOT]
call vec2tensor(z_real_rp_3d, F%real_rp_3d)
!! f_side.to_f2_trans[real, 0, PTR]
if (n_real_rp_0d_ptr == 0) then                                                                                  
  if (associated(F%real_rp_0d_ptr)) deallocate(F%real_rp_0d_ptr)                                                           
else                                                                                                   
  call c_f_pointer (z_real_rp_0d_ptr, f_real_rp_0d_ptr)                                                                    
  if (.not. associated(F%real_rp_0d_ptr)) allocate(F%real_rp_0d_ptr)                                                       
  F%real_rp_0d_ptr = f_real_rp_0d_ptr
endif                                                                                                  

!! f_side.to_f2_trans[real, 1, PTR]
if (associated(F%real_rp_1d_ptr)) then
  if (n1_real_rp_1d_ptr == 0 .or. any(shape(F%real_rp_1d_ptr) /= [n1_real_rp_1d_ptr])) deallocate(F%real_rp_1d_ptr)
  if (any(lbound(F%real_rp_1d_ptr) /= 1)) deallocate(F%real_rp_1d_ptr)
endif
if (n1_real_rp_1d_ptr /= 0) then
  call c_f_pointer (z_real_rp_1d_ptr, f_real_rp_1d_ptr, [n1_real_rp_1d_ptr])
  if (.not. associated(F%real_rp_1d_ptr)) allocate(F%real_rp_1d_ptr(n1_real_rp_1d_ptr))
  F%real_rp_1d_ptr = f_real_rp_1d_ptr(1:n1_real_rp_1d_ptr)
else
  if (associated(F%real_rp_1d_ptr)) deallocate(F%real_rp_1d_ptr)
endif

!! f_side.to_f2_trans[real, 2, PTR]
if (associated(F%real_rp_2d_ptr)) then
  if (n1_real_rp_2d_ptr == 0 .or. any(shape(F%real_rp_2d_ptr) /= [n1_real_rp_2d_ptr, n2_real_rp_2d_ptr])) deallocate(F%real_rp_2d_ptr)
  if (any(lbound(F%real_rp_2d_ptr) /= 1)) deallocate(F%real_rp_2d_ptr)
endif
if (n1_real_rp_2d_ptr /= 0) then
  call c_f_pointer (z_real_rp_2d_ptr, f_real_rp_2d_ptr, [n1_real_rp_2d_ptr*n2_real_rp_2d_ptr])
  if (.not. associated(F%real_rp_2d_ptr)) allocate(F%real_rp_2d_ptr(n1_real_rp_2d_ptr, n2_real_rp_2d_ptr))
  call vec2mat(f_real_rp_2d_ptr, F%real_rp_2d_ptr)
else
  if (associated(F%real_rp_2d_ptr)) deallocate(F%real_rp_2d_ptr)
endif

!! f_side.to_f2_trans[real, 3, PTR]
if (associated(F%real_rp_3d_ptr)) then
  if (n1_real_rp_3d_ptr == 0 .or. any(shape(F%real_rp_3d_ptr) /= [n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr])) deallocate(F%real_rp_3d_ptr)
  if (any(lbound(F%real_rp_3d_ptr) /= 1)) deallocate(F%real_rp_3d_ptr)
endif
if (n1_real_rp_3d_ptr /= 0) then
  call c_f_pointer (z_real_rp_3d_ptr, f_real_rp_3d_ptr, [n1_real_rp_3d_ptr*n2_real_rp_3d_ptr*n3_real_rp_3d_ptr])
  if (.not. associated(F%real_rp_3d_ptr)) allocate(F%real_rp_3d_ptr(n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr))
  call vec2tensor(f_real_rp_3d_ptr, F%real_rp_3d_ptr)
else
  if (associated(F%real_rp_3d_ptr)) deallocate(F%real_rp_3d_ptr)
endif

!! f_side.to_f2_trans[real, 1, ALLOC]
if (allocated(F%real_rp_1d_alloc)) then
  if (n1_real_rp_1d_alloc == 0 .or. any(shape(F%real_rp_1d_alloc) /= [n1_real_rp_1d_alloc])) deallocate(F%real_rp_1d_alloc)
  if (any(lbound(F%real_rp_1d_alloc) /= 1)) deallocate(F%real_rp_1d_alloc)
endif
if (n1_real_rp_1d_alloc /= 0) then
  call c_f_pointer (z_real_rp_1d_alloc, f_real_rp_1d_alloc, [n1_real_rp_1d_alloc])
  if (.not. allocated(F%real_rp_1d_alloc)) allocate(F%real_rp_1d_alloc(n1_real_rp_1d_alloc))
  F%real_rp_1d_alloc = f_real_rp_1d_alloc(1:n1_real_rp_1d_alloc)
else
  if (allocated(F%real_rp_1d_alloc)) deallocate(F%real_rp_1d_alloc)
endif

!! f_side.to_f2_trans[real, 2, ALLOC]
if (allocated(F%real_rp_2d_alloc)) then
  if (n1_real_rp_2d_alloc == 0 .or. any(shape(F%real_rp_2d_alloc) /= [n1_real_rp_2d_alloc, n2_real_rp_2d_alloc])) deallocate(F%real_rp_2d_alloc)
  if (any(lbound(F%real_rp_2d_alloc) /= 1)) deallocate(F%real_rp_2d_alloc)
endif
if (n1_real_rp_2d_alloc /= 0) then
  call c_f_pointer (z_real_rp_2d_alloc, f_real_rp_2d_alloc, [n1_real_rp_2d_alloc*n2_real_rp_2d_alloc])
  if (.not. allocated(F%real_rp_2d_alloc)) allocate(F%real_rp_2d_alloc(n1_real_rp_2d_alloc, n2_real_rp_2d_alloc))
  call vec2mat(f_real_rp_2d_alloc, F%real_rp_2d_alloc)
else
  if (allocated(F%real_rp_2d_alloc)) deallocate(F%real_rp_2d_alloc)
endif

!! f_side.to_f2_trans[real, 3, ALLOC]
if (allocated(F%real_rp_3d_alloc)) then
  if (n1_real_rp_3d_alloc == 0 .or. any(shape(F%real_rp_3d_alloc) /= [n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc])) deallocate(F%real_rp_3d_alloc)
  if (any(lbound(F%real_rp_3d_alloc) /= 1)) deallocate(F%real_rp_3d_alloc)
endif
if (n1_real_rp_3d_alloc /= 0) then
  call c_f_pointer (z_real_rp_3d_alloc, f_real_rp_3d_alloc, [n1_real_rp_3d_alloc*n2_real_rp_3d_alloc*n3_real_rp_3d_alloc])
  if (.not. allocated(F%real_rp_3d_alloc)) allocate(F%real_rp_3d_alloc(n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc))
  call vec2tensor(f_real_rp_3d_alloc, F%real_rp_3d_alloc)
else
  if (allocated(F%real_rp_3d_alloc)) deallocate(F%real_rp_3d_alloc)
endif

!! f_side.to_f2_trans[real, 0, NOT]
F%real_dp_0d = z_real_dp_0d
!! f_side.to_f2_trans[real, 1, NOT]
F%real_dp_1d = z_real_dp_1d(1:3)
!! f_side.to_f2_trans[real, 2, NOT]
call vec2mat(z_real_dp_2d, F%real_dp_2d)
!! f_side.to_f2_trans[real, 3, NOT]
call vec2tensor(z_real_dp_3d, F%real_dp_3d)
!! f_side.to_f2_trans[real, 0, PTR]
if (n_real_dp_0d_ptr == 0) then                                                                                  
  if (associated(F%real_dp_0d_ptr)) deallocate(F%real_dp_0d_ptr)                                                           
else                                                                                                   
  call c_f_pointer (z_real_dp_0d_ptr, f_real_dp_0d_ptr)                                                                    
  if (.not. associated(F%real_dp_0d_ptr)) allocate(F%real_dp_0d_ptr)                                                       
  F%real_dp_0d_ptr = f_real_dp_0d_ptr
endif                                                                                                  

!! f_side.to_f2_trans[real, 1, PTR]
if (associated(F%real_dp_1d_ptr)) then
  if (n1_real_dp_1d_ptr == 0 .or. any(shape(F%real_dp_1d_ptr) /= [n1_real_dp_1d_ptr])) deallocate(F%real_dp_1d_ptr)
  if (any(lbound(F%real_dp_1d_ptr) /= 1)) deallocate(F%real_dp_1d_ptr)
endif
if (n1_real_dp_1d_ptr /= 0) then
  call c_f_pointer (z_real_dp_1d_ptr, f_real_dp_1d_ptr, [n1_real_dp_1d_ptr])
  if (.not. associated(F%real_dp_1d_ptr)) allocate(F%real_dp_1d_ptr(n1_real_dp_1d_ptr))
  F%real_dp_1d_ptr = f_real_dp_1d_ptr(1:n1_real_dp_1d_ptr)
else
  if (associated(F%real_dp_1d_ptr)) deallocate(F%real_dp_1d_ptr)
endif

!! f_side.to_f2_trans[real, 2, PTR]
if (associated(F%real_dp_2d_ptr)) then
  if (n1_real_dp_2d_ptr == 0 .or. any(shape(F%real_dp_2d_ptr) /= [n1_real_dp_2d_ptr, n2_real_dp_2d_ptr])) deallocate(F%real_dp_2d_ptr)
  if (any(lbound(F%real_dp_2d_ptr) /= 1)) deallocate(F%real_dp_2d_ptr)
endif
if (n1_real_dp_2d_ptr /= 0) then
  call c_f_pointer (z_real_dp_2d_ptr, f_real_dp_2d_ptr, [n1_real_dp_2d_ptr*n2_real_dp_2d_ptr])
  if (.not. associated(F%real_dp_2d_ptr)) allocate(F%real_dp_2d_ptr(n1_real_dp_2d_ptr, n2_real_dp_2d_ptr))
  call vec2mat(f_real_dp_2d_ptr, F%real_dp_2d_ptr)
else
  if (associated(F%real_dp_2d_ptr)) deallocate(F%real_dp_2d_ptr)
endif

!! f_side.to_f2_trans[real, 3, PTR]
if (associated(F%real_dp_3d_ptr)) then
  if (n1_real_dp_3d_ptr == 0 .or. any(shape(F%real_dp_3d_ptr) /= [n1_real_dp_3d_ptr, n2_real_dp_3d_ptr, n3_real_dp_3d_ptr])) deallocate(F%real_dp_3d_ptr)
  if (any(lbound(F%real_dp_3d_ptr) /= 1)) deallocate(F%real_dp_3d_ptr)
endif
if (n1_real_dp_3d_ptr /= 0) then
  call c_f_pointer (z_real_dp_3d_ptr, f_real_dp_3d_ptr, [n1_real_dp_3d_ptr*n2_real_dp_3d_ptr*n3_real_dp_3d_ptr])
  if (.not. associated(F%real_dp_3d_ptr)) allocate(F%real_dp_3d_ptr(n1_real_dp_3d_ptr, n2_real_dp_3d_ptr, n3_real_dp_3d_ptr))
  call vec2tensor(f_real_dp_3d_ptr, F%real_dp_3d_ptr)
else
  if (associated(F%real_dp_3d_ptr)) deallocate(F%real_dp_3d_ptr)
endif

!! f_side.to_f2_trans[real, 1, ALLOC]
if (allocated(F%real_dp_1d_alloc)) then
  if (n1_real_dp_1d_alloc == 0 .or. any(shape(F%real_dp_1d_alloc) /= [n1_real_dp_1d_alloc])) deallocate(F%real_dp_1d_alloc)
  if (any(lbound(F%real_dp_1d_alloc) /= 1)) deallocate(F%real_dp_1d_alloc)
endif
if (n1_real_dp_1d_alloc /= 0) then
  call c_f_pointer (z_real_dp_1d_alloc, f_real_dp_1d_alloc, [n1_real_dp_1d_alloc])
  if (.not. allocated(F%real_dp_1d_alloc)) allocate(F%real_dp_1d_alloc(n1_real_dp_1d_alloc))
  F%real_dp_1d_alloc = f_real_dp_1d_alloc(1:n1_real_dp_1d_alloc)
else
  if (allocated(F%real_dp_1d_alloc)) deallocate(F%real_dp_1d_alloc)
endif

!! f_side.to_f2_trans[real, 2, ALLOC]
if (allocated(F%real_dp_2d_alloc)) then
  if (n1_real_dp_2d_alloc == 0 .or. any(shape(F%real_dp_2d_alloc) /= [n1_real_dp_2d_alloc, n2_real_dp_2d_alloc])) deallocate(F%real_dp_2d_alloc)
  if (any(lbound(F%real_dp_2d_alloc) /= 1)) deallocate(F%real_dp_2d_alloc)
endif
if (n1_real_dp_2d_alloc /= 0) then
  call c_f_pointer (z_real_dp_2d_alloc, f_real_dp_2d_alloc, [n1_real_dp_2d_alloc*n2_real_dp_2d_alloc])
  if (.not. allocated(F%real_dp_2d_alloc)) allocate(F%real_dp_2d_alloc(n1_real_dp_2d_alloc, n2_real_dp_2d_alloc))
  call vec2mat(f_real_dp_2d_alloc, F%real_dp_2d_alloc)
else
  if (allocated(F%real_dp_2d_alloc)) deallocate(F%real_dp_2d_alloc)
endif

!! f_side.to_f2_trans[real, 3, ALLOC]
if (allocated(F%real_dp_3d_alloc)) then
  if (n1_real_dp_3d_alloc == 0 .or. any(shape(F%real_dp_3d_alloc) /= [n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, n3_real_dp_3d_alloc])) deallocate(F%real_dp_3d_alloc)
  if (any(lbound(F%real_dp_3d_alloc) /= 1)) deallocate(F%real_dp_3d_alloc)
endif
if (n1_real_dp_3d_alloc /= 0) then
  call c_f_pointer (z_real_dp_3d_alloc, f_real_dp_3d_alloc, [n1_real_dp_3d_alloc*n2_real_dp_3d_alloc*n3_real_dp_3d_alloc])
  if (.not. allocated(F%real_dp_3d_alloc)) allocate(F%real_dp_3d_alloc(n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, n3_real_dp_3d_alloc))
  call vec2tensor(f_real_dp_3d_alloc, F%real_dp_3d_alloc)
else
  if (allocated(F%real_dp_3d_alloc)) deallocate(F%real_dp_3d_alloc)
endif

!! f_side.to_f2_trans[complex, 0, NOT]
F%complex_dp_0d = z_complex_dp_0d
!! f_side.to_f2_trans[complex, 1, NOT]
F%complex_dp_1d = z_complex_dp_1d(1:3)
!! f_side.to_f2_trans[complex, 2, NOT]
call vec2mat(z_complex_dp_2d, F%complex_dp_2d)
!! f_side.to_f2_trans[complex, 3, NOT]
call vec2tensor(z_complex_dp_3d, F%complex_dp_3d)
!! f_side.to_f2_trans[complex, 0, PTR]
if (n_complex_dp_0d_ptr == 0) then                                                                                  
  if (associated(F%complex_dp_0d_ptr)) deallocate(F%complex_dp_0d_ptr)                                                           
else                                                                                                   
  call c_f_pointer (z_complex_dp_0d_ptr, f_complex_dp_0d_ptr)                                                                    
  if (.not. associated(F%complex_dp_0d_ptr)) allocate(F%complex_dp_0d_ptr)                                                       
  F%complex_dp_0d_ptr = f_complex_dp_0d_ptr
endif                                                                                                  

!! f_side.to_f2_trans[complex, 1, PTR]
if (associated(F%complex_dp_1d_ptr)) then
  if (n1_complex_dp_1d_ptr == 0 .or. any(shape(F%complex_dp_1d_ptr) /= [n1_complex_dp_1d_ptr])) deallocate(F%complex_dp_1d_ptr)
  if (any(lbound(F%complex_dp_1d_ptr) /= 1)) deallocate(F%complex_dp_1d_ptr)
endif
if (n1_complex_dp_1d_ptr /= 0) then
  call c_f_pointer (z_complex_dp_1d_ptr, f_complex_dp_1d_ptr, [n1_complex_dp_1d_ptr])
  if (.not. associated(F%complex_dp_1d_ptr)) allocate(F%complex_dp_1d_ptr(n1_complex_dp_1d_ptr))
  F%complex_dp_1d_ptr = f_complex_dp_1d_ptr(1:n1_complex_dp_1d_ptr)
else
  if (associated(F%complex_dp_1d_ptr)) deallocate(F%complex_dp_1d_ptr)
endif

!! f_side.to_f2_trans[complex, 2, PTR]
if (associated(F%complex_dp_2d_ptr)) then
  if (n1_complex_dp_2d_ptr == 0 .or. any(shape(F%complex_dp_2d_ptr) /= [n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr])) deallocate(F%complex_dp_2d_ptr)
  if (any(lbound(F%complex_dp_2d_ptr) /= 1)) deallocate(F%complex_dp_2d_ptr)
endif
if (n1_complex_dp_2d_ptr /= 0) then
  call c_f_pointer (z_complex_dp_2d_ptr, f_complex_dp_2d_ptr, [n1_complex_dp_2d_ptr*n2_complex_dp_2d_ptr])
  if (.not. associated(F%complex_dp_2d_ptr)) allocate(F%complex_dp_2d_ptr(n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr))
  call vec2mat(f_complex_dp_2d_ptr, F%complex_dp_2d_ptr)
else
  if (associated(F%complex_dp_2d_ptr)) deallocate(F%complex_dp_2d_ptr)
endif

!! f_side.to_f2_trans[complex, 3, PTR]
if (associated(F%complex_dp_3d_ptr)) then
  if (n1_complex_dp_3d_ptr == 0 .or. any(shape(F%complex_dp_3d_ptr) /= [n1_complex_dp_3d_ptr, n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr])) deallocate(F%complex_dp_3d_ptr)
  if (any(lbound(F%complex_dp_3d_ptr) /= 1)) deallocate(F%complex_dp_3d_ptr)
endif
if (n1_complex_dp_3d_ptr /= 0) then
  call c_f_pointer (z_complex_dp_3d_ptr, f_complex_dp_3d_ptr, [n1_complex_dp_3d_ptr*n2_complex_dp_3d_ptr*n3_complex_dp_3d_ptr])
  if (.not. associated(F%complex_dp_3d_ptr)) allocate(F%complex_dp_3d_ptr(n1_complex_dp_3d_ptr, n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr))
  call vec2tensor(f_complex_dp_3d_ptr, F%complex_dp_3d_ptr)
else
  if (associated(F%complex_dp_3d_ptr)) deallocate(F%complex_dp_3d_ptr)
endif

!! f_side.to_f2_trans[complex, 1, ALLOC]
if (allocated(F%complex_dp_1d_alloc)) then
  if (n1_complex_dp_1d_alloc == 0 .or. any(shape(F%complex_dp_1d_alloc) /= [n1_complex_dp_1d_alloc])) deallocate(F%complex_dp_1d_alloc)
  if (any(lbound(F%complex_dp_1d_alloc) /= 1)) deallocate(F%complex_dp_1d_alloc)
endif
if (n1_complex_dp_1d_alloc /= 0) then
  call c_f_pointer (z_complex_dp_1d_alloc, f_complex_dp_1d_alloc, [n1_complex_dp_1d_alloc])
  if (.not. allocated(F%complex_dp_1d_alloc)) allocate(F%complex_dp_1d_alloc(n1_complex_dp_1d_alloc))
  F%complex_dp_1d_alloc = f_complex_dp_1d_alloc(1:n1_complex_dp_1d_alloc)
else
  if (allocated(F%complex_dp_1d_alloc)) deallocate(F%complex_dp_1d_alloc)
endif

!! f_side.to_f2_trans[complex, 2, ALLOC]
if (allocated(F%complex_dp_2d_alloc)) then
  if (n1_complex_dp_2d_alloc == 0 .or. any(shape(F%complex_dp_2d_alloc) /= [n1_complex_dp_2d_alloc, n2_complex_dp_2d_alloc])) deallocate(F%complex_dp_2d_alloc)
  if (any(lbound(F%complex_dp_2d_alloc) /= 1)) deallocate(F%complex_dp_2d_alloc)
endif
if (n1_complex_dp_2d_alloc /= 0) then
  call c_f_pointer (z_complex_dp_2d_alloc, f_complex_dp_2d_alloc, [n1_complex_dp_2d_alloc*n2_complex_dp_2d_alloc])
  if (.not. allocated(F%complex_dp_2d_alloc)) allocate(F%complex_dp_2d_alloc(n1_complex_dp_2d_alloc, n2_complex_dp_2d_alloc))
  call vec2mat(f_complex_dp_2d_alloc, F%complex_dp_2d_alloc)
else
  if (allocated(F%complex_dp_2d_alloc)) deallocate(F%complex_dp_2d_alloc)
endif

!! f_side.to_f2_trans[complex, 3, ALLOC]
if (allocated(F%complex_dp_3d_alloc)) then
  if (n1_complex_dp_3d_alloc == 0 .or. any(shape(F%complex_dp_3d_alloc) /= [n1_complex_dp_3d_alloc, n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc])) deallocate(F%complex_dp_3d_alloc)
  if (any(lbound(F%complex_dp_3d_alloc) /= 1)) deallocate(F%complex_dp_3d_alloc)
endif
if (n1_complex_dp_3d_alloc /= 0) then
  call c_f_pointer (z_complex_dp_3d_alloc, f_complex_dp_3d_alloc, [n1_complex_dp_3d_alloc*n2_complex_dp_3d_alloc*n3_complex_dp_3d_alloc])
  if (.not. allocated(F%complex_dp_3d_alloc)) allocate(F%complex_dp_3d_alloc(n1_complex_dp_3d_alloc, n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc))
  call vec2tensor(f_complex_dp_3d_alloc, F%complex_dp_3d_alloc)
else
  if (allocated(F%complex_dp_3d_alloc)) deallocate(F%complex_dp_3d_alloc)
endif

!! f_side.to_f2_trans[integer, 0, NOT]
F%int_0d = z_int_0d
!! f_side.to_f2_trans[integer, 1, NOT]
F%int_1d = z_int_1d(1:3)
!! f_side.to_f2_trans[integer, 2, NOT]
call vec2mat(z_int_2d, F%int_2d)
!! f_side.to_f2_trans[integer, 3, NOT]
call vec2tensor(z_int_3d, F%int_3d)
!! f_side.to_f2_trans[integer, 0, PTR]
if (n_int_0d_ptr == 0) then                                                                                  
  if (associated(F%int_0d_ptr)) deallocate(F%int_0d_ptr)                                                           
else                                                                                                   
  call c_f_pointer (z_int_0d_ptr, f_int_0d_ptr)                                                                    
  if (.not. associated(F%int_0d_ptr)) allocate(F%int_0d_ptr)                                                       
  F%int_0d_ptr = f_int_0d_ptr
endif                                                                                                  

!! f_side.to_f2_trans[integer, 1, PTR]
if (associated(F%int_1d_ptr)) then
  if (n1_int_1d_ptr == 0 .or. any(shape(F%int_1d_ptr) /= [n1_int_1d_ptr])) deallocate(F%int_1d_ptr)
  if (any(lbound(F%int_1d_ptr) /= 1)) deallocate(F%int_1d_ptr)
endif
if (n1_int_1d_ptr /= 0) then
  call c_f_pointer (z_int_1d_ptr, f_int_1d_ptr, [n1_int_1d_ptr])
  if (.not. associated(F%int_1d_ptr)) allocate(F%int_1d_ptr(n1_int_1d_ptr))
  F%int_1d_ptr = f_int_1d_ptr(1:n1_int_1d_ptr)
else
  if (associated(F%int_1d_ptr)) deallocate(F%int_1d_ptr)
endif

!! f_side.to_f2_trans[integer, 2, PTR]
if (associated(F%int_2d_ptr)) then
  if (n1_int_2d_ptr == 0 .or. any(shape(F%int_2d_ptr) /= [n1_int_2d_ptr, n2_int_2d_ptr])) deallocate(F%int_2d_ptr)
  if (any(lbound(F%int_2d_ptr) /= 1)) deallocate(F%int_2d_ptr)
endif
if (n1_int_2d_ptr /= 0) then
  call c_f_pointer (z_int_2d_ptr, f_int_2d_ptr, [n1_int_2d_ptr*n2_int_2d_ptr])
  if (.not. associated(F%int_2d_ptr)) allocate(F%int_2d_ptr(n1_int_2d_ptr, n2_int_2d_ptr))
  call vec2mat(f_int_2d_ptr, F%int_2d_ptr)
else
  if (associated(F%int_2d_ptr)) deallocate(F%int_2d_ptr)
endif

!! f_side.to_f2_trans[integer, 3, PTR]
if (associated(F%int_3d_ptr)) then
  if (n1_int_3d_ptr == 0 .or. any(shape(F%int_3d_ptr) /= [n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr])) deallocate(F%int_3d_ptr)
  if (any(lbound(F%int_3d_ptr) /= 1)) deallocate(F%int_3d_ptr)
endif
if (n1_int_3d_ptr /= 0) then
  call c_f_pointer (z_int_3d_ptr, f_int_3d_ptr, [n1_int_3d_ptr*n2_int_3d_ptr*n3_int_3d_ptr])
  if (.not. associated(F%int_3d_ptr)) allocate(F%int_3d_ptr(n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr))
  call vec2tensor(f_int_3d_ptr, F%int_3d_ptr)
else
  if (associated(F%int_3d_ptr)) deallocate(F%int_3d_ptr)
endif

!! f_side.to_f2_trans[integer, 1, ALLOC]
if (allocated(F%int_1d_alloc)) then
  if (n1_int_1d_alloc == 0 .or. any(shape(F%int_1d_alloc) /= [n1_int_1d_alloc])) deallocate(F%int_1d_alloc)
  if (any(lbound(F%int_1d_alloc) /= 1)) deallocate(F%int_1d_alloc)
endif
if (n1_int_1d_alloc /= 0) then
  call c_f_pointer (z_int_1d_alloc, f_int_1d_alloc, [n1_int_1d_alloc])
  if (.not. allocated(F%int_1d_alloc)) allocate(F%int_1d_alloc(n1_int_1d_alloc))
  F%int_1d_alloc = f_int_1d_alloc(1:n1_int_1d_alloc)
else
  if (allocated(F%int_1d_alloc)) deallocate(F%int_1d_alloc)
endif

!! f_side.to_f2_trans[integer, 2, ALLOC]
if (allocated(F%int_2d_alloc)) then
  if (n1_int_2d_alloc == 0 .or. any(shape(F%int_2d_alloc) /= [n1_int_2d_alloc, n2_int_2d_alloc])) deallocate(F%int_2d_alloc)
  if (any(lbound(F%int_2d_alloc) /= 1)) deallocate(F%int_2d_alloc)
endif
if (n1_int_2d_alloc /= 0) then
  call c_f_pointer (z_int_2d_alloc, f_int_2d_alloc, [n1_int_2d_alloc*n2_int_2d_alloc])
  if (.not. allocated(F%int_2d_alloc)) allocate(F%int_2d_alloc(n1_int_2d_alloc, n2_int_2d_alloc))
  call vec2mat(f_int_2d_alloc, F%int_2d_alloc)
else
  if (allocated(F%int_2d_alloc)) deallocate(F%int_2d_alloc)
endif

!! f_side.to_f2_trans[integer, 3, ALLOC]
if (allocated(F%int_3d_alloc)) then
  if (n1_int_3d_alloc == 0 .or. any(shape(F%int_3d_alloc) /= [n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc])) deallocate(F%int_3d_alloc)
  if (any(lbound(F%int_3d_alloc) /= 1)) deallocate(F%int_3d_alloc)
endif
if (n1_int_3d_alloc /= 0) then
  call c_f_pointer (z_int_3d_alloc, f_int_3d_alloc, [n1_int_3d_alloc*n2_int_3d_alloc*n3_int_3d_alloc])
  if (.not. allocated(F%int_3d_alloc)) allocate(F%int_3d_alloc(n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc))
  call vec2tensor(f_int_3d_alloc, F%int_3d_alloc)
else
  if (allocated(F%int_3d_alloc)) deallocate(F%int_3d_alloc)
endif

!! f_side.to_f2_trans[integer8, 0, NOT]
F%int8_0d = z_int8_0d
!! f_side.to_f2_trans[integer8, 1, NOT]
F%int8_1d = z_int8_1d(1:3)
!! f_side.to_f2_trans[integer8, 2, NOT]
call vec2mat(z_int8_2d, F%int8_2d)
!! f_side.to_f2_trans[integer8, 3, NOT]
call vec2tensor(z_int8_3d, F%int8_3d)
!! f_side.to_f2_trans[integer8, 0, PTR]
if (n_int8_0d_ptr == 0) then                                                                                  
  if (associated(F%int8_0d_ptr)) deallocate(F%int8_0d_ptr)                                                           
else                                                                                                   
  call c_f_pointer (z_int8_0d_ptr, f_int8_0d_ptr)                                                                    
  if (.not. associated(F%int8_0d_ptr)) allocate(F%int8_0d_ptr)                                                       
  F%int8_0d_ptr = f_int8_0d_ptr
endif                                                                                                  

!! f_side.to_f2_trans[integer8, 1, PTR]
if (associated(F%int8_1d_ptr)) then
  if (n1_int8_1d_ptr == 0 .or. any(shape(F%int8_1d_ptr) /= [n1_int8_1d_ptr])) deallocate(F%int8_1d_ptr)
  if (any(lbound(F%int8_1d_ptr) /= 1)) deallocate(F%int8_1d_ptr)
endif
if (n1_int8_1d_ptr /= 0) then
  call c_f_pointer (z_int8_1d_ptr, f_int8_1d_ptr, [n1_int8_1d_ptr])
  if (.not. associated(F%int8_1d_ptr)) allocate(F%int8_1d_ptr(n1_int8_1d_ptr))
  F%int8_1d_ptr = f_int8_1d_ptr(1:n1_int8_1d_ptr)
else
  if (associated(F%int8_1d_ptr)) deallocate(F%int8_1d_ptr)
endif

!! f_side.to_f2_trans[integer8, 2, PTR]
if (associated(F%int8_2d_ptr)) then
  if (n1_int8_2d_ptr == 0 .or. any(shape(F%int8_2d_ptr) /= [n1_int8_2d_ptr, n2_int8_2d_ptr])) deallocate(F%int8_2d_ptr)
  if (any(lbound(F%int8_2d_ptr) /= 1)) deallocate(F%int8_2d_ptr)
endif
if (n1_int8_2d_ptr /= 0) then
  call c_f_pointer (z_int8_2d_ptr, f_int8_2d_ptr, [n1_int8_2d_ptr*n2_int8_2d_ptr])
  if (.not. associated(F%int8_2d_ptr)) allocate(F%int8_2d_ptr(n1_int8_2d_ptr, n2_int8_2d_ptr))
  call vec2mat(f_int8_2d_ptr, F%int8_2d_ptr)
else
  if (associated(F%int8_2d_ptr)) deallocate(F%int8_2d_ptr)
endif

!! f_side.to_f2_trans[integer8, 3, PTR]
if (associated(F%int8_3d_ptr)) then
  if (n1_int8_3d_ptr == 0 .or. any(shape(F%int8_3d_ptr) /= [n1_int8_3d_ptr, n2_int8_3d_ptr, n3_int8_3d_ptr])) deallocate(F%int8_3d_ptr)
  if (any(lbound(F%int8_3d_ptr) /= 1)) deallocate(F%int8_3d_ptr)
endif
if (n1_int8_3d_ptr /= 0) then
  call c_f_pointer (z_int8_3d_ptr, f_int8_3d_ptr, [n1_int8_3d_ptr*n2_int8_3d_ptr*n3_int8_3d_ptr])
  if (.not. associated(F%int8_3d_ptr)) allocate(F%int8_3d_ptr(n1_int8_3d_ptr, n2_int8_3d_ptr, n3_int8_3d_ptr))
  call vec2tensor(f_int8_3d_ptr, F%int8_3d_ptr)
else
  if (associated(F%int8_3d_ptr)) deallocate(F%int8_3d_ptr)
endif

!! f_side.to_f2_trans[integer8, 1, ALLOC]
if (allocated(F%int8_1d_alloc)) then
  if (n1_int8_1d_alloc == 0 .or. any(shape(F%int8_1d_alloc) /= [n1_int8_1d_alloc])) deallocate(F%int8_1d_alloc)
  if (any(lbound(F%int8_1d_alloc) /= 1)) deallocate(F%int8_1d_alloc)
endif
if (n1_int8_1d_alloc /= 0) then
  call c_f_pointer (z_int8_1d_alloc, f_int8_1d_alloc, [n1_int8_1d_alloc])
  if (.not. allocated(F%int8_1d_alloc)) allocate(F%int8_1d_alloc(n1_int8_1d_alloc))
  F%int8_1d_alloc = f_int8_1d_alloc(1:n1_int8_1d_alloc)
else
  if (allocated(F%int8_1d_alloc)) deallocate(F%int8_1d_alloc)
endif

!! f_side.to_f2_trans[integer8, 2, ALLOC]
if (allocated(F%int8_2d_alloc)) then
  if (n1_int8_2d_alloc == 0 .or. any(shape(F%int8_2d_alloc) /= [n1_int8_2d_alloc, n2_int8_2d_alloc])) deallocate(F%int8_2d_alloc)
  if (any(lbound(F%int8_2d_alloc) /= 1)) deallocate(F%int8_2d_alloc)
endif
if (n1_int8_2d_alloc /= 0) then
  call c_f_pointer (z_int8_2d_alloc, f_int8_2d_alloc, [n1_int8_2d_alloc*n2_int8_2d_alloc])
  if (.not. allocated(F%int8_2d_alloc)) allocate(F%int8_2d_alloc(n1_int8_2d_alloc, n2_int8_2d_alloc))
  call vec2mat(f_int8_2d_alloc, F%int8_2d_alloc)
else
  if (allocated(F%int8_2d_alloc)) deallocate(F%int8_2d_alloc)
endif

!! f_side.to_f2_trans[integer8, 3, ALLOC]
if (allocated(F%int8_3d_alloc)) then
  if (n1_int8_3d_alloc == 0 .or. any(shape(F%int8_3d_alloc) /= [n1_int8_3d_alloc, n2_int8_3d_alloc, n3_int8_3d_alloc])) deallocate(F%int8_3d_alloc)
  if (any(lbound(F%int8_3d_alloc) /= 1)) deallocate(F%int8_3d_alloc)
endif
if (n1_int8_3d_alloc /= 0) then
  call c_f_pointer (z_int8_3d_alloc, f_int8_3d_alloc, [n1_int8_3d_alloc*n2_int8_3d_alloc*n3_int8_3d_alloc])
  if (.not. allocated(F%int8_3d_alloc)) allocate(F%int8_3d_alloc(n1_int8_3d_alloc, n2_int8_3d_alloc, n3_int8_3d_alloc))
  call vec2tensor(f_int8_3d_alloc, F%int8_3d_alloc)
else
  if (allocated(F%int8_3d_alloc)) deallocate(F%int8_3d_alloc)
endif

!! f_side.to_f2_trans[logical, 0, NOT]
F%logical_0d = f_logic(z_logical_0d)
!! f_side.to_f2_trans[logical, 1, NOT]
call vec2fvec (z_logical_1d, F%logical_1d)
!! f_side.to_f2_trans[logical, 2, NOT]
call vec2mat(z_logical_2d, F%logical_2d)
!! f_side.to_f2_trans[logical, 3, NOT]
call vec2tensor(z_logical_3d, F%logical_3d)
!! f_side.to_f2_trans[logical, 0, PTR]
if (n_logical_0d_ptr == 0) then                                                                                  
  if (associated(F%logical_0d_ptr)) deallocate(F%logical_0d_ptr)                                                           
else                                                                                                   
  call c_f_pointer (z_logical_0d_ptr, f_logical_0d_ptr)                                                                    
  if (.not. associated(F%logical_0d_ptr)) allocate(F%logical_0d_ptr)                                                       
  F%logical_0d_ptr = f_logic(f_logical_0d_ptr)
endif                                                                                                  

!! f_side.to_f2_trans[type, 0, NOT]
call wake_lr_to_f(z_type_0d, c_loc(F%type_0d))
!! f_side.to_f2_trans[type, 1, NOT]
do jd1 = 1, size(F%type_1d,1); lb1 = lbound(F%type_1d,1) - 1
  call wake_lr_to_f(z_type_1d(jd1), c_loc(F%type_1d(jd1+lb1)))
enddo
!! f_side.to_f2_trans[type, 2, NOT]
do jd1 = 1, size(F%type_2d,1); lb1 = lbound(F%type_2d,1) - 1
do jd2 = 1, size(F%type_2d,2); lb2 = lbound(F%type_2d,2) - 1
  call wake_lr_to_f(z_type_2d(4*(jd1-1) + jd2), c_loc(F%type_2d(jd1+lb1,jd2+lb2)))
enddo; enddo

!! f_side.to_f2_trans[type, 3, NOT]
do jd1 = 1, size(F%type_3d,1); lb1 = lbound(F%type_3d,1) - 1
do jd2 = 1, size(F%type_3d,2); lb2 = lbound(F%type_3d,2) - 1
do jd3 = 1, size(F%type_3d,3); lb3 = lbound(F%type_3d,3) - 1
  call wake_lr_to_f(z_type_3d(5*4*(jd1-1) + 5*(jd2-1) + jd3), c_loc(F%type_3d(jd1+lb1,jd2+lb2,jd3+lb3)))
enddo; enddo; enddo

!! f_side.to_f2_trans[type, 0, PTR]
if (n_type_0d_ptr == 0) then
  if (associated(F%type_0d_ptr)) deallocate(F%type_0d_ptr)
else
  if (.not. associated(F%type_0d_ptr)) allocate(F%type_0d_ptr)
  call wake_lr_to_f (z_type_0d_ptr, c_loc(F%type_0d_ptr))
endif

!! f_side.to_f2_trans[type, 1, PTR]
if (n1_type_1d_ptr == 0) then
  if (associated(F%type_1d_ptr)) deallocate(F%type_1d_ptr)
else
  if (associated(F%type_1d_ptr)) then
    if (n1_type_1d_ptr == 0 .or. any(shape(F%type_1d_ptr) /= [n1_type_1d_ptr])) deallocate(F%type_1d_ptr)
    if (any(lbound(F%type_1d_ptr) /= 1)) deallocate(F%type_1d_ptr)
  endif
  if (.not. associated(F%type_1d_ptr)) allocate(F%type_1d_ptr(1:n1_type_1d_ptr+1-1))
  do jd1 = 1, n1_type_1d_ptr
    call wake_lr_to_f (z_type_1d_ptr(jd1), c_loc(F%type_1d_ptr(jd1+1-1)))
  enddo
endif

!! f_side.to_f2_trans[type, 2, PTR]
if (n1_type_2d_ptr == 0) then
  if (associated(F%type_2d_ptr)) deallocate(F%type_2d_ptr)
else
  if (associated(F%type_2d_ptr)) then
    if (n1_type_2d_ptr == 0 .or. any(shape(F%type_2d_ptr) /= [n1_type_2d_ptr, n2_type_2d_ptr])) deallocate(F%type_2d_ptr)
    if (any(lbound(F%type_2d_ptr) /= 1)) deallocate(F%type_2d_ptr)
  endif
  if (.not. associated(F%type_2d_ptr)) allocate(F%type_2d_ptr(1:n1_type_2d_ptr+1-1, 1:n2_type_2d_ptr+1-1))
  do jd1 = 1, n1_type_2d_ptr
  do jd2 = 1, n2_type_2d_ptr
    call wake_lr_to_f (z_type_2d_ptr(n2_type_2d_ptr*(jd1-1) + jd2), c_loc(F%type_2d_ptr(jd1+1-1,jd2+1-1)))
  enddo
  enddo
endif

!! f_side.to_f2_trans[type, 3, PTR]
if (n1_type_3d_ptr == 0) then
  if (associated(F%type_3d_ptr)) deallocate(F%type_3d_ptr)
else
  if (associated(F%type_3d_ptr)) then
    if (n1_type_3d_ptr == 0 .or. any(shape(F%type_3d_ptr) /= [n1_type_3d_ptr, n2_type_3d_ptr, n3_type_3d_ptr])) deallocate(F%type_3d_ptr)
    if (any(lbound(F%type_3d_ptr) /= 1)) deallocate(F%type_3d_ptr)
  endif
  if (.not. associated(F%type_3d_ptr)) allocate(F%type_3d_ptr(1:n1_type_3d_ptr+1-1, 1:n2_type_3d_ptr+1-1, 1:n3_type_3d_ptr+1-1))
  do jd1 = 1, n1_type_3d_ptr;  do jd2 = 1, n2_type_3d_ptr;  do jd3 = 1, n3_type_3d_ptr
    call wake_lr_to_f (z_type_3d_ptr(n3_type_3d_ptr*n2_type_3d_ptr*(jd1-1) + n3_type_3d_ptr*(jd2-1) + jd3), c_loc(F%type_3d_ptr(jd1+1-1,jd2+1-1,jd3+1-1)))
  enddo;  enddo;  enddo
endif

!! f_side.to_f2_trans[type, 1, ALLOC]
if (n1_type_1d_alloc == 0) then
  if (allocated(F%type_1d_alloc)) deallocate(F%type_1d_alloc)
else
  if (allocated(F%type_1d_alloc)) then
    if (n1_type_1d_alloc == 0 .or. any(shape(F%type_1d_alloc) /= [n1_type_1d_alloc])) deallocate(F%type_1d_alloc)
    if (any(lbound(F%type_1d_alloc) /= 1)) deallocate(F%type_1d_alloc)
  endif
  if (.not. allocated(F%type_1d_alloc)) allocate(F%type_1d_alloc(1:n1_type_1d_alloc+1-1))
  do jd1 = 1, n1_type_1d_alloc
    call wake_lr_to_f (z_type_1d_alloc(jd1), c_loc(F%type_1d_alloc(jd1+1-1)))
  enddo
endif

!! f_side.to_f2_trans[type, 2, ALLOC]
if (n1_type_2d_alloc == 0) then
  if (allocated(F%type_2d_alloc)) deallocate(F%type_2d_alloc)
else
  if (allocated(F%type_2d_alloc)) then
    if (n1_type_2d_alloc == 0 .or. any(shape(F%type_2d_alloc) /= [n1_type_2d_alloc, n2_type_2d_alloc])) deallocate(F%type_2d_alloc)
    if (any(lbound(F%type_2d_alloc) /= 1)) deallocate(F%type_2d_alloc)
  endif
  if (.not. allocated(F%type_2d_alloc)) allocate(F%type_2d_alloc(1:n1_type_2d_alloc+1-1, 1:n2_type_2d_alloc+1-1))
  do jd1 = 1, n1_type_2d_alloc
  do jd2 = 1, n2_type_2d_alloc
    call wake_lr_to_f (z_type_2d_alloc(n2_type_2d_alloc*(jd1-1) + jd2), c_loc(F%type_2d_alloc(jd1+1-1,jd2+1-1)))
  enddo
  enddo
endif

!! f_side.to_f2_trans[type, 3, ALLOC]
if (n1_type_3d_alloc == 0) then
  if (allocated(F%type_3d_alloc)) deallocate(F%type_3d_alloc)
else
  if (allocated(F%type_3d_alloc)) then
    if (n1_type_3d_alloc == 0 .or. any(shape(F%type_3d_alloc) /= [n1_type_3d_alloc, n2_type_3d_alloc, n3_type_3d_alloc])) deallocate(F%type_3d_alloc)
    if (any(lbound(F%type_3d_alloc) /= 1)) deallocate(F%type_3d_alloc)
  endif
  if (.not. allocated(F%type_3d_alloc)) allocate(F%type_3d_alloc(1:n1_type_3d_alloc+1-1, 1:n2_type_3d_alloc+1-1, 1:n3_type_3d_alloc+1-1))
  do jd1 = 1, n1_type_3d_alloc;  do jd2 = 1, n2_type_3d_alloc;  do jd3 = 1, n3_type_3d_alloc
    call wake_lr_to_f (z_type_3d_alloc(n3_type_3d_alloc*n2_type_3d_alloc*(jd1-1) + n3_type_3d_alloc*(jd2-1) + jd3), c_loc(F%type_3d_alloc(jd1+1-1,jd2+1-1,jd3+1-1)))
  enddo;  enddo;  enddo
endif


end subroutine all_encompassing_to_f2
end module
