//+
// C++ equality functions for Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY!
//-

#include <iostream>
#include <string>
#include <vector>

#include "bmad_std_typedef.h"
#include "cpp_bmad_classes.h"

using namespace std;

using std::vector, std::string;

//---------------------------------------------------

template <class T>
bool is_all_equal(const VariableArray1D<T> &vec1,
                  const VariableArray1D<T> &vec2) {
  if (vec1.size() != vec2.size())
    return false;
  for (size_t i = 0; i < vec1.size(); i++) {
    if (!(vec1[i] == vec2[i]))
      return false;
  }
  return true;
}

template <class T>
bool is_all_equal(const vector<vector<T>> &mat1,
                  const vector<vector<T>> &mat2) {
  if (mat1.size() != mat2.size())
    return false;
  for (size_t i = 0; i < mat1.size(); i++) {
    if (mat1[i].size() != mat2[i].size())
      return false;
    for (size_t j = 0; j < mat1[i].size(); j++) {
      if (!(mat1[i][j] == mat2[i][j]))
        return false;
    }
  }
  return true;
}

template <class T>
bool is_all_equal(const vector<vector<vector<T>>> &tensor1,
                  const vector<vector<vector<T>>> &tensor2) {
  if (tensor1.size() != tensor2.size())
    return false;
  for (size_t i = 0; i < tensor1.size(); i++) {
    if (tensor1[i].size() != tensor2[i].size())
      return false;
    for (size_t j = 0; j < tensor1[i].size(); j++) {
      if (tensor1[i][j].size() != tensor2[i][j].size())
        return false;
      for (size_t k = 0; k < tensor1[i][j].size(); k++) {
        if (!(tensor1[i][j][k] == tensor2[i][j][k]))
          return false;
      }
    }
  }
  return true;
}

template <typename T, std::size_t DIM1>
bool is_all_equal(const FixedArray1D<T, DIM1> &arr1,
                  const FixedArray1D<T, DIM1> &arr2) {
  // No need to check sizes since they're fixed at compile time
  for (std::size_t i = 0; i < DIM1; i++) {
    if (!(arr1[i] == arr2[i]))
      return false;
  }
  return true;
}

template <typename T, std::size_t DIM1, std::size_t DIM2>
bool is_all_equal(const FixedArray2D<T, DIM1, DIM2> &arr1,
                  const FixedArray2D<T, DIM1, DIM2> &arr2) {
  // No need to check sizes since they're fixed at compile time
  for (std::size_t i = 0; i < DIM1; i++) {
    for (std::size_t j = 0; j < DIM2; j++) {
      if (!(arr1[i][j] == arr2[i][j]))
        return false;
    }
  }
  return true;
}

template <typename T, std::size_t DIM1, std::size_t DIM2, std::size_t DIM3>
bool is_all_equal(const FixedArray3D<T, DIM1, DIM2, DIM3> &arr1,
                  const FixedArray3D<T, DIM1, DIM2, DIM3> &arr2) {
  // No need to check sizes since they're fixed at compile time
  for (std::size_t i = 0; i < DIM1; i++) {
    for (std::size_t j = 0; j < DIM2; j++) {
      for (std::size_t k = 0; k < DIM3; k++) {
        if (!(arr1[i][j][k] == arr2[i][j][k]))
          return false;
      }
    }
  }
  return true;
}
//---------------------------------------------------

//--------------------------------------------------------------

bool operator== (const CPP_wake_lr& x, const CPP_wake_lr& y) {
  bool is_eq = true;
  is_eq = is_eq && (x.aaa == y.aaa);
  is_eq = is_eq && (x.bbb == y.bbb);
  is_eq = is_eq && (x.file == y.file);
  is_eq = is_eq && (x.t_ref == y.t_ref);
  is_eq = is_eq && (x.freq_spread == y.freq_spread);
  return is_eq;
};


//--------------------------------------------------------------

bool operator== (const CPP_wake& x, const CPP_wake& y) {
  bool is_eq = true;
  is_eq = is_eq && (x.sr == y.sr);
  return is_eq;
};


//--------------------------------------------------------------

bool operator== (const CPP_all_encompassing& x, const CPP_all_encompassing& y) {
  bool is_eq = true;
  is_eq = is_eq && (x.real_rp_0d == y.real_rp_0d);
  is_eq = is_eq && is_all_equal(x.real_rp_1d, y.real_rp_1d);
  is_eq = is_eq && is_all_equal(x.real_rp_2d, y.real_rp_2d);
  is_eq = is_eq && is_all_equal(x.real_rp_3d, y.real_rp_3d);
  is_eq = is_eq && ((x.real_rp_0d_ptr == NULL) == (y.real_rp_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.real_rp_0d_ptr != NULL) is_eq = (*x.real_rp_0d_ptr == *y.real_rp_0d_ptr);
  is_eq = is_eq && is_all_equal(x.real_rp_1d_ptr, y.real_rp_1d_ptr);
  is_eq = is_eq && is_all_equal(x.real_rp_2d_ptr, y.real_rp_2d_ptr);
  is_eq = is_eq && is_all_equal(x.real_rp_3d_ptr, y.real_rp_3d_ptr);
  is_eq = is_eq && is_all_equal(x.real_rp_1d_alloc, y.real_rp_1d_alloc);
  is_eq = is_eq && is_all_equal(x.real_rp_2d_alloc, y.real_rp_2d_alloc);
  is_eq = is_eq && is_all_equal(x.real_rp_3d_alloc, y.real_rp_3d_alloc);
  is_eq = is_eq && (x.real_dp_0d == y.real_dp_0d);
  is_eq = is_eq && is_all_equal(x.real_dp_1d, y.real_dp_1d);
  is_eq = is_eq && is_all_equal(x.real_dp_2d, y.real_dp_2d);
  is_eq = is_eq && is_all_equal(x.real_dp_3d, y.real_dp_3d);
  is_eq = is_eq && ((x.real_dp_0d_ptr == NULL) == (y.real_dp_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.real_dp_0d_ptr != NULL) is_eq = (*x.real_dp_0d_ptr == *y.real_dp_0d_ptr);
  is_eq = is_eq && is_all_equal(x.real_dp_1d_ptr, y.real_dp_1d_ptr);
  is_eq = is_eq && is_all_equal(x.real_dp_2d_ptr, y.real_dp_2d_ptr);
  is_eq = is_eq && is_all_equal(x.real_dp_3d_ptr, y.real_dp_3d_ptr);
  is_eq = is_eq && is_all_equal(x.real_dp_1d_alloc, y.real_dp_1d_alloc);
  is_eq = is_eq && is_all_equal(x.real_dp_2d_alloc, y.real_dp_2d_alloc);
  is_eq = is_eq && is_all_equal(x.real_dp_3d_alloc, y.real_dp_3d_alloc);
  is_eq = is_eq && (x.complex_dp_0d == y.complex_dp_0d);
  is_eq = is_eq && is_all_equal(x.complex_dp_1d, y.complex_dp_1d);
  is_eq = is_eq && is_all_equal(x.complex_dp_2d, y.complex_dp_2d);
  is_eq = is_eq && is_all_equal(x.complex_dp_3d, y.complex_dp_3d);
  is_eq = is_eq && ((x.complex_dp_0d_ptr == NULL) == (y.complex_dp_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.complex_dp_0d_ptr != NULL) is_eq = (*x.complex_dp_0d_ptr == *y.complex_dp_0d_ptr);
  is_eq = is_eq && is_all_equal(x.complex_dp_1d_ptr, y.complex_dp_1d_ptr);
  is_eq = is_eq && is_all_equal(x.complex_dp_2d_ptr, y.complex_dp_2d_ptr);
  is_eq = is_eq && is_all_equal(x.complex_dp_3d_ptr, y.complex_dp_3d_ptr);
  is_eq = is_eq && is_all_equal(x.complex_dp_1d_alloc, y.complex_dp_1d_alloc);
  is_eq = is_eq && is_all_equal(x.complex_dp_2d_alloc, y.complex_dp_2d_alloc);
  is_eq = is_eq && is_all_equal(x.complex_dp_3d_alloc, y.complex_dp_3d_alloc);
  is_eq = is_eq && (x.int_0d == y.int_0d);
  is_eq = is_eq && is_all_equal(x.int_1d, y.int_1d);
  is_eq = is_eq && is_all_equal(x.int_2d, y.int_2d);
  is_eq = is_eq && is_all_equal(x.int_3d, y.int_3d);
  is_eq = is_eq && ((x.int_0d_ptr == NULL) == (y.int_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.int_0d_ptr != NULL) is_eq = (*x.int_0d_ptr == *y.int_0d_ptr);
  is_eq = is_eq && is_all_equal(x.int_1d_ptr, y.int_1d_ptr);
  is_eq = is_eq && is_all_equal(x.int_2d_ptr, y.int_2d_ptr);
  is_eq = is_eq && is_all_equal(x.int_3d_ptr, y.int_3d_ptr);
  is_eq = is_eq && is_all_equal(x.int_1d_alloc, y.int_1d_alloc);
  is_eq = is_eq && is_all_equal(x.int_2d_alloc, y.int_2d_alloc);
  is_eq = is_eq && is_all_equal(x.int_3d_alloc, y.int_3d_alloc);
  is_eq = is_eq && (x.int8_0d == y.int8_0d);
  is_eq = is_eq && is_all_equal(x.int8_1d, y.int8_1d);
  is_eq = is_eq && is_all_equal(x.int8_2d, y.int8_2d);
  is_eq = is_eq && is_all_equal(x.int8_3d, y.int8_3d);
  is_eq = is_eq && ((x.int8_0d_ptr == NULL) == (y.int8_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.int8_0d_ptr != NULL) is_eq = (*x.int8_0d_ptr == *y.int8_0d_ptr);
  is_eq = is_eq && is_all_equal(x.int8_1d_ptr, y.int8_1d_ptr);
  is_eq = is_eq && is_all_equal(x.int8_2d_ptr, y.int8_2d_ptr);
  is_eq = is_eq && is_all_equal(x.int8_3d_ptr, y.int8_3d_ptr);
  is_eq = is_eq && is_all_equal(x.int8_1d_alloc, y.int8_1d_alloc);
  is_eq = is_eq && is_all_equal(x.int8_2d_alloc, y.int8_2d_alloc);
  is_eq = is_eq && is_all_equal(x.int8_3d_alloc, y.int8_3d_alloc);
  is_eq = is_eq && (x.logical_0d == y.logical_0d);
  is_eq = is_eq && is_all_equal(x.logical_1d, y.logical_1d);
  is_eq = is_eq && is_all_equal(x.logical_2d, y.logical_2d);
  is_eq = is_eq && is_all_equal(x.logical_3d, y.logical_3d);
  is_eq = is_eq && ((x.logical_0d_ptr == NULL) == (y.logical_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.logical_0d_ptr != NULL) is_eq = (*x.logical_0d_ptr == *y.logical_0d_ptr);
  is_eq = is_eq && (x.type_0d == y.type_0d);
  is_eq = is_eq && is_all_equal(x.type_1d, y.type_1d);
  is_eq = is_eq && is_all_equal(x.type_2d, y.type_2d);
  is_eq = is_eq && is_all_equal(x.type_3d, y.type_3d);
  is_eq = is_eq && ((x.type_0d_ptr == NULL) == (y.type_0d_ptr == NULL));
  if (!is_eq) return false;
  if (x.type_0d_ptr != NULL) is_eq = (*x.type_0d_ptr == *y.type_0d_ptr);
  is_eq = is_eq && is_all_equal(x.type_1d_ptr, y.type_1d_ptr);
  is_eq = is_eq && is_all_equal(x.type_2d_ptr, y.type_2d_ptr);
  is_eq = is_eq && is_all_equal(x.type_3d_ptr, y.type_3d_ptr);
  is_eq = is_eq && is_all_equal(x.type_1d_alloc, y.type_1d_alloc);
  is_eq = is_eq && is_all_equal(x.type_2d_alloc, y.type_2d_alloc);
  is_eq = is_eq && is_all_equal(x.type_3d_alloc, y.type_3d_alloc);
  return is_eq;
};

