//+
// C++ JSON helpers for Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY!
//-

#include <iostream>
#include <memory>
#include <optional>

#include "bmad_enums.h"
#include "bmad_std_typedef.h"
#include "converter_templates.h"
#include "cpp_bmad_classes.h"
#include "json.hpp"

using namespace Bmad;
using std::ostream;
using std::size_t;
using json = nlohmann::json;

namespace std {
template <typename T>
void to_json(json& j, const complex<T>& d) {
  j = {d.real(), d.imag()};
}
void from_json(const json& j, Complex& d) {
  d.real(j.at(0).get<double>());
  d.imag(j.at(1).get<double>());
}
} // namespace std

namespace Bmad {
//--------------------------------------------------------------------
void to_json(json& j, const CPP_spline& obj) {
  j = json{{"x0", obj.x0}, {"y0", obj.y0}, {"x1", obj.x1}, {"coef", obj.coef}};
}

ostream& operator<<(ostream& os, const CPP_spline& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_spin_polar& obj) {
  j = json{
      {"polarization", obj.polarization},
      {"theta", obj.theta},
      {"phi", obj.phi},
      {"xi", obj.xi}};
}

ostream& operator<<(ostream& os, const CPP_spin_polar& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ac_kicker_time& obj) {
  j = json{{"amp", obj.amp}, {"time", obj.time}, {"spline", obj.spline}};
}

ostream& operator<<(ostream& os, const CPP_ac_kicker_time& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ac_kicker_freq& obj) {
  j = json{
      {"f", obj.f},
      {"amp", obj.amp},
      {"phi", obj.phi},
      {"rf_clock_harmonic", obj.rf_clock_harmonic}};
}

ostream& operator<<(ostream& os, const CPP_ac_kicker_freq& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ac_kicker& obj) {
  j = json{{"amp_vs_time", obj.amp_vs_time}, {"frequency", obj.frequency}};
}

ostream& operator<<(ostream& os, const CPP_ac_kicker& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_interval1_coef& obj) {
  j = json{{"c0", obj.c0}, {"c1", obj.c1}, {"n_exp", obj.n_exp}};
}

ostream& operator<<(ostream& os, const CPP_interval1_coef& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_photon_reflect_table& obj) {
  j = json{
      {"angle", obj.angle},
      {"energy", obj.energy},
      {"int1", obj.int1},
      {"p_reflect", obj.p_reflect},
      {"max_energy", obj.max_energy},
      {"p_reflect_scratch", obj.p_reflect_scratch},
      {"bragg_angle", obj.bragg_angle}};
}

ostream& operator<<(ostream& os, const CPP_photon_reflect_table& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_photon_reflect_surface& obj) {
  j = json{
      {"name", obj.name},
      {"description", obj.description},
      {"reflectivity_file", obj.reflectivity_file},
      {"table", obj.table},
      {"surface_roughness_rms", obj.surface_roughness_rms},
      {"roughness_correlation_len", obj.roughness_correlation_len},
      {"ix_surface", obj.ix_surface}};
}

ostream& operator<<(ostream& os, const CPP_photon_reflect_surface& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_coord& obj) {
  j = json{
      {"vec", obj.vec},
      {"s", obj.s},
      {"t", obj.t},
      {"spin", obj.spin},
      {"field", obj.field},
      {"phase", obj.phase},
      {"charge", obj.charge},
      {"dt_ref", obj.dt_ref},
      {"r", obj.r},
      {"p0c", obj.p0c},
      {"E_potential", obj.E_potential},
      {"beta", obj.beta},
      {"ix_ele", obj.ix_ele},
      {"ix_branch", obj.ix_branch},
      {"ix_turn", obj.ix_turn},
      {"ix_user", obj.ix_user},
      {"state", obj.state},
      {"direction", obj.direction},
      {"time_dir", obj.time_dir},
      {"species", obj.species},
      {"location", obj.location}};
}

ostream& operator<<(ostream& os, const CPP_coord& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_coord_array& obj) {
  j = json{{"orbit", obj.orbit}};
}

ostream& operator<<(ostream& os, const CPP_coord_array& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_bpm_phase_coupling& obj) {
  j = json{
      {"K_22a", obj.K_22a},
      {"K_12a", obj.K_12a},
      {"K_11b", obj.K_11b},
      {"K_12b", obj.K_12b},
      {"Cbar22_a", obj.Cbar22_a},
      {"Cbar12_a", obj.Cbar12_a},
      {"Cbar11_b", obj.Cbar11_b},
      {"Cbar12_b", obj.Cbar12_b},
      {"phi_a", obj.phi_a},
      {"phi_b", obj.phi_b}};
}

ostream& operator<<(ostream& os, const CPP_bpm_phase_coupling& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_expression_atom& obj) {
  j = json{{"name", obj.name}, {"type", obj.type}, {"value", obj.value}};
}

ostream& operator<<(ostream& os, const CPP_expression_atom& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wake_sr_z_long& obj) {
  j = json{
      {"w", obj.w},
      {"fw", obj.fw},
      {"fbunch", obj.fbunch},
      {"w_out", obj.w_out},
      {"dz", obj.dz},
      {"z0", obj.z0},
      {"smoothing_sigma", obj.smoothing_sigma},
      {"position_dependence", obj.position_dependence},
      {"time_based", obj.time_based}};
}

ostream& operator<<(ostream& os, const CPP_wake_sr_z_long& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wake_sr_mode& obj) {
  j = json{
      {"amp", obj.amp},
      {"damp", obj.damp},
      {"k", obj.k},
      {"phi", obj.phi},
      {"b_sin", obj.b_sin},
      {"b_cos", obj.b_cos},
      {"a_sin", obj.a_sin},
      {"a_cos", obj.a_cos},
      {"polarization", obj.polarization},
      {"position_dependence", obj.position_dependence}};
}

ostream& operator<<(ostream& os, const CPP_wake_sr_mode& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wake_sr& obj) {
  j = json{
      {"file", obj.file},
      {"z_long", obj.z_long},
      {"long_wake", obj.long_wake},
      {"trans_wake", obj.trans_wake},
      {"z_ref_long", obj.z_ref_long},
      {"z_ref_trans", obj.z_ref_trans},
      {"z_max", obj.z_max},
      {"amp_scale", obj.amp_scale},
      {"z_scale", obj.z_scale},
      {"scale_with_length", obj.scale_with_length}};
}

ostream& operator<<(ostream& os, const CPP_wake_sr& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wake_lr_mode& obj) {
  j = json{
      {"freq", obj.freq},
      {"freq_in", obj.freq_in},
      {"R_over_Q", obj.R_over_Q},
      {"Q", obj.Q},
      {"damp", obj.damp},
      {"phi", obj.phi},
      {"angle", obj.angle},
      {"b_sin", obj.b_sin},
      {"b_cos", obj.b_cos},
      {"a_sin", obj.a_sin},
      {"a_cos", obj.a_cos},
      {"m", obj.m},
      {"polarized", obj.polarized}};
}

ostream& operator<<(ostream& os, const CPP_wake_lr_mode& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wake_lr& obj) {
  j = json{
      {"file", obj.file},
      {"mode", obj.mode},
      {"t_ref", obj.t_ref},
      {"freq_spread", obj.freq_spread},
      {"amp_scale", obj.amp_scale},
      {"time_scale", obj.time_scale},
      {"self_wake_on", obj.self_wake_on}};
}

ostream& operator<<(ostream& os, const CPP_wake_lr& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_lat_ele_loc& obj) {
  j = json{{"ix_ele", obj.ix_ele}, {"ix_branch", obj.ix_branch}};
}

ostream& operator<<(ostream& os, const CPP_lat_ele_loc& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wake& obj) {
  j = json{{"sr", obj.sr}, {"lr", obj.lr}};
}

ostream& operator<<(ostream& os, const CPP_wake& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_taylor_term& obj) {
  j = json{{"coef", obj.coef}, {"expn", obj.expn}};
}

ostream& operator<<(ostream& os, const CPP_taylor_term& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_taylor& obj) {
  j = json{{"ref", obj.ref}, {"term", obj.term}};
}

ostream& operator<<(ostream& os, const CPP_taylor& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_em_taylor_term& obj) {
  j = json{{"coef", obj.coef}, {"expn", obj.expn}};
}

ostream& operator<<(ostream& os, const CPP_em_taylor_term& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_em_taylor& obj) {
  j = json{{"ref", obj.ref}, {"term", obj.term}};
}

ostream& operator<<(ostream& os, const CPP_em_taylor& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_cartesian_map_term1& obj) {
  j = json{
      {"coef", obj.coef},
      {"kx", obj.kx},
      {"ky", obj.ky},
      {"kz", obj.kz},
      {"x0", obj.x0},
      {"y0", obj.y0},
      {"phi_z", obj.phi_z},
      {"family", obj.family},
      {"form", obj.form}};
}

ostream& operator<<(ostream& os, const CPP_cartesian_map_term1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_cartesian_map_term& obj) {
  j = json{{"file", obj.file}, {"n_link", obj.n_link}, {"term", obj.term}};
}

ostream& operator<<(ostream& os, const CPP_cartesian_map_term& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_cartesian_map& obj) {
  j = json{
      {"field_scale", obj.field_scale},
      {"r0", obj.r0},
      {"master_parameter", obj.master_parameter},
      {"ele_anchor_pt", obj.ele_anchor_pt},
      {"field_type", obj.field_type},
      {"ptr", obj.ptr}};
}

ostream& operator<<(ostream& os, const CPP_cartesian_map& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_cylindrical_map_term1& obj) {
  j = json{{"e_coef", obj.e_coef}, {"b_coef", obj.b_coef}};
}

ostream& operator<<(ostream& os, const CPP_cylindrical_map_term1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_cylindrical_map_term& obj) {
  j = json{{"file", obj.file}, {"n_link", obj.n_link}, {"term", obj.term}};
}

ostream& operator<<(ostream& os, const CPP_cylindrical_map_term& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_cylindrical_map& obj) {
  j = json{
      {"m", obj.m},
      {"harmonic", obj.harmonic},
      {"phi0_fieldmap", obj.phi0_fieldmap},
      {"theta0_azimuth", obj.theta0_azimuth},
      {"field_scale", obj.field_scale},
      {"master_parameter", obj.master_parameter},
      {"ele_anchor_pt", obj.ele_anchor_pt},
      {"dz", obj.dz},
      {"r0", obj.r0},
      {"ptr", obj.ptr}};
}

ostream& operator<<(ostream& os, const CPP_cylindrical_map& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_bicubic_cmplx_coef& obj) {
  j = json{{"coef", obj.coef}, {"i_box", obj.i_box}};
}

ostream& operator<<(ostream& os, const CPP_bicubic_cmplx_coef& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_tricubic_cmplx_coef& obj) {
  j = json{{"coef", obj.coef}, {"i_box", obj.i_box}};
}

ostream& operator<<(ostream& os, const CPP_tricubic_cmplx_coef& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_grid_field_pt1& obj) {
  j = json{{"E", obj.E}, {"B", obj.B}};
}

ostream& operator<<(ostream& os, const CPP_grid_field_pt1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_grid_field_pt& obj) {
  j = json{{"file", obj.file}, {"n_link", obj.n_link}, {"pt", obj.pt}};
}

ostream& operator<<(ostream& os, const CPP_grid_field_pt& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_grid_field& obj) {
  j = json{
      {"geometry", obj.geometry},
      {"harmonic", obj.harmonic},
      {"phi0_fieldmap", obj.phi0_fieldmap},
      {"field_scale", obj.field_scale},
      {"field_type", obj.field_type},
      {"master_parameter", obj.master_parameter},
      {"ele_anchor_pt", obj.ele_anchor_pt},
      {"interpolation_order", obj.interpolation_order},
      {"dr", obj.dr},
      {"r0", obj.r0},
      {"curved_ref_frame", obj.curved_ref_frame},
      {"ptr", obj.ptr},
      {"bi_coef", obj.bi_coef},
      {"tri_coef", obj.tri_coef}};
}

ostream& operator<<(ostream& os, const CPP_grid_field& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_floor_position& obj) {
  j = json{
      {"r", obj.r},
      {"w", obj.w},
      {"theta", obj.theta},
      {"phi", obj.phi},
      {"psi", obj.psi}};
}

ostream& operator<<(ostream& os, const CPP_floor_position& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_high_energy_space_charge& obj) {
  j = json{
      {"closed_orb", obj.closed_orb},
      {"kick_const", obj.kick_const},
      {"sig_x", obj.sig_x},
      {"sig_y", obj.sig_y},
      {"phi", obj.phi},
      {"sin_phi", obj.sin_phi},
      {"cos_phi", obj.cos_phi},
      {"sig_z", obj.sig_z}};
}

ostream& operator<<(ostream& os, const CPP_high_energy_space_charge& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_xy_disp& obj) {
  j = json{
      {"eta", obj.eta},
      {"etap", obj.etap},
      {"deta_ds", obj.deta_ds},
      {"sigma", obj.sigma}};
}

ostream& operator<<(ostream& os, const CPP_xy_disp& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_twiss& obj) {
  j = json{
      {"beta", obj.beta},
      {"alpha", obj.alpha},
      {"gamma", obj.gamma},
      {"phi", obj.phi},
      {"eta", obj.eta},
      {"etap", obj.etap},
      {"deta_ds", obj.deta_ds},
      {"sigma", obj.sigma},
      {"sigma_p", obj.sigma_p},
      {"emit", obj.emit},
      {"norm_emit", obj.norm_emit},
      {"dbeta_dpz", obj.dbeta_dpz},
      {"dalpha_dpz", obj.dalpha_dpz}};
}

ostream& operator<<(ostream& os, const CPP_twiss& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_mode3& obj) {
  j = json{
      {"v", obj.v},
      {"a", obj.a},
      {"b", obj.b},
      {"c", obj.c},
      {"x", obj.x},
      {"y", obj.y}};
}

ostream& operator<<(ostream& os, const CPP_mode3& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_bookkeeping_state& obj) {
  j = json{
      {"attributes", obj.attributes},
      {"control", obj.control},
      {"floor_position", obj.floor_position},
      {"s_position", obj.s_position},
      {"ref_energy", obj.ref_energy},
      {"mat6", obj.mat6},
      {"rad_int", obj.rad_int},
      {"ptc", obj.ptc},
      {"has_misalign", obj.has_misalign}};
}

ostream& operator<<(ostream& os, const CPP_bookkeeping_state& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_rad_map& obj) {
  j = json{
      {"ref_orb", obj.ref_orb},
      {"damp_dmat", obj.damp_dmat},
      {"xfer_damp_vec", obj.xfer_damp_vec},
      {"xfer_damp_mat", obj.xfer_damp_mat},
      {"stoc_mat", obj.stoc_mat}};
}

ostream& operator<<(ostream& os, const CPP_rad_map& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_rad_map_ele& obj) {
  j = json{{"rm0", obj.rm0}, {"rm1", obj.rm1}, {"stale", obj.stale}};
}

ostream& operator<<(ostream& os, const CPP_rad_map_ele& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_gen_grad1& obj) {
  j = json{
      {"m", obj.m},
      {"sincos", obj.sincos},
      {"n_deriv_max", obj.n_deriv_max},
      {"deriv", obj.deriv}};
}

ostream& operator<<(ostream& os, const CPP_gen_grad1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_gen_grad_map& obj) {
  j = json{
      {"file", obj.file},
      {"gg", obj.gg},
      {"ele_anchor_pt", obj.ele_anchor_pt},
      {"field_type", obj.field_type},
      {"iz0", obj.iz0},
      {"iz1", obj.iz1},
      {"dz", obj.dz},
      {"r0", obj.r0},
      {"field_scale", obj.field_scale},
      {"master_parameter", obj.master_parameter},
      {"curved_ref_frame", obj.curved_ref_frame}};
}

ostream& operator<<(ostream& os, const CPP_gen_grad_map& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_segmented_pt& obj) {
  j = json{
      {"x0", obj.x0},
      {"y0", obj.y0},
      {"z0", obj.z0},
      {"dz_dx", obj.dz_dx},
      {"dz_dy", obj.dz_dy}};
}

ostream& operator<<(ostream& os, const CPP_surface_segmented_pt& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_segmented& obj) {
  j = json{
      {"active", obj.active}, {"dr", obj.dr}, {"r0", obj.r0}, {"pt", obj.pt}};
}

ostream& operator<<(ostream& os, const CPP_surface_segmented& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_h_misalign_pt& obj) {
  j = json{
      {"x0", obj.x0},
      {"y0", obj.y0},
      {"rot_y", obj.rot_y},
      {"rot_t", obj.rot_t},
      {"rot_y_rms", obj.rot_y_rms},
      {"rot_t_rms", obj.rot_t_rms}};
}

ostream& operator<<(ostream& os, const CPP_surface_h_misalign_pt& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_h_misalign& obj) {
  j = json{
      {"active", obj.active}, {"dr", obj.dr}, {"r0", obj.r0}, {"pt", obj.pt}};
}

ostream& operator<<(ostream& os, const CPP_surface_h_misalign& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_displacement_pt& obj) {
  j = json{
      {"x0", obj.x0},
      {"y0", obj.y0},
      {"z0", obj.z0},
      {"dz_dx", obj.dz_dx},
      {"dz_dy", obj.dz_dy},
      {"d2z_dxdy", obj.d2z_dxdy}};
}

ostream& operator<<(ostream& os, const CPP_surface_displacement_pt& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_displacement& obj) {
  j = json{
      {"active", obj.active}, {"dr", obj.dr}, {"r0", obj.r0}, {"pt", obj.pt}};
}

ostream& operator<<(ostream& os, const CPP_surface_displacement& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_target_point& obj) {
  j = json{{"r", obj.r}};
}

ostream& operator<<(ostream& os, const CPP_target_point& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_surface_curvature& obj) {
  j = json{
      {"xy", obj.xy},
      {"spherical", obj.spherical},
      {"elliptical", obj.elliptical},
      {"has_curvature", obj.has_curvature}};
}

ostream& operator<<(ostream& os, const CPP_surface_curvature& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_photon_target& obj) {
  j = json{
      {"type", obj.type},
      {"n_corner", obj.n_corner},
      {"ele_loc", obj.ele_loc},
      {"corner", obj.corner},
      {"center", obj.center}};
}

ostream& operator<<(ostream& os, const CPP_photon_target& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_photon_material& obj) {
  j = json{
      {"f0_m1", obj.f0_m1},
      {"f0_m2", obj.f0_m2},
      {"f_0", obj.f_0},
      {"f_h", obj.f_h},
      {"f_hbar", obj.f_hbar},
      {"f_hkl", obj.f_hkl},
      {"h_norm", obj.h_norm},
      {"l_ref", obj.l_ref}};
}

ostream& operator<<(ostream& os, const CPP_photon_material& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_pixel_pt& obj) {
  j = json{
      {"n_photon", obj.n_photon},
      {"E_x", obj.E_x},
      {"E_y", obj.E_y},
      {"intensity_x", obj.intensity_x},
      {"intensity_y", obj.intensity_y},
      {"intensity", obj.intensity},
      {"orbit", obj.orbit},
      {"orbit_rms", obj.orbit_rms},
      {"init_orbit", obj.init_orbit},
      {"init_orbit_rms", obj.init_orbit_rms}};
}

ostream& operator<<(ostream& os, const CPP_pixel_pt& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_pixel_detec& obj) {
  j = json{
      {"dr", obj.dr},
      {"r0", obj.r0},
      {"n_track_tot", obj.n_track_tot},
      {"n_hit_detec", obj.n_hit_detec},
      {"n_hit_pixel", obj.n_hit_pixel},
      {"pt", obj.pt}};
}

ostream& operator<<(ostream& os, const CPP_pixel_detec& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_photon_element& obj) {
  j = json{
      {"curvature", obj.curvature},
      {"target", obj.target},
      {"material", obj.material},
      {"segmented", obj.segmented},
      {"h_misalign", obj.h_misalign},
      {"displacement", obj.displacement},
      {"pixel", obj.pixel},
      {"reflectivity_table_type", obj.reflectivity_table_type},
      {"reflectivity_table_sigma", obj.reflectivity_table_sigma},
      {"reflectivity_table_pi", obj.reflectivity_table_pi},
      {"init_energy_prob", obj.init_energy_prob},
      {"integrated_init_energy_prob", obj.integrated_init_energy_prob}};
}

ostream& operator<<(ostream& os, const CPP_photon_element& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wall3d_vertex& obj) {
  j = json{
      {"x", obj.x},
      {"y", obj.y},
      {"radius_x", obj.radius_x},
      {"radius_y", obj.radius_y},
      {"tilt", obj.tilt},
      {"angle", obj.angle},
      {"x0", obj.x0},
      {"y0", obj.y0},
      {"type", obj.type}};
}

ostream& operator<<(ostream& os, const CPP_wall3d_vertex& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wall3d_section& obj) {
  j = json{
      {"name", obj.name},
      {"material", obj.material},
      {"v", obj.v},
      {"surface", obj.surface},
      {"type", obj.type},
      {"n_vertex_input", obj.n_vertex_input},
      {"ix_ele", obj.ix_ele},
      {"ix_branch", obj.ix_branch},
      {"vertices_state", obj.vertices_state},
      {"patch_in_region", obj.patch_in_region},
      {"thickness", obj.thickness},
      {"s", obj.s},
      {"r0", obj.r0},
      {"dx0_ds", obj.dx0_ds},
      {"dy0_ds", obj.dy0_ds},
      {"x0_coef", obj.x0_coef},
      {"y0_coef", obj.y0_coef},
      {"dr_ds", obj.dr_ds},
      {"p1_coef", obj.p1_coef},
      {"p2_coef", obj.p2_coef}};
}

ostream& operator<<(ostream& os, const CPP_wall3d_section& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_wall3d& obj) {
  j = json{
      {"name", obj.name},
      {"type", obj.type},
      {"ix_wall3d", obj.ix_wall3d},
      {"n_link", obj.n_link},
      {"thickness", obj.thickness},
      {"clear_material", obj.clear_material},
      {"opaque_material", obj.opaque_material},
      {"superimpose", obj.superimpose},
      {"ele_anchor_pt", obj.ele_anchor_pt},
      {"section", obj.section}};
}

ostream& operator<<(ostream& os, const CPP_wall3d& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ramper_lord& obj) {
  j = json{
      {"ix_ele", obj.ix_ele},
      {"ix_con", obj.ix_con},
      {"attrib_ptr", obj.attrib_ptr}};
}

ostream& operator<<(ostream& os, const CPP_ramper_lord& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_control& obj) {
  j = json{
      {"value", obj.value},
      {"y_knot", obj.y_knot},
      {"stack", obj.stack},
      {"slave", obj.slave},
      {"lord", obj.lord},
      {"slave_name", obj.slave_name},
      {"attribute", obj.attribute},
      {"ix_attrib", obj.ix_attrib}};
}

ostream& operator<<(ostream& os, const CPP_control& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_control_var1& obj) {
  j = json{
      {"name", obj.name}, {"value", obj.value}, {"old_value", obj.old_value}};
}

ostream& operator<<(ostream& os, const CPP_control_var1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_control_ramp1& obj) {
  j = json{
      {"y_knot", obj.y_knot},
      {"stack", obj.stack},
      {"attribute", obj.attribute},
      {"slave_name", obj.slave_name},
      {"is_controller", obj.is_controller}};
}

ostream& operator<<(ostream& os, const CPP_control_ramp1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_controller& obj) {
  j = json{
      {"var", obj.var},
      {"ramp", obj.ramp},
      {"ramper_lord", obj.ramper_lord},
      {"x_knot", obj.x_knot}};
}

ostream& operator<<(ostream& os, const CPP_controller& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ellipse_beam_init& obj) {
  j = json{
      {"part_per_ellipse", obj.part_per_ellipse},
      {"n_ellipse", obj.n_ellipse},
      {"sigma_cutoff", obj.sigma_cutoff}};
}

ostream& operator<<(ostream& os, const CPP_ellipse_beam_init& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_kv_beam_init& obj) {
  j = json{
      {"part_per_phi", obj.part_per_phi}, {"n_I2", obj.n_I2}, {"A", obj.A}};
}

ostream& operator<<(ostream& os, const CPP_kv_beam_init& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_grid_beam_init& obj) {
  j = json{
      {"n_x", obj.n_x},
      {"n_px", obj.n_px},
      {"x_min", obj.x_min},
      {"x_max", obj.x_max},
      {"px_min", obj.px_min},
      {"px_max", obj.px_max}};
}

ostream& operator<<(ostream& os, const CPP_grid_beam_init& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_beam_init& obj) {
  j = json{
      {"position_file", obj.position_file},
      {"distribution_type", obj.distribution_type},
      {"spin", obj.spin},
      {"ellipse", obj.ellipse},
      {"KV", obj.KV},
      {"grid", obj.grid},
      {"center_jitter", obj.center_jitter},
      {"emit_jitter", obj.emit_jitter},
      {"sig_z_jitter", obj.sig_z_jitter},
      {"sig_pz_jitter", obj.sig_pz_jitter},
      {"n_particle", obj.n_particle},
      {"renorm_center", obj.renorm_center},
      {"renorm_sigma", obj.renorm_sigma},
      {"random_engine", obj.random_engine},
      {"random_gauss_converter", obj.random_gauss_converter},
      {"random_sigma_cutoff", obj.random_sigma_cutoff},
      {"a_norm_emit", obj.a_norm_emit},
      {"b_norm_emit", obj.b_norm_emit},
      {"a_emit", obj.a_emit},
      {"b_emit", obj.b_emit},
      {"dPz_dz", obj.dPz_dz},
      {"center", obj.center},
      {"t_offset", obj.t_offset},
      {"dt_bunch", obj.dt_bunch},
      {"sig_z", obj.sig_z},
      {"sig_pz", obj.sig_pz},
      {"bunch_charge", obj.bunch_charge},
      {"n_bunch", obj.n_bunch},
      {"ix_turn", obj.ix_turn},
      {"species", obj.species},
      {"full_6D_coupling_calc", obj.full_6D_coupling_calc},
      {"use_particle_start", obj.use_particle_start},
      {"use_t_coords", obj.use_t_coords},
      {"use_z_as_t", obj.use_z_as_t},
      {"file_name", obj.file_name}};
}

ostream& operator<<(ostream& os, const CPP_beam_init& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_lat_param& obj) {
  j = json{
      {"n_part", obj.n_part},
      {"total_length", obj.total_length},
      {"unstable_factor", obj.unstable_factor},
      {"t1_with_RF", obj.t1_with_RF},
      {"t1_no_RF", obj.t1_no_RF},
      {"spin_tune", obj.spin_tune},
      {"particle", obj.particle},
      {"default_tracking_species", obj.default_tracking_species},
      {"geometry", obj.geometry},
      {"ixx", obj.ixx},
      {"stable", obj.stable},
      {"live_branch", obj.live_branch},
      {"g1_integral", obj.g1_integral},
      {"g2_integral", obj.g2_integral},
      {"g3_integral", obj.g3_integral},
      {"bookkeeping_state", obj.bookkeeping_state},
      {"beam_init", obj.beam_init}};
}

ostream& operator<<(ostream& os, const CPP_lat_param& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_mode_info& obj) {
  j = json{
      {"stable", obj.stable},
      {"tune", obj.tune},
      {"emit", obj.emit},
      {"chrom", obj.chrom},
      {"sigma", obj.sigma},
      {"sigmap", obj.sigmap}};
}

ostream& operator<<(ostream& os, const CPP_mode_info& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_pre_tracker& obj) {
  j = json{
      {"who", obj.who},
      {"ix_ele_start", obj.ix_ele_start},
      {"ix_ele_end", obj.ix_ele_end},
      {"input_file", obj.input_file}};
}

ostream& operator<<(ostream& os, const CPP_pre_tracker& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_anormal_mode& obj) {
  j = json{
      {"emittance", obj.emittance},
      {"emittance_no_vert", obj.emittance_no_vert},
      {"synch_int", obj.synch_int},
      {"j_damp", obj.j_damp},
      {"alpha_damp", obj.alpha_damp},
      {"chrom", obj.chrom},
      {"tune", obj.tune}};
}

ostream& operator<<(ostream& os, const CPP_anormal_mode& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_linac_normal_mode& obj) {
  j = json{
      {"i2_E4", obj.i2_E4},
      {"i3_E7", obj.i3_E7},
      {"i5a_E6", obj.i5a_E6},
      {"i5b_E6", obj.i5b_E6},
      {"sig_E1", obj.sig_E1},
      {"a_emittance_end", obj.a_emittance_end},
      {"b_emittance_end", obj.b_emittance_end}};
}

ostream& operator<<(ostream& os, const CPP_linac_normal_mode& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_normal_modes& obj) {
  j = json{
      {"synch_int", obj.synch_int},
      {"sigE_E", obj.sigE_E},
      {"sig_z", obj.sig_z},
      {"e_loss", obj.e_loss},
      {"rf_voltage", obj.rf_voltage},
      {"pz_aperture", obj.pz_aperture},
      {"pz_average", obj.pz_average},
      {"momentum_compaction", obj.momentum_compaction},
      {"dpz_damp", obj.dpz_damp},
      {"a", obj.a},
      {"b", obj.b},
      {"z", obj.z},
      {"lin", obj.lin}};
}

ostream& operator<<(ostream& os, const CPP_normal_modes& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_em_field& obj) {
  j = json{
      {"E", obj.E},
      {"B", obj.B},
      {"dE", obj.dE},
      {"dB", obj.dB},
      {"phi", obj.phi},
      {"phi_B", obj.phi_B},
      {"A", obj.A}};
}

ostream& operator<<(ostream& os, const CPP_em_field& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_strong_beam& obj) {
  j = json{
      {"ix_slice", obj.ix_slice},
      {"x_center", obj.x_center},
      {"y_center", obj.y_center},
      {"x_sigma", obj.x_sigma},
      {"y_sigma", obj.y_sigma},
      {"dx", obj.dx},
      {"dy", obj.dy}};
}

ostream& operator<<(ostream& os, const CPP_strong_beam& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_track_point& obj) {
  j = json{
      {"s_body", obj.s_body},
      {"orb", obj.orb},
      {"field", obj.field},
      {"strong_beam", obj.strong_beam},
      {"vec0", obj.vec0},
      {"mat6", obj.mat6}};
}

ostream& operator<<(ostream& os, const CPP_track_point& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_track& obj) {
  j = json{
      {"pt", obj.pt},
      {"ds_save", obj.ds_save},
      {"n_pt", obj.n_pt},
      {"n_bad", obj.n_bad},
      {"n_ok", obj.n_ok}};
}

ostream& operator<<(ostream& os, const CPP_track& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_space_charge_common& obj) {
  j = json{
      {"ds_track_step", obj.ds_track_step},
      {"dt_track_step", obj.dt_track_step},
      {"cathode_strength_cutoff", obj.cathode_strength_cutoff},
      {"rel_tol_tracking", obj.rel_tol_tracking},
      {"abs_tol_tracking", obj.abs_tol_tracking},
      {"beam_chamber_height", obj.beam_chamber_height},
      {"lsc_sigma_cutoff", obj.lsc_sigma_cutoff},
      {"particle_sigma_cutoff", obj.particle_sigma_cutoff},
      {"space_charge_mesh_size", obj.space_charge_mesh_size},
      {"csr3d_mesh_size", obj.csr3d_mesh_size},
      {"n_bin", obj.n_bin},
      {"particle_bin_span", obj.particle_bin_span},
      {"n_shield_images", obj.n_shield_images},
      {"sc_min_in_bin", obj.sc_min_in_bin},
      {"lsc_kick_transverse_dependence", obj.lsc_kick_transverse_dependence},
      {"debug", obj.debug},
      {"diagnostic_output_file", obj.diagnostic_output_file}};
}

ostream& operator<<(ostream& os, const CPP_space_charge_common& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_bmad_common& obj) {
  j = json{
      {"max_aperture_limit", obj.max_aperture_limit},
      {"d_orb", obj.d_orb},
      {"default_ds_step", obj.default_ds_step},
      {"significant_length", obj.significant_length},
      {"rel_tol_tracking", obj.rel_tol_tracking},
      {"abs_tol_tracking", obj.abs_tol_tracking},
      {"rel_tol_adaptive_tracking", obj.rel_tol_adaptive_tracking},
      {"abs_tol_adaptive_tracking", obj.abs_tol_adaptive_tracking},
      {"init_ds_adaptive_tracking", obj.init_ds_adaptive_tracking},
      {"min_ds_adaptive_tracking", obj.min_ds_adaptive_tracking},
      {"fatal_ds_adaptive_tracking", obj.fatal_ds_adaptive_tracking},
      {"autoscale_amp_abs_tol", obj.autoscale_amp_abs_tol},
      {"autoscale_amp_rel_tol", obj.autoscale_amp_rel_tol},
      {"autoscale_phase_tol", obj.autoscale_phase_tol},
      {"electric_dipole_moment", obj.electric_dipole_moment},
      {"synch_rad_scale", obj.synch_rad_scale},
      {"sad_eps_scale", obj.sad_eps_scale},
      {"sad_amp_max", obj.sad_amp_max},
      {"sad_n_div_max", obj.sad_n_div_max},
      {"taylor_order", obj.taylor_order},
      {"runge_kutta_order", obj.runge_kutta_order},
      {"default_integ_order", obj.default_integ_order},
      {"max_num_runge_kutta_step", obj.max_num_runge_kutta_step},
      {"rf_phase_below_transition_ref", obj.rf_phase_below_transition_ref},
      {"sr_wakes_on", obj.sr_wakes_on},
      {"lr_wakes_on", obj.lr_wakes_on},
      {"auto_bookkeeper", obj.auto_bookkeeper},
      {"high_energy_space_charge_on", obj.high_energy_space_charge_on},
      {"csr_and_space_charge_on", obj.csr_and_space_charge_on},
      {"spin_tracking_on", obj.spin_tracking_on},
      {"spin_sokolov_ternov_flipping_on", obj.spin_sokolov_ternov_flipping_on},
      {"radiation_damping_on", obj.radiation_damping_on},
      {"radiation_zero_average", obj.radiation_zero_average},
      {"radiation_fluctuations_on", obj.radiation_fluctuations_on},
      {"conserve_taylor_maps", obj.conserve_taylor_maps},
      {"absolute_time_tracking", obj.absolute_time_tracking},
      {"absolute_time_ref_shift", obj.absolute_time_ref_shift},
      {"convert_to_kinetic_momentum", obj.convert_to_kinetic_momentum},
      {"aperture_limit_on", obj.aperture_limit_on},
      {"debug", obj.debug}};
}

ostream& operator<<(ostream& os, const CPP_bmad_common& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_rad_int1& obj) {
  j = json{
      {"i0", obj.i0},
      {"i1", obj.i1},
      {"i2", obj.i2},
      {"i3", obj.i3},
      {"i4a", obj.i4a},
      {"i4b", obj.i4b},
      {"i4z", obj.i4z},
      {"i5a", obj.i5a},
      {"i5b", obj.i5b},
      {"i6b", obj.i6b},
      {"lin_i2_E4", obj.lin_i2_E4},
      {"lin_i3_E7", obj.lin_i3_E7},
      {"lin_i5a_E6", obj.lin_i5a_E6},
      {"lin_i5b_E6", obj.lin_i5b_E6},
      {"lin_norm_emit_a", obj.lin_norm_emit_a},
      {"lin_norm_emit_b", obj.lin_norm_emit_b},
      {"lin_sig_E", obj.lin_sig_E},
      {"n_steps", obj.n_steps}};
}

ostream& operator<<(ostream& os, const CPP_rad_int1& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_rad_int_branch& obj) {
  j = json{{"ele", obj.ele}};
}

ostream& operator<<(ostream& os, const CPP_rad_int_branch& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_rad_int_all_ele& obj) {
  j = json{{"branch", obj.branch}};
}

ostream& operator<<(ostream& os, const CPP_rad_int_all_ele& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ele_reference& obj) {
  j = json{{"ix_ele", obj.ix_ele}, {"ix_branch", obj.ix_branch}};
}

ostream& operator<<(ostream& os, const CPP_ele_reference& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_branch_reference& obj) {
  j = json{{"ix_branch", obj.ix_branch}};
}

ostream& operator<<(ostream& os, const CPP_branch_reference& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_ele& obj) {
  j = json{
      {"name", obj.name},
      {"type", obj.type},
      {"alias", obj.alias},
      {"component_name", obj.component_name},
      {"descrip", obj.descrip},
      {"a", obj.a},
      {"b", obj.b},
      {"z", obj.z},
      {"x", obj.x},
      {"y", obj.y},
      {"ac_kick", obj.ac_kick},
      {"bookkeeping_state", obj.bookkeeping_state},
      {"control", obj.control},
      {"lord", obj.lord},
      {"floor", obj.floor},
      {"high_energy_space_charge", obj.high_energy_space_charge},
      {"mode3", obj.mode3},
      {"photon", obj.photon},
      {"rad_map", obj.rad_map},
      {"taylor", obj.taylor},
      {"spin_taylor_ref_orb_in", obj.spin_taylor_ref_orb_in},
      {"spin_taylor", obj.spin_taylor},
      {"wake", obj.wake},
      {"wall3d", obj.wall3d},
      {"cartesian_map", obj.cartesian_map},
      {"cylindrical_map", obj.cylindrical_map},
      {"gen_grad_map", obj.gen_grad_map},
      {"grid_field", obj.grid_field},
      {"map_ref_orb_in", obj.map_ref_orb_in},
      {"map_ref_orb_out", obj.map_ref_orb_out},
      {"time_ref_orb_in", obj.time_ref_orb_in},
      {"time_ref_orb_out", obj.time_ref_orb_out},
      {"value", obj.value},
      {"old_value", obj.old_value},
      {"spin_q", obj.spin_q},
      {"vec0", obj.vec0},
      {"mat6", obj.mat6},
      {"c_mat", obj.c_mat},
      {"gamma_c", obj.gamma_c},
      {"s_start", obj.s_start},
      {"s", obj.s},
      {"ref_time", obj.ref_time},
      {"a_pole", obj.a_pole},
      {"b_pole", obj.b_pole},
      {"a_pole_elec", obj.a_pole_elec},
      {"b_pole_elec", obj.b_pole_elec},
      {"custom", obj.custom},
      {"r", obj.r},
      {"key", obj.key},
      {"sub_key", obj.sub_key},
      {"ix_ele", obj.ix_ele},
      {"ix_branch", obj.ix_branch},
      {"lord_status", obj.lord_status},
      {"n_slave", obj.n_slave},
      {"n_slave_field", obj.n_slave_field},
      {"ix1_slave", obj.ix1_slave},
      {"slave_status", obj.slave_status},
      {"n_lord", obj.n_lord},
      {"n_lord_field", obj.n_lord_field},
      {"n_lord_ramper", obj.n_lord_ramper},
      {"ic1_lord", obj.ic1_lord},
      {"ix_pointer", obj.ix_pointer},
      {"ixx", obj.ixx},
      {"iyy", obj.iyy},
      {"izz", obj.izz},
      {"mat6_calc_method", obj.mat6_calc_method},
      {"tracking_method", obj.tracking_method},
      {"spin_tracking_method", obj.spin_tracking_method},
      {"csr_method", obj.csr_method},
      {"space_charge_method", obj.space_charge_method},
      {"ptc_integration_type", obj.ptc_integration_type},
      {"field_calc", obj.field_calc},
      {"aperture_at", obj.aperture_at},
      {"aperture_type", obj.aperture_type},
      {"ref_species", obj.ref_species},
      {"orientation", obj.orientation},
      {"symplectify", obj.symplectify},
      {"mode_flip", obj.mode_flip},
      {"multipoles_on", obj.multipoles_on},
      {"scale_multipoles", obj.scale_multipoles},
      {"taylor_map_includes_offsets", obj.taylor_map_includes_offsets},
      {"field_master", obj.field_master},
      {"is_on", obj.is_on},
      {"logic", obj.logic},
      {"bmad_logic", obj.bmad_logic},
      {"select", obj.select},
      {"offset_moves_aperture", obj.offset_moves_aperture}};
}

ostream& operator<<(ostream& os, const CPP_ele& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_complex_taylor_term& obj) {
  j = json{{"coef", obj.coef}, {"expn", obj.expn}};
}

ostream& operator<<(ostream& os, const CPP_complex_taylor_term& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_complex_taylor& obj) {
  j = json{{"ref", obj.ref}, {"term", obj.term}};
}

ostream& operator<<(ostream& os, const CPP_complex_taylor& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_branch& obj) {
  j = json{
      {"name", obj.name},
      {"ix_branch", obj.ix_branch},
      {"ix_from_branch", obj.ix_from_branch},
      {"ix_from_ele", obj.ix_from_ele},
      {"ix_to_ele", obj.ix_to_ele},
      {"n_ele_track", obj.n_ele_track},
      {"n_ele_max", obj.n_ele_max},
      {"a", obj.a},
      {"b", obj.b},
      {"z", obj.z},
      {"ele", obj.ele},
      {"param", obj.param},
      {"wall3d", obj.wall3d}};
}

ostream& operator<<(ostream& os, const CPP_branch& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_lat& obj) {
  j = json{
      {"use_name", obj.use_name},
      {"lattice", obj.lattice},
      {"machine", obj.machine},
      {"input_file_name", obj.input_file_name},
      {"title", obj.title},
      {"print_str", obj.print_str},
      {"constant", obj.constant},
      {"a", obj.a},
      {"b", obj.b},
      {"z", obj.z},
      {"param", obj.param},
      {"lord_state", obj.lord_state},
      {"ele_init", obj.ele_init},
      {"ele", obj.ele},
      {"branch", obj.branch},
      {"control", obj.control},
      {"particle_start", obj.particle_start},
      {"beam_init", obj.beam_init},
      {"pre_tracker", obj.pre_tracker},
      {"custom", obj.custom},
      {"version", obj.version},
      {"n_ele_track", obj.n_ele_track},
      {"n_ele_max", obj.n_ele_max},
      {"n_control_max", obj.n_control_max},
      {"n_ic_max", obj.n_ic_max},
      {"input_taylor_order", obj.input_taylor_order},
      {"ic", obj.ic},
      {"photon_type", obj.photon_type},
      {"creation_hash", obj.creation_hash},
      {"ramper_slave_bookkeeping", obj.ramper_slave_bookkeeping}};
}

ostream& operator<<(ostream& os, const CPP_lat& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_bunch& obj) {
  j = json{
      {"particle", obj.particle},
      {"ix_z", obj.ix_z},
      {"charge_tot", obj.charge_tot},
      {"charge_live", obj.charge_live},
      {"z_center", obj.z_center},
      {"t_center", obj.t_center},
      {"t0", obj.t0},
      {"drift_between_t_and_s", obj.drift_between_t_and_s},
      {"ix_ele", obj.ix_ele},
      {"ix_bunch", obj.ix_bunch},
      {"ix_turn", obj.ix_turn},
      {"n_live", obj.n_live},
      {"n_good", obj.n_good},
      {"n_bad", obj.n_bad}};
}

ostream& operator<<(ostream& os, const CPP_bunch& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_bunch_params& obj) {
  j = json{
      {"centroid", obj.centroid},
      {"x", obj.x},
      {"y", obj.y},
      {"z", obj.z},
      {"a", obj.a},
      {"b", obj.b},
      {"c", obj.c},
      {"sigma", obj.sigma},
      {"rel_max", obj.rel_max},
      {"rel_min", obj.rel_min},
      {"s", obj.s},
      {"t", obj.t},
      {"sigma_t", obj.sigma_t},
      {"charge_live", obj.charge_live},
      {"charge_tot", obj.charge_tot},
      {"n_particle_tot", obj.n_particle_tot},
      {"n_particle_live", obj.n_particle_live},
      {"n_particle_lost_in_ele", obj.n_particle_lost_in_ele},
      {"n_good_steps", obj.n_good_steps},
      {"n_bad_steps", obj.n_bad_steps},
      {"ix_ele", obj.ix_ele},
      {"location", obj.location},
      {"twiss_valid", obj.twiss_valid}};
}

ostream& operator<<(ostream& os, const CPP_bunch_params& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_beam& obj) {
  j = json{{"bunch", obj.bunch}};
}

ostream& operator<<(ostream& os, const CPP_beam& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_aperture_point& obj) {
  j = json{
      {"x", obj.x},
      {"y", obj.y},
      {"plane", obj.plane},
      {"ix_ele", obj.ix_ele},
      {"i_turn", obj.i_turn}};
}

ostream& operator<<(ostream& os, const CPP_aperture_point& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_aperture_param& obj) {
  j = json{
      {"min_angle", obj.min_angle},
      {"max_angle", obj.max_angle},
      {"n_angle", obj.n_angle},
      {"n_turn", obj.n_turn},
      {"x_init", obj.x_init},
      {"y_init", obj.y_init},
      {"rel_accuracy", obj.rel_accuracy},
      {"abs_accuracy", obj.abs_accuracy},
      {"start_ele", obj.start_ele}};
}

ostream& operator<<(ostream& os, const CPP_aperture_param& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

void to_json(json& j, const CPP_aperture_scan& obj) {
  j = json{
      {"point", obj.point},
      {"ref_orb", obj.ref_orb},
      {"pz_start", obj.pz_start}};
}

ostream& operator<<(ostream& os, const CPP_aperture_scan& obj) {
  json j;
  to_json(j, obj);
  std::string str = nlohmann::to_string(j);
  os << str;
  return os;
}

//--------------------------------------------------------------------
} // namespace Bmad
