//+
// C++ side of the Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY!
//-

#include "converter_templates.h"
#include "cpp_bmad_classes.h"
#include <iostream>
#include <sstream>

using namespace Bmad;

//--------------------------------------------------------------------
//--------------------------------------------------------------------
// CPP_wake_lr

extern "C" void wake_lr_to_c (const Opaque_wake_lr_class*, CPP_wake_lr&);

// c_side.to_f2_arg
extern "C" void wake_lr_to_f2 (Opaque_wake_lr_class*, c_Int8&, c_Int&, c_Char, c_Real&,
    c_Real&);

extern "C" void wake_lr_to_f (const CPP_wake_lr& C, Opaque_wake_lr_class* F) {

  // c_side.to_f2_call
  wake_lr_to_f2 (F, C.aaa, C.bbb, C.file.c_str(), C.t_ref, C.freq_spread);

}

// c_side.to_c2_arg
extern "C" void wake_lr_to_c2 (CPP_wake_lr& C, c_Int8& z_aaa, c_Int& z_bbb, c_Char z_file,
    c_Real& z_t_ref, c_Real& z_freq_spread) {

  // c_side.to_c2_set[integer8, 0, NOT] Int8
  C.aaa = z_aaa;
  // c_side.to_c2_set[integer, 0, NOT] Int
  C.bbb = z_bbb;
  // c_side.to_c2_set[character, 0, NOT] string
  C.file = z_file;
  // c_side.to_c2_set[real, 0, NOT] Real
  C.t_ref = z_t_ref;
  // c_side.to_c2_set[real, 0, NOT] Real
  C.freq_spread = z_freq_spread;
}

//--------------------------------------------------------------------
//--------------------------------------------------------------------
// CPP_wake

extern "C" void wake_to_c (const Opaque_wake_class*, CPP_wake&);

// c_side.to_f2_arg
extern "C" void wake_to_f2 (Opaque_wake_class*, const CPP_wake_lr&);

extern "C" void wake_to_f (const CPP_wake& C, Opaque_wake_class* F) {

  // c_side.to_f2_call
  wake_to_f2 (F, C.sr);

}

// c_side.to_c2_arg
extern "C" void wake_to_c2 (CPP_wake& C, const Opaque_wake_lr_class* z_sr) {

  // c_side.to_c2_set[type, 0, NOT] CPP_wake_lr
  wake_lr_to_c(z_sr, C.sr);
}

//--------------------------------------------------------------------
//--------------------------------------------------------------------
// CPP_all_encompassing

extern "C" void all_encompassing_to_c (const Opaque_all_encompassing_class*, CPP_all_encompassing&);

// c_side.to_f2_arg
extern "C" void all_encompassing_to_f2 (Opaque_all_encompassing_class*, c_Real&, c_RealArr,
    c_RealArr, c_RealArr, c_RealArr, Int, c_RealArr, Int, c_RealArr, Int, Int, c_RealArr, Int,
    Int, Int, c_RealArr, Int, c_RealArr, Int, Int, c_RealArr, Int, Int, Int, c_Real&,
    c_RealArr, c_RealArr, c_RealArr, c_RealArr, Int, c_RealArr, Int, c_RealArr, Int, Int,
    c_RealArr, Int, Int, Int, c_RealArr, Int, c_RealArr, Int, Int, c_RealArr, Int, Int, Int,
    c_Complex&, c_ComplexArr, c_ComplexArr, c_ComplexArr, c_ComplexArr, Int, c_ComplexArr, Int,
    c_ComplexArr, Int, Int, c_ComplexArr, Int, Int, Int, c_ComplexArr, Int, c_ComplexArr, Int,
    Int, c_ComplexArr, Int, Int, Int, c_Int&, c_IntArr, c_IntArr, c_IntArr, c_IntArr, Int,
    c_IntArr, Int, c_IntArr, Int, Int, c_IntArr, Int, Int, Int, c_IntArr, Int, c_IntArr, Int,
    Int, c_IntArr, Int, Int, Int, c_Int8&, c_Int8Arr, c_Int8Arr, c_Int8Arr, c_Int8Arr, Int,
    c_Int8Arr, Int, c_Int8Arr, Int, Int, c_Int8Arr, Int, Int, Int, c_Int8Arr, Int, c_Int8Arr,
    Int, Int, c_Int8Arr, Int, Int, Int, c_Bool&, c_BoolArr, c_BoolArr, c_BoolArr, c_BoolArr,
    Int, const CPP_wake_lr&, const CPP_wake_lr**, const CPP_wake_lr**, const CPP_wake_lr**,
    const CPP_wake_lr&, Int, const CPP_wake_lr**, Int, const CPP_wake_lr**, Int, Int, const
    CPP_wake_lr**, Int, Int, Int, const CPP_wake_lr**, Int, const CPP_wake_lr**, Int, Int,
    const CPP_wake_lr**, Int, Int, Int);

extern "C" void all_encompassing_to_f (const CPP_all_encompassing& C, Opaque_all_encompassing_class* F) {
  // c_side.to_f_setup[real, 2, NOT] FixedArray2D<Real, 3, 4>
  Real z_real_rp_2d[3*4]; matrix_to_vec(C.real_rp_2d, z_real_rp_2d);
  // c_side.to_f_setup[real, 3, NOT] FixedArray3D<Real, 3, 4, 5>
  Real z_real_rp_3d[3*4*5]; tensor_to_vec(C.real_rp_3d, z_real_rp_3d);
  // c_side.to_f_setup[real, 0, PTR] shared_ptr<Real>
  size_t n_real_rp_0d_ptr = 0; if (C.real_rp_0d_ptr != nullptr) n_real_rp_0d_ptr = 1;
  // c_side.to_f_setup[real, 1, PTR] VariableArray1D<Real>
  auto n1_real_rp_1d_ptr = C.real_rp_1d_ptr.size();
  c_RealArr z_real_rp_1d_ptr = nullptr;
  if (n1_real_rp_1d_ptr > 0) {
    z_real_rp_1d_ptr = &C.real_rp_1d_ptr[0];
  }
  // c_side.to_f_setup[real, 2, PTR] VariableArray2D<Real>
  auto n1_real_rp_2d_ptr { C.real_rp_2d_ptr.size() };
  auto n2_real_rp_2d_ptr { std::size_t{0} };
  Real* z_real_rp_2d_ptr = nullptr;
  if (n1_real_rp_2d_ptr > 0) {
    n2_real_rp_2d_ptr = C.real_rp_2d_ptr[0].size();
    z_real_rp_2d_ptr = new Real [n1_real_rp_2d_ptr*n2_real_rp_2d_ptr];
    matrix_to_vec (C.real_rp_2d_ptr, z_real_rp_2d_ptr);
  }
  // c_side.to_f_setup[real, 3, PTR] VariableArray3D<Real>

  auto n1_real_rp_3d_ptr { C.real_rp_3d_ptr.size() };
  auto n2_real_rp_3d_ptr { std::size_t{0} };
  auto n3_real_rp_3d_ptr { std::size_t{0} };
  Real* z_real_rp_3d_ptr { nullptr };
  if (n1_real_rp_3d_ptr > 0) {
    n2_real_rp_3d_ptr = C.real_rp_3d_ptr[0].size();
    n3_real_rp_3d_ptr = C.real_rp_3d_ptr[0][0].size();
    z_real_rp_3d_ptr = new Real [C.real_rp_3d_ptr.size()*C.real_rp_3d_ptr[0].size()*C.real_rp_3d_ptr[0][0].size()];
    tensor_to_vec (C.real_rp_3d_ptr, z_real_rp_3d_ptr);
  }
  // c_side.to_f_setup[real, 1, ALLOC] VariableArray1D<Real>
  auto n1_real_rp_1d_alloc = C.real_rp_1d_alloc.size();
  c_RealArr z_real_rp_1d_alloc = nullptr;
  if (n1_real_rp_1d_alloc > 0) {
    z_real_rp_1d_alloc = &C.real_rp_1d_alloc[0];
  }
  // c_side.to_f_setup[real, 2, ALLOC] VariableArray2D<Real>
  auto n1_real_rp_2d_alloc { C.real_rp_2d_alloc.size() };
  auto n2_real_rp_2d_alloc { std::size_t{0} };
  Real* z_real_rp_2d_alloc = nullptr;
  if (n1_real_rp_2d_alloc > 0) {
    n2_real_rp_2d_alloc = C.real_rp_2d_alloc[0].size();
    z_real_rp_2d_alloc = new Real [n1_real_rp_2d_alloc*n2_real_rp_2d_alloc];
    matrix_to_vec (C.real_rp_2d_alloc, z_real_rp_2d_alloc);
  }
  // c_side.to_f_setup[real, 3, ALLOC] VariableArray3D<Real>

  auto n1_real_rp_3d_alloc { C.real_rp_3d_alloc.size() };
  auto n2_real_rp_3d_alloc { std::size_t{0} };
  auto n3_real_rp_3d_alloc { std::size_t{0} };
  Real* z_real_rp_3d_alloc { nullptr };
  if (n1_real_rp_3d_alloc > 0) {
    n2_real_rp_3d_alloc = C.real_rp_3d_alloc[0].size();
    n3_real_rp_3d_alloc = C.real_rp_3d_alloc[0][0].size();
    z_real_rp_3d_alloc = new Real [C.real_rp_3d_alloc.size()*C.real_rp_3d_alloc[0].size()*C.real_rp_3d_alloc[0][0].size()];
    tensor_to_vec (C.real_rp_3d_alloc, z_real_rp_3d_alloc);
  }
  // c_side.to_f_setup[real, 2, NOT] FixedArray2D<Real, 3, 4>
  Real z_real_dp_2d[3*4]; matrix_to_vec(C.real_dp_2d, z_real_dp_2d);
  // c_side.to_f_setup[real, 3, NOT] FixedArray3D<Real, 3, 4, 5>
  Real z_real_dp_3d[3*4*5]; tensor_to_vec(C.real_dp_3d, z_real_dp_3d);
  // c_side.to_f_setup[real, 0, PTR] shared_ptr<Real>
  size_t n_real_dp_0d_ptr = 0; if (C.real_dp_0d_ptr != nullptr) n_real_dp_0d_ptr = 1;
  // c_side.to_f_setup[real, 1, PTR] VariableArray1D<Real>
  auto n1_real_dp_1d_ptr = C.real_dp_1d_ptr.size();
  c_RealArr z_real_dp_1d_ptr = nullptr;
  if (n1_real_dp_1d_ptr > 0) {
    z_real_dp_1d_ptr = &C.real_dp_1d_ptr[0];
  }
  // c_side.to_f_setup[real, 2, PTR] VariableArray2D<Real>
  auto n1_real_dp_2d_ptr { C.real_dp_2d_ptr.size() };
  auto n2_real_dp_2d_ptr { std::size_t{0} };
  Real* z_real_dp_2d_ptr = nullptr;
  if (n1_real_dp_2d_ptr > 0) {
    n2_real_dp_2d_ptr = C.real_dp_2d_ptr[0].size();
    z_real_dp_2d_ptr = new Real [n1_real_dp_2d_ptr*n2_real_dp_2d_ptr];
    matrix_to_vec (C.real_dp_2d_ptr, z_real_dp_2d_ptr);
  }
  // c_side.to_f_setup[real, 3, PTR] VariableArray3D<Real>

  auto n1_real_dp_3d_ptr { C.real_dp_3d_ptr.size() };
  auto n2_real_dp_3d_ptr { std::size_t{0} };
  auto n3_real_dp_3d_ptr { std::size_t{0} };
  Real* z_real_dp_3d_ptr { nullptr };
  if (n1_real_dp_3d_ptr > 0) {
    n2_real_dp_3d_ptr = C.real_dp_3d_ptr[0].size();
    n3_real_dp_3d_ptr = C.real_dp_3d_ptr[0][0].size();
    z_real_dp_3d_ptr = new Real [C.real_dp_3d_ptr.size()*C.real_dp_3d_ptr[0].size()*C.real_dp_3d_ptr[0][0].size()];
    tensor_to_vec (C.real_dp_3d_ptr, z_real_dp_3d_ptr);
  }
  // c_side.to_f_setup[real, 1, ALLOC] VariableArray1D<Real>
  auto n1_real_dp_1d_alloc = C.real_dp_1d_alloc.size();
  c_RealArr z_real_dp_1d_alloc = nullptr;
  if (n1_real_dp_1d_alloc > 0) {
    z_real_dp_1d_alloc = &C.real_dp_1d_alloc[0];
  }
  // c_side.to_f_setup[real, 2, ALLOC] VariableArray2D<Real>
  auto n1_real_dp_2d_alloc { C.real_dp_2d_alloc.size() };
  auto n2_real_dp_2d_alloc { std::size_t{0} };
  Real* z_real_dp_2d_alloc = nullptr;
  if (n1_real_dp_2d_alloc > 0) {
    n2_real_dp_2d_alloc = C.real_dp_2d_alloc[0].size();
    z_real_dp_2d_alloc = new Real [n1_real_dp_2d_alloc*n2_real_dp_2d_alloc];
    matrix_to_vec (C.real_dp_2d_alloc, z_real_dp_2d_alloc);
  }
  // c_side.to_f_setup[real, 3, ALLOC] VariableArray3D<Real>

  auto n1_real_dp_3d_alloc { C.real_dp_3d_alloc.size() };
  auto n2_real_dp_3d_alloc { std::size_t{0} };
  auto n3_real_dp_3d_alloc { std::size_t{0} };
  Real* z_real_dp_3d_alloc { nullptr };
  if (n1_real_dp_3d_alloc > 0) {
    n2_real_dp_3d_alloc = C.real_dp_3d_alloc[0].size();
    n3_real_dp_3d_alloc = C.real_dp_3d_alloc[0][0].size();
    z_real_dp_3d_alloc = new Real [C.real_dp_3d_alloc.size()*C.real_dp_3d_alloc[0].size()*C.real_dp_3d_alloc[0][0].size()];
    tensor_to_vec (C.real_dp_3d_alloc, z_real_dp_3d_alloc);
  }
  // c_side.to_f_setup[complex, 2, NOT] FixedArray2D<Complex, 3, 4>
  Complex z_complex_dp_2d[3*4]; matrix_to_vec(C.complex_dp_2d, z_complex_dp_2d);
  // c_side.to_f_setup[complex, 3, NOT] FixedArray3D<Complex, 3, 4, 5>
  Complex z_complex_dp_3d[3*4*5]; tensor_to_vec(C.complex_dp_3d, z_complex_dp_3d);
  // c_side.to_f_setup[complex, 0, PTR] shared_ptr<Complex>
  size_t n_complex_dp_0d_ptr = 0; if (C.complex_dp_0d_ptr != nullptr) n_complex_dp_0d_ptr = 1;
  // c_side.to_f_setup[complex, 1, PTR] VariableArray1D<Complex>
  auto n1_complex_dp_1d_ptr = C.complex_dp_1d_ptr.size();
  c_ComplexArr z_complex_dp_1d_ptr = nullptr;
  if (n1_complex_dp_1d_ptr > 0) {
    z_complex_dp_1d_ptr = &C.complex_dp_1d_ptr[0];
  }
  // c_side.to_f_setup[complex, 2, PTR] VariableArray2D<Complex>
  auto n1_complex_dp_2d_ptr { C.complex_dp_2d_ptr.size() };
  auto n2_complex_dp_2d_ptr { std::size_t{0} };
  Complex* z_complex_dp_2d_ptr = nullptr;
  if (n1_complex_dp_2d_ptr > 0) {
    n2_complex_dp_2d_ptr = C.complex_dp_2d_ptr[0].size();
    z_complex_dp_2d_ptr = new Complex [n1_complex_dp_2d_ptr*n2_complex_dp_2d_ptr];
    matrix_to_vec (C.complex_dp_2d_ptr, z_complex_dp_2d_ptr);
  }
  // c_side.to_f_setup[complex, 3, PTR] VariableArray3D<Complex>

  auto n1_complex_dp_3d_ptr { C.complex_dp_3d_ptr.size() };
  auto n2_complex_dp_3d_ptr { std::size_t{0} };
  auto n3_complex_dp_3d_ptr { std::size_t{0} };
  Complex* z_complex_dp_3d_ptr { nullptr };
  if (n1_complex_dp_3d_ptr > 0) {
    n2_complex_dp_3d_ptr = C.complex_dp_3d_ptr[0].size();
    n3_complex_dp_3d_ptr = C.complex_dp_3d_ptr[0][0].size();
    z_complex_dp_3d_ptr = new Complex [C.complex_dp_3d_ptr.size()*C.complex_dp_3d_ptr[0].size()*C.complex_dp_3d_ptr[0][0].size()];
    tensor_to_vec (C.complex_dp_3d_ptr, z_complex_dp_3d_ptr);
  }
  // c_side.to_f_setup[complex, 1, ALLOC] VariableArray1D<Complex>
  auto n1_complex_dp_1d_alloc = C.complex_dp_1d_alloc.size();
  c_ComplexArr z_complex_dp_1d_alloc = nullptr;
  if (n1_complex_dp_1d_alloc > 0) {
    z_complex_dp_1d_alloc = &C.complex_dp_1d_alloc[0];
  }
  // c_side.to_f_setup[complex, 2, ALLOC] VariableArray2D<Complex>
  auto n1_complex_dp_2d_alloc { C.complex_dp_2d_alloc.size() };
  auto n2_complex_dp_2d_alloc { std::size_t{0} };
  Complex* z_complex_dp_2d_alloc = nullptr;
  if (n1_complex_dp_2d_alloc > 0) {
    n2_complex_dp_2d_alloc = C.complex_dp_2d_alloc[0].size();
    z_complex_dp_2d_alloc = new Complex [n1_complex_dp_2d_alloc*n2_complex_dp_2d_alloc];
    matrix_to_vec (C.complex_dp_2d_alloc, z_complex_dp_2d_alloc);
  }
  // c_side.to_f_setup[complex, 3, ALLOC] VariableArray3D<Complex>

  auto n1_complex_dp_3d_alloc { C.complex_dp_3d_alloc.size() };
  auto n2_complex_dp_3d_alloc { std::size_t{0} };
  auto n3_complex_dp_3d_alloc { std::size_t{0} };
  Complex* z_complex_dp_3d_alloc { nullptr };
  if (n1_complex_dp_3d_alloc > 0) {
    n2_complex_dp_3d_alloc = C.complex_dp_3d_alloc[0].size();
    n3_complex_dp_3d_alloc = C.complex_dp_3d_alloc[0][0].size();
    z_complex_dp_3d_alloc = new Complex [C.complex_dp_3d_alloc.size()*C.complex_dp_3d_alloc[0].size()*C.complex_dp_3d_alloc[0][0].size()];
    tensor_to_vec (C.complex_dp_3d_alloc, z_complex_dp_3d_alloc);
  }
  // c_side.to_f_setup[integer, 2, NOT] FixedArray2D<Int, 3, 4>
  Int z_int_2d[3*4]; matrix_to_vec(C.int_2d, z_int_2d);
  // c_side.to_f_setup[integer, 3, NOT] FixedArray3D<Int, 3, 4, 5>
  Int z_int_3d[3*4*5]; tensor_to_vec(C.int_3d, z_int_3d);
  // c_side.to_f_setup[integer, 0, PTR] shared_ptr<Int>
  size_t n_int_0d_ptr = 0; if (C.int_0d_ptr != nullptr) n_int_0d_ptr = 1;
  // c_side.to_f_setup[integer, 1, PTR] VariableArray1D<Int>
  auto n1_int_1d_ptr = C.int_1d_ptr.size();
  c_IntArr z_int_1d_ptr = nullptr;
  if (n1_int_1d_ptr > 0) {
    z_int_1d_ptr = &C.int_1d_ptr[0];
  }
  // c_side.to_f_setup[integer, 2, PTR] VariableArray2D<Int>
  auto n1_int_2d_ptr { C.int_2d_ptr.size() };
  auto n2_int_2d_ptr { std::size_t{0} };
  Int* z_int_2d_ptr = nullptr;
  if (n1_int_2d_ptr > 0) {
    n2_int_2d_ptr = C.int_2d_ptr[0].size();
    z_int_2d_ptr = new Int [n1_int_2d_ptr*n2_int_2d_ptr];
    matrix_to_vec (C.int_2d_ptr, z_int_2d_ptr);
  }
  // c_side.to_f_setup[integer, 3, PTR] VariableArray3D<Int>

  auto n1_int_3d_ptr { C.int_3d_ptr.size() };
  auto n2_int_3d_ptr { std::size_t{0} };
  auto n3_int_3d_ptr { std::size_t{0} };
  Int* z_int_3d_ptr { nullptr };
  if (n1_int_3d_ptr > 0) {
    n2_int_3d_ptr = C.int_3d_ptr[0].size();
    n3_int_3d_ptr = C.int_3d_ptr[0][0].size();
    z_int_3d_ptr = new Int [C.int_3d_ptr.size()*C.int_3d_ptr[0].size()*C.int_3d_ptr[0][0].size()];
    tensor_to_vec (C.int_3d_ptr, z_int_3d_ptr);
  }
  // c_side.to_f_setup[integer, 1, ALLOC] VariableArray1D<Int>
  auto n1_int_1d_alloc = C.int_1d_alloc.size();
  c_IntArr z_int_1d_alloc = nullptr;
  if (n1_int_1d_alloc > 0) {
    z_int_1d_alloc = &C.int_1d_alloc[0];
  }
  // c_side.to_f_setup[integer, 2, ALLOC] VariableArray2D<Int>
  auto n1_int_2d_alloc { C.int_2d_alloc.size() };
  auto n2_int_2d_alloc { std::size_t{0} };
  Int* z_int_2d_alloc = nullptr;
  if (n1_int_2d_alloc > 0) {
    n2_int_2d_alloc = C.int_2d_alloc[0].size();
    z_int_2d_alloc = new Int [n1_int_2d_alloc*n2_int_2d_alloc];
    matrix_to_vec (C.int_2d_alloc, z_int_2d_alloc);
  }
  // c_side.to_f_setup[integer, 3, ALLOC] VariableArray3D<Int>

  auto n1_int_3d_alloc { C.int_3d_alloc.size() };
  auto n2_int_3d_alloc { std::size_t{0} };
  auto n3_int_3d_alloc { std::size_t{0} };
  Int* z_int_3d_alloc { nullptr };
  if (n1_int_3d_alloc > 0) {
    n2_int_3d_alloc = C.int_3d_alloc[0].size();
    n3_int_3d_alloc = C.int_3d_alloc[0][0].size();
    z_int_3d_alloc = new Int [C.int_3d_alloc.size()*C.int_3d_alloc[0].size()*C.int_3d_alloc[0][0].size()];
    tensor_to_vec (C.int_3d_alloc, z_int_3d_alloc);
  }
  // c_side.to_f_setup[integer8, 2, NOT] FixedArray2D<Int8, 3, 4>
  Int8 z_int8_2d[3*4]; matrix_to_vec(C.int8_2d, z_int8_2d);
  // c_side.to_f_setup[integer8, 3, NOT] FixedArray3D<Int8, 3, 4, 5>
  Int8 z_int8_3d[3*4*5]; tensor_to_vec(C.int8_3d, z_int8_3d);
  // c_side.to_f_setup[integer8, 0, PTR] shared_ptr<Int8>
  size_t n_int8_0d_ptr = 0; if (C.int8_0d_ptr != nullptr) n_int8_0d_ptr = 1;
  // c_side.to_f_setup[integer8, 1, PTR] VariableArray1D<Int8>
  auto n1_int8_1d_ptr = C.int8_1d_ptr.size();
  c_Int8Arr z_int8_1d_ptr = nullptr;
  if (n1_int8_1d_ptr > 0) {
    z_int8_1d_ptr = &C.int8_1d_ptr[0];
  }
  // c_side.to_f_setup[integer8, 2, PTR] VariableArray2D<Int8>
  auto n1_int8_2d_ptr { C.int8_2d_ptr.size() };
  auto n2_int8_2d_ptr { std::size_t{0} };
  Int8* z_int8_2d_ptr = nullptr;
  if (n1_int8_2d_ptr > 0) {
    n2_int8_2d_ptr = C.int8_2d_ptr[0].size();
    z_int8_2d_ptr = new Int8 [n1_int8_2d_ptr*n2_int8_2d_ptr];
    matrix_to_vec (C.int8_2d_ptr, z_int8_2d_ptr);
  }
  // c_side.to_f_setup[integer8, 3, PTR] VariableArray3D<Int8>

  auto n1_int8_3d_ptr { C.int8_3d_ptr.size() };
  auto n2_int8_3d_ptr { std::size_t{0} };
  auto n3_int8_3d_ptr { std::size_t{0} };
  Int8* z_int8_3d_ptr { nullptr };
  if (n1_int8_3d_ptr > 0) {
    n2_int8_3d_ptr = C.int8_3d_ptr[0].size();
    n3_int8_3d_ptr = C.int8_3d_ptr[0][0].size();
    z_int8_3d_ptr = new Int8 [C.int8_3d_ptr.size()*C.int8_3d_ptr[0].size()*C.int8_3d_ptr[0][0].size()];
    tensor_to_vec (C.int8_3d_ptr, z_int8_3d_ptr);
  }
  // c_side.to_f_setup[integer8, 1, ALLOC] VariableArray1D<Int8>
  auto n1_int8_1d_alloc = C.int8_1d_alloc.size();
  c_Int8Arr z_int8_1d_alloc = nullptr;
  if (n1_int8_1d_alloc > 0) {
    z_int8_1d_alloc = &C.int8_1d_alloc[0];
  }
  // c_side.to_f_setup[integer8, 2, ALLOC] VariableArray2D<Int8>
  auto n1_int8_2d_alloc { C.int8_2d_alloc.size() };
  auto n2_int8_2d_alloc { std::size_t{0} };
  Int8* z_int8_2d_alloc = nullptr;
  if (n1_int8_2d_alloc > 0) {
    n2_int8_2d_alloc = C.int8_2d_alloc[0].size();
    z_int8_2d_alloc = new Int8 [n1_int8_2d_alloc*n2_int8_2d_alloc];
    matrix_to_vec (C.int8_2d_alloc, z_int8_2d_alloc);
  }
  // c_side.to_f_setup[integer8, 3, ALLOC] VariableArray3D<Int8>

  auto n1_int8_3d_alloc { C.int8_3d_alloc.size() };
  auto n2_int8_3d_alloc { std::size_t{0} };
  auto n3_int8_3d_alloc { std::size_t{0} };
  Int8* z_int8_3d_alloc { nullptr };
  if (n1_int8_3d_alloc > 0) {
    n2_int8_3d_alloc = C.int8_3d_alloc[0].size();
    n3_int8_3d_alloc = C.int8_3d_alloc[0][0].size();
    z_int8_3d_alloc = new Int8 [C.int8_3d_alloc.size()*C.int8_3d_alloc[0].size()*C.int8_3d_alloc[0][0].size()];
    tensor_to_vec (C.int8_3d_alloc, z_int8_3d_alloc);
  }
  // c_side.to_f_setup[logical, 2, NOT] FixedArray2D<Bool, 3, 4>
  Bool z_logical_2d[3*4]; matrix_to_vec(C.logical_2d, z_logical_2d);
  // c_side.to_f_setup[logical, 3, NOT] FixedArray3D<Bool, 3, 4, 5>
  Bool z_logical_3d[3*4*5]; tensor_to_vec(C.logical_3d, z_logical_3d);
  // c_side.to_f_setup[logical, 0, PTR] shared_ptr<Bool>
  size_t n_logical_0d_ptr = 0; if (C.logical_0d_ptr != nullptr) n_logical_0d_ptr = 1;
  // c_side.to_f_setup[type, 1, NOT] FixedArray1D<CPP_wake_lr, 3>
  const CPP_wake_lr* z_type_1d[3];
  for (int i = 0; i < 3; i++) {z_type_1d[i] = &C.type_1d[i];}
  // c_side.to_f_setup[type, 2, NOT] SharedVector2D<CPP_wake_lr>
  const CPP_wake_lr* z_type_2d[3*4];
  for (size_t i = 0; i < C.type_2d.size(); i++)  for (size_t j = 0; j < C.type_2d[0].size(); j++) 
    {auto m = 4*i + j; z_type_2d[m] = C.type_2d[i][j].get();}
  // c_side.to_f_setup[type, 3, NOT] SharedVector3D<CPP_wake_lr>
  const CPP_wake_lr* z_type_3d[3*4*5];
  for (size_t i = 0; i < C.type_3d.size(); i++)  for (size_t j = 0; j < C.type_3d[0].size(); j++)   for (size_t k = 0; k < C.type_3d[0][0].size(); k++)
    {auto m = 5*4*i + 5*j + k; z_type_3d[m] = C.type_3d[i][j][k].get();}
  // c_side.to_f_setup[type, 0, PTR] shared_ptr<CPP_wake_lr>
  size_t n_type_0d_ptr = 0; if (C.type_0d_ptr != nullptr) n_type_0d_ptr = 1;
  // c_side.to_f_setup[type, 1, PTR] VariableArray1D<CPP_wake_lr>
  auto n1_type_1d_ptr = C.type_1d_ptr.size();
  const CPP_wake_lr** z_type_1d_ptr = nullptr;
  if (n1_type_1d_ptr != 0) {
    z_type_1d_ptr = new const CPP_wake_lr*[n1_type_1d_ptr];
    for (auto i{0}; i < n1_type_1d_ptr; i++) z_type_1d_ptr[i] = &C.type_1d_ptr[i];
  }
  // c_side.to_f_setup[type, 2, PTR] VariableArray2D<CPP_wake_lr>

  auto n1_type_2d_ptr { C.type_2d_ptr.size() };
  auto n2_type_2d_ptr { std::size_t{0} };
  const CPP_wake_lr** z_type_2d_ptr { nullptr };
  if (n1_type_2d_ptr > 0) {
    n2_type_2d_ptr = C.type_2d_ptr[0].size();
    z_type_2d_ptr = new const CPP_wake_lr* [n1_type_2d_ptr*n2_type_2d_ptr];
    for (auto i{0}; i < n1_type_2d_ptr; i++) {
      for (auto j{0}; j < n2_type_2d_ptr; j++) {
        z_type_2d_ptr[i*n2_type_2d_ptr + j] = &C.type_2d_ptr[i][j];
      }
    }
  }
  // c_side.to_f_setup[type, 3, PTR] VariableArray3D<CPP_wake_lr>

  auto n1_type_3d_ptr { C.type_3d_ptr.size() };
  auto n2_type_3d_ptr { std::size_t{0} };
  auto n3_type_3d_ptr { std::size_t{0} };
  const CPP_wake_lr** z_type_3d_ptr { nullptr };
  if (n1_type_3d_ptr > 0) {
    n2_type_3d_ptr = C.type_3d_ptr[0].size();
    n3_type_3d_ptr = C.type_3d_ptr[0][0].size();
    z_type_3d_ptr = new const CPP_wake_lr* [n1_type_3d_ptr*n2_type_3d_ptr*n3_type_3d_ptr];
    for (auto i{0}; i < n1_type_3d_ptr; i++) {
      for (auto j{0}; j < n2_type_3d_ptr; j++) {
        for (auto k{0}; k < n3_type_3d_ptr; k++) {
          z_type_3d_ptr[i*n2_type_3d_ptr*n3_type_3d_ptr + j*n3_type_3d_ptr + k] = &C.type_3d_ptr[i][j][k];
        }
      }
    }
  }
  // c_side.to_f_setup[type, 1, ALLOC] VariableArray1D<CPP_wake_lr>
  auto n1_type_1d_alloc = C.type_1d_alloc.size();
  const CPP_wake_lr** z_type_1d_alloc = nullptr;
  if (n1_type_1d_alloc != 0) {
    z_type_1d_alloc = new const CPP_wake_lr*[n1_type_1d_alloc];
    for (auto i{0}; i < n1_type_1d_alloc; i++) z_type_1d_alloc[i] = &C.type_1d_alloc[i];
  }
  // c_side.to_f_setup[type, 2, ALLOC] VariableArray2D<CPP_wake_lr>

  auto n1_type_2d_alloc { C.type_2d_alloc.size() };
  auto n2_type_2d_alloc { std::size_t{0} };
  const CPP_wake_lr** z_type_2d_alloc { nullptr };
  if (n1_type_2d_alloc > 0) {
    n2_type_2d_alloc = C.type_2d_alloc[0].size();
    z_type_2d_alloc = new const CPP_wake_lr* [n1_type_2d_alloc*n2_type_2d_alloc];
    for (auto i{0}; i < n1_type_2d_alloc; i++) {
      for (auto j{0}; j < n2_type_2d_alloc; j++) {
        z_type_2d_alloc[i*n2_type_2d_alloc + j] = &C.type_2d_alloc[i][j];
      }
    }
  }
  // c_side.to_f_setup[type, 3, ALLOC] VariableArray3D<CPP_wake_lr>

  auto n1_type_3d_alloc { C.type_3d_alloc.size() };
  auto n2_type_3d_alloc { std::size_t{0} };
  auto n3_type_3d_alloc { std::size_t{0} };
  const CPP_wake_lr** z_type_3d_alloc { nullptr };
  if (n1_type_3d_alloc > 0) {
    n2_type_3d_alloc = C.type_3d_alloc[0].size();
    n3_type_3d_alloc = C.type_3d_alloc[0][0].size();
    z_type_3d_alloc = new const CPP_wake_lr* [n1_type_3d_alloc*n2_type_3d_alloc*n3_type_3d_alloc];
    for (auto i{0}; i < n1_type_3d_alloc; i++) {
      for (auto j{0}; j < n2_type_3d_alloc; j++) {
        for (auto k{0}; k < n3_type_3d_alloc; k++) {
          z_type_3d_alloc[i*n2_type_3d_alloc*n3_type_3d_alloc + j*n3_type_3d_alloc + k] = &C.type_3d_alloc[i][j][k];
        }
      }
    }
  }

  // c_side.to_f2_call
  all_encompassing_to_f2 (F, C.real_rp_0d, &C.real_rp_1d[0], z_real_rp_2d, z_real_rp_3d,
      C.real_rp_0d_ptr.get(), n_real_rp_0d_ptr, z_real_rp_1d_ptr, n1_real_rp_1d_ptr,
      z_real_rp_2d_ptr, n1_real_rp_2d_ptr, n2_real_rp_2d_ptr, z_real_rp_3d_ptr,
      n1_real_rp_3d_ptr, n2_real_rp_3d_ptr, n3_real_rp_3d_ptr, z_real_rp_1d_alloc,
      n1_real_rp_1d_alloc, z_real_rp_2d_alloc, n1_real_rp_2d_alloc, n2_real_rp_2d_alloc,
      z_real_rp_3d_alloc, n1_real_rp_3d_alloc, n2_real_rp_3d_alloc, n3_real_rp_3d_alloc,
      C.real_dp_0d, &C.real_dp_1d[0], z_real_dp_2d, z_real_dp_3d, C.real_dp_0d_ptr.get(),
      n_real_dp_0d_ptr, z_real_dp_1d_ptr, n1_real_dp_1d_ptr, z_real_dp_2d_ptr,
      n1_real_dp_2d_ptr, n2_real_dp_2d_ptr, z_real_dp_3d_ptr, n1_real_dp_3d_ptr,
      n2_real_dp_3d_ptr, n3_real_dp_3d_ptr, z_real_dp_1d_alloc, n1_real_dp_1d_alloc,
      z_real_dp_2d_alloc, n1_real_dp_2d_alloc, n2_real_dp_2d_alloc, z_real_dp_3d_alloc,
      n1_real_dp_3d_alloc, n2_real_dp_3d_alloc, n3_real_dp_3d_alloc, C.complex_dp_0d,
      &C.complex_dp_1d[0], z_complex_dp_2d, z_complex_dp_3d, C.complex_dp_0d_ptr.get(),
      n_complex_dp_0d_ptr, z_complex_dp_1d_ptr, n1_complex_dp_1d_ptr, z_complex_dp_2d_ptr,
      n1_complex_dp_2d_ptr, n2_complex_dp_2d_ptr, z_complex_dp_3d_ptr, n1_complex_dp_3d_ptr,
      n2_complex_dp_3d_ptr, n3_complex_dp_3d_ptr, z_complex_dp_1d_alloc,
      n1_complex_dp_1d_alloc, z_complex_dp_2d_alloc, n1_complex_dp_2d_alloc,
      n2_complex_dp_2d_alloc, z_complex_dp_3d_alloc, n1_complex_dp_3d_alloc,
      n2_complex_dp_3d_alloc, n3_complex_dp_3d_alloc, C.int_0d, &C.int_1d[0], z_int_2d,
      z_int_3d, C.int_0d_ptr.get(), n_int_0d_ptr, z_int_1d_ptr, n1_int_1d_ptr, z_int_2d_ptr,
      n1_int_2d_ptr, n2_int_2d_ptr, z_int_3d_ptr, n1_int_3d_ptr, n2_int_3d_ptr, n3_int_3d_ptr,
      z_int_1d_alloc, n1_int_1d_alloc, z_int_2d_alloc, n1_int_2d_alloc, n2_int_2d_alloc,
      z_int_3d_alloc, n1_int_3d_alloc, n2_int_3d_alloc, n3_int_3d_alloc, C.int8_0d,
      &C.int8_1d[0], z_int8_2d, z_int8_3d, C.int8_0d_ptr.get(), n_int8_0d_ptr, z_int8_1d_ptr,
      n1_int8_1d_ptr, z_int8_2d_ptr, n1_int8_2d_ptr, n2_int8_2d_ptr, z_int8_3d_ptr,
      n1_int8_3d_ptr, n2_int8_3d_ptr, n3_int8_3d_ptr, z_int8_1d_alloc, n1_int8_1d_alloc,
      z_int8_2d_alloc, n1_int8_2d_alloc, n2_int8_2d_alloc, z_int8_3d_alloc, n1_int8_3d_alloc,
      n2_int8_3d_alloc, n3_int8_3d_alloc, C.logical_0d, &C.logical_1d[0], z_logical_2d,
      z_logical_3d, C.logical_0d_ptr.get(), n_logical_0d_ptr, C.type_0d, z_type_1d, z_type_2d,
      z_type_3d, *C.type_0d_ptr, n_type_0d_ptr, z_type_1d_ptr, n1_type_1d_ptr, z_type_2d_ptr,
      n1_type_2d_ptr, n2_type_2d_ptr, z_type_3d_ptr, n1_type_3d_ptr, n2_type_3d_ptr,
      n3_type_3d_ptr, z_type_1d_alloc, n1_type_1d_alloc, z_type_2d_alloc, n1_type_2d_alloc,
      n2_type_2d_alloc, z_type_3d_alloc, n1_type_3d_alloc, n2_type_3d_alloc, n3_type_3d_alloc);

  // c_side.to_f_cleanup[real, 2, PTR]
  if (z_real_rp_2d_ptr) delete[] z_real_rp_2d_ptr;
  // c_side.to_f_cleanup[real, 3, PTR]
  if (z_real_rp_3d_ptr) delete[] z_real_rp_3d_ptr;
  // c_side.to_f_cleanup[real, 2, ALLOC]
  if (z_real_rp_2d_alloc) delete[] z_real_rp_2d_alloc;
  // c_side.to_f_cleanup[real, 3, ALLOC]
  if (z_real_rp_3d_alloc) delete[] z_real_rp_3d_alloc;
  // c_side.to_f_cleanup[real, 2, PTR]
  if (z_real_dp_2d_ptr) delete[] z_real_dp_2d_ptr;
  // c_side.to_f_cleanup[real, 3, PTR]
  if (z_real_dp_3d_ptr) delete[] z_real_dp_3d_ptr;
  // c_side.to_f_cleanup[real, 2, ALLOC]
  if (z_real_dp_2d_alloc) delete[] z_real_dp_2d_alloc;
  // c_side.to_f_cleanup[real, 3, ALLOC]
  if (z_real_dp_3d_alloc) delete[] z_real_dp_3d_alloc;
  // c_side.to_f_cleanup[complex, 2, PTR]
  if (z_complex_dp_2d_ptr) delete[] z_complex_dp_2d_ptr;
  // c_side.to_f_cleanup[complex, 3, PTR]
  if (z_complex_dp_3d_ptr) delete[] z_complex_dp_3d_ptr;
  // c_side.to_f_cleanup[complex, 2, ALLOC]
  if (z_complex_dp_2d_alloc) delete[] z_complex_dp_2d_alloc;
  // c_side.to_f_cleanup[complex, 3, ALLOC]
  if (z_complex_dp_3d_alloc) delete[] z_complex_dp_3d_alloc;
  // c_side.to_f_cleanup[integer, 2, PTR]
  if (z_int_2d_ptr) delete[] z_int_2d_ptr;
  // c_side.to_f_cleanup[integer, 3, PTR]
  if (z_int_3d_ptr) delete[] z_int_3d_ptr;
  // c_side.to_f_cleanup[integer, 2, ALLOC]
  if (z_int_2d_alloc) delete[] z_int_2d_alloc;
  // c_side.to_f_cleanup[integer, 3, ALLOC]
  if (z_int_3d_alloc) delete[] z_int_3d_alloc;
  // c_side.to_f_cleanup[integer8, 2, PTR]
  if (z_int8_2d_ptr) delete[] z_int8_2d_ptr;
  // c_side.to_f_cleanup[integer8, 3, PTR]
  if (z_int8_3d_ptr) delete[] z_int8_3d_ptr;
  // c_side.to_f_cleanup[integer8, 2, ALLOC]
  if (z_int8_2d_alloc) delete[] z_int8_2d_alloc;
  // c_side.to_f_cleanup[integer8, 3, ALLOC]
  if (z_int8_3d_alloc) delete[] z_int8_3d_alloc;
  // c_side.to_f_cleanup[type, 1, PTR]
 if (z_type_1d_ptr) delete[] z_type_1d_ptr;
  // c_side.to_f_cleanup[type, 2, PTR]
  if (z_type_2d_ptr) delete[] z_type_2d_ptr;
  // c_side.to_f_cleanup[type, 3, PTR]
  if (z_type_3d_ptr) delete[] z_type_3d_ptr;
  // c_side.to_f_cleanup[type, 1, ALLOC]
 if (z_type_1d_alloc) delete[] z_type_1d_alloc;
  // c_side.to_f_cleanup[type, 2, ALLOC]
  if (z_type_2d_alloc) delete[] z_type_2d_alloc;
  // c_side.to_f_cleanup[type, 3, ALLOC]
  if (z_type_3d_alloc) delete[] z_type_3d_alloc;
}

// c_side.to_c2_arg
extern "C" void all_encompassing_to_c2 (CPP_all_encompassing& C, c_Real& z_real_rp_0d,
    c_RealArr z_real_rp_1d, c_RealArr z_real_rp_2d, c_RealArr z_real_rp_3d, c_RealArr
    z_real_rp_0d_ptr, Int n_real_rp_0d_ptr, c_RealArr z_real_rp_1d_ptr, Int n1_real_rp_1d_ptr,
    c_RealArr z_real_rp_2d_ptr, Int n1_real_rp_2d_ptr, Int n2_real_rp_2d_ptr, c_RealArr
    z_real_rp_3d_ptr, Int n1_real_rp_3d_ptr, Int n2_real_rp_3d_ptr, Int n3_real_rp_3d_ptr,
    c_RealArr z_real_rp_1d_alloc, Int n1_real_rp_1d_alloc, c_RealArr z_real_rp_2d_alloc, Int
    n1_real_rp_2d_alloc, Int n2_real_rp_2d_alloc, c_RealArr z_real_rp_3d_alloc, Int
    n1_real_rp_3d_alloc, Int n2_real_rp_3d_alloc, Int n3_real_rp_3d_alloc, c_Real&
    z_real_dp_0d, c_RealArr z_real_dp_1d, c_RealArr z_real_dp_2d, c_RealArr z_real_dp_3d,
    c_RealArr z_real_dp_0d_ptr, Int n_real_dp_0d_ptr, c_RealArr z_real_dp_1d_ptr, Int
    n1_real_dp_1d_ptr, c_RealArr z_real_dp_2d_ptr, Int n1_real_dp_2d_ptr, Int
    n2_real_dp_2d_ptr, c_RealArr z_real_dp_3d_ptr, Int n1_real_dp_3d_ptr, Int
    n2_real_dp_3d_ptr, Int n3_real_dp_3d_ptr, c_RealArr z_real_dp_1d_alloc, Int
    n1_real_dp_1d_alloc, c_RealArr z_real_dp_2d_alloc, Int n1_real_dp_2d_alloc, Int
    n2_real_dp_2d_alloc, c_RealArr z_real_dp_3d_alloc, Int n1_real_dp_3d_alloc, Int
    n2_real_dp_3d_alloc, Int n3_real_dp_3d_alloc, c_Complex& z_complex_dp_0d, c_ComplexArr
    z_complex_dp_1d, c_ComplexArr z_complex_dp_2d, c_ComplexArr z_complex_dp_3d, c_ComplexArr
    z_complex_dp_0d_ptr, Int n_complex_dp_0d_ptr, c_ComplexArr z_complex_dp_1d_ptr, Int
    n1_complex_dp_1d_ptr, c_ComplexArr z_complex_dp_2d_ptr, Int n1_complex_dp_2d_ptr, Int
    n2_complex_dp_2d_ptr, c_ComplexArr z_complex_dp_3d_ptr, Int n1_complex_dp_3d_ptr, Int
    n2_complex_dp_3d_ptr, Int n3_complex_dp_3d_ptr, c_ComplexArr z_complex_dp_1d_alloc, Int
    n1_complex_dp_1d_alloc, c_ComplexArr z_complex_dp_2d_alloc, Int n1_complex_dp_2d_alloc, Int
    n2_complex_dp_2d_alloc, c_ComplexArr z_complex_dp_3d_alloc, Int n1_complex_dp_3d_alloc, Int
    n2_complex_dp_3d_alloc, Int n3_complex_dp_3d_alloc, c_Int& z_int_0d, c_IntArr z_int_1d,
    c_IntArr z_int_2d, c_IntArr z_int_3d, c_IntArr z_int_0d_ptr, Int n_int_0d_ptr, c_IntArr
    z_int_1d_ptr, Int n1_int_1d_ptr, c_IntArr z_int_2d_ptr, Int n1_int_2d_ptr, Int
    n2_int_2d_ptr, c_IntArr z_int_3d_ptr, Int n1_int_3d_ptr, Int n2_int_3d_ptr, Int
    n3_int_3d_ptr, c_IntArr z_int_1d_alloc, Int n1_int_1d_alloc, c_IntArr z_int_2d_alloc, Int
    n1_int_2d_alloc, Int n2_int_2d_alloc, c_IntArr z_int_3d_alloc, Int n1_int_3d_alloc, Int
    n2_int_3d_alloc, Int n3_int_3d_alloc, c_Int8& z_int8_0d, c_Int8Arr z_int8_1d, c_Int8Arr
    z_int8_2d, c_Int8Arr z_int8_3d, c_Int8Arr z_int8_0d_ptr, Int n_int8_0d_ptr, c_Int8Arr
    z_int8_1d_ptr, Int n1_int8_1d_ptr, c_Int8Arr z_int8_2d_ptr, Int n1_int8_2d_ptr, Int
    n2_int8_2d_ptr, c_Int8Arr z_int8_3d_ptr, Int n1_int8_3d_ptr, Int n2_int8_3d_ptr, Int
    n3_int8_3d_ptr, c_Int8Arr z_int8_1d_alloc, Int n1_int8_1d_alloc, c_Int8Arr z_int8_2d_alloc,
    Int n1_int8_2d_alloc, Int n2_int8_2d_alloc, c_Int8Arr z_int8_3d_alloc, Int
    n1_int8_3d_alloc, Int n2_int8_3d_alloc, Int n3_int8_3d_alloc, c_Bool& z_logical_0d,
    c_BoolArr z_logical_1d, c_BoolArr z_logical_2d, c_BoolArr z_logical_3d, c_BoolArr
    z_logical_0d_ptr, Int n_logical_0d_ptr, const Opaque_wake_lr_class* z_type_0d, const
    Opaque_wake_lr_class** z_type_1d, const Opaque_wake_lr_class** z_type_2d, const
    Opaque_wake_lr_class** z_type_3d, Opaque_wake_lr_class* z_type_0d_ptr, Int n_type_0d_ptr,
    Opaque_wake_lr_class** z_type_1d_ptr, Int n1_type_1d_ptr, Opaque_wake_lr_class**
    z_type_2d_ptr, Int n1_type_2d_ptr, Int n2_type_2d_ptr, Opaque_wake_lr_class**
    z_type_3d_ptr, Int n1_type_3d_ptr, Int n2_type_3d_ptr, Int n3_type_3d_ptr,
    Opaque_wake_lr_class** z_type_1d_alloc, Int n1_type_1d_alloc, Opaque_wake_lr_class**
    z_type_2d_alloc, Int n1_type_2d_alloc, Int n2_type_2d_alloc, Opaque_wake_lr_class**
    z_type_3d_alloc, Int n1_type_3d_alloc, Int n2_type_3d_alloc, Int n3_type_3d_alloc) {

  // c_side.to_c2_set[real, 0, NOT] Real
  C.real_rp_0d = z_real_rp_0d;
  // c_side.to_c2_set[real, 1, NOT] FixedArray1D<Real, 3>
  C.real_rp_1d << z_real_rp_1d;
  // c_side.to_c2_set[real, 2, NOT] FixedArray2D<Real, 3, 4>
  C.real_rp_2d << z_real_rp_2d;
  // c_side.to_c2_set[real, 3, NOT] FixedArray3D<Real, 3, 4, 5>
  C.real_rp_3d << z_real_rp_3d;
  // c_side.to_c2_set[real, 0, PTR] shared_ptr<Real>
  if (n_real_rp_0d_ptr == 0) {
    C.real_rp_0d_ptr = nullptr;
  } else {
    C.real_rp_0d_ptr = make_shared<Real>();
    *C.real_rp_0d_ptr = *z_real_rp_0d_ptr;
  }

  // c_side.to_c2_set[real, 1, PTR] VariableArray1D<Real>

  C.real_rp_1d_ptr.resize(n1_real_rp_1d_ptr);
  C.real_rp_1d_ptr << z_real_rp_1d_ptr;

  // c_side.to_c2_set[real, 2, PTR] VariableArray2D<Real>
  C.real_rp_2d_ptr.resize(n1_real_rp_2d_ptr);
  for (auto i{0}; i < n1_real_rp_2d_ptr; i++) C.real_rp_2d_ptr[i].resize(n2_real_rp_2d_ptr);
  C.real_rp_2d_ptr << z_real_rp_2d_ptr;

  // c_side.to_c2_set[real, 3, PTR] VariableArray3D<Real>
  C.real_rp_3d_ptr.resize(n1_real_rp_3d_ptr);
  for (size_t i = 0; i < C.real_rp_3d_ptr.size(); i++) {
    C.real_rp_3d_ptr[i].resize(n2_real_rp_3d_ptr);
    for (size_t j = 0; j < C.real_rp_3d_ptr[0].size(); j++)
      C.real_rp_3d_ptr[i][j].resize(n3_real_rp_3d_ptr);
  }
  C.real_rp_3d_ptr << z_real_rp_3d_ptr;

  // c_side.to_c2_set[real, 1, ALLOC] VariableArray1D<Real>

  C.real_rp_1d_alloc.resize(n1_real_rp_1d_alloc);
  C.real_rp_1d_alloc << z_real_rp_1d_alloc;

  // c_side.to_c2_set[real, 2, ALLOC] VariableArray2D<Real>
  C.real_rp_2d_alloc.resize(n1_real_rp_2d_alloc);
  for (auto i{0}; i < n1_real_rp_2d_alloc; i++) C.real_rp_2d_alloc[i].resize(n2_real_rp_2d_alloc);
  C.real_rp_2d_alloc << z_real_rp_2d_alloc;

  // c_side.to_c2_set[real, 3, ALLOC] VariableArray3D<Real>
  C.real_rp_3d_alloc.resize(n1_real_rp_3d_alloc);
  for (size_t i = 0; i < C.real_rp_3d_alloc.size(); i++) {
    C.real_rp_3d_alloc[i].resize(n2_real_rp_3d_alloc);
    for (size_t j = 0; j < C.real_rp_3d_alloc[0].size(); j++)
      C.real_rp_3d_alloc[i][j].resize(n3_real_rp_3d_alloc);
  }
  C.real_rp_3d_alloc << z_real_rp_3d_alloc;

  // c_side.to_c2_set[real, 0, NOT] Real
  C.real_dp_0d = z_real_dp_0d;
  // c_side.to_c2_set[real, 1, NOT] FixedArray1D<Real, 3>
  C.real_dp_1d << z_real_dp_1d;
  // c_side.to_c2_set[real, 2, NOT] FixedArray2D<Real, 3, 4>
  C.real_dp_2d << z_real_dp_2d;
  // c_side.to_c2_set[real, 3, NOT] FixedArray3D<Real, 3, 4, 5>
  C.real_dp_3d << z_real_dp_3d;
  // c_side.to_c2_set[real, 0, PTR] shared_ptr<Real>
  if (n_real_dp_0d_ptr == 0) {
    C.real_dp_0d_ptr = nullptr;
  } else {
    C.real_dp_0d_ptr = make_shared<Real>();
    *C.real_dp_0d_ptr = *z_real_dp_0d_ptr;
  }

  // c_side.to_c2_set[real, 1, PTR] VariableArray1D<Real>

  C.real_dp_1d_ptr.resize(n1_real_dp_1d_ptr);
  C.real_dp_1d_ptr << z_real_dp_1d_ptr;

  // c_side.to_c2_set[real, 2, PTR] VariableArray2D<Real>
  C.real_dp_2d_ptr.resize(n1_real_dp_2d_ptr);
  for (auto i{0}; i < n1_real_dp_2d_ptr; i++) C.real_dp_2d_ptr[i].resize(n2_real_dp_2d_ptr);
  C.real_dp_2d_ptr << z_real_dp_2d_ptr;

  // c_side.to_c2_set[real, 3, PTR] VariableArray3D<Real>
  C.real_dp_3d_ptr.resize(n1_real_dp_3d_ptr);
  for (size_t i = 0; i < C.real_dp_3d_ptr.size(); i++) {
    C.real_dp_3d_ptr[i].resize(n2_real_dp_3d_ptr);
    for (size_t j = 0; j < C.real_dp_3d_ptr[0].size(); j++)
      C.real_dp_3d_ptr[i][j].resize(n3_real_dp_3d_ptr);
  }
  C.real_dp_3d_ptr << z_real_dp_3d_ptr;

  // c_side.to_c2_set[real, 1, ALLOC] VariableArray1D<Real>

  C.real_dp_1d_alloc.resize(n1_real_dp_1d_alloc);
  C.real_dp_1d_alloc << z_real_dp_1d_alloc;

  // c_side.to_c2_set[real, 2, ALLOC] VariableArray2D<Real>
  C.real_dp_2d_alloc.resize(n1_real_dp_2d_alloc);
  for (auto i{0}; i < n1_real_dp_2d_alloc; i++) C.real_dp_2d_alloc[i].resize(n2_real_dp_2d_alloc);
  C.real_dp_2d_alloc << z_real_dp_2d_alloc;

  // c_side.to_c2_set[real, 3, ALLOC] VariableArray3D<Real>
  C.real_dp_3d_alloc.resize(n1_real_dp_3d_alloc);
  for (size_t i = 0; i < C.real_dp_3d_alloc.size(); i++) {
    C.real_dp_3d_alloc[i].resize(n2_real_dp_3d_alloc);
    for (size_t j = 0; j < C.real_dp_3d_alloc[0].size(); j++)
      C.real_dp_3d_alloc[i][j].resize(n3_real_dp_3d_alloc);
  }
  C.real_dp_3d_alloc << z_real_dp_3d_alloc;

  // c_side.to_c2_set[complex, 0, NOT] Complex
  C.complex_dp_0d = z_complex_dp_0d;
  // c_side.to_c2_set[complex, 1, NOT] FixedArray1D<Complex, 3>
  C.complex_dp_1d << z_complex_dp_1d;
  // c_side.to_c2_set[complex, 2, NOT] FixedArray2D<Complex, 3, 4>
  C.complex_dp_2d << z_complex_dp_2d;
  // c_side.to_c2_set[complex, 3, NOT] FixedArray3D<Complex, 3, 4, 5>
  C.complex_dp_3d << z_complex_dp_3d;
  // c_side.to_c2_set[complex, 0, PTR] shared_ptr<Complex>
  if (n_complex_dp_0d_ptr == 0) {
    C.complex_dp_0d_ptr = nullptr;
  } else {
    C.complex_dp_0d_ptr = make_shared<Complex>();
    *C.complex_dp_0d_ptr = *z_complex_dp_0d_ptr;
  }

  // c_side.to_c2_set[complex, 1, PTR] VariableArray1D<Complex>

  C.complex_dp_1d_ptr.resize(n1_complex_dp_1d_ptr);
  C.complex_dp_1d_ptr << z_complex_dp_1d_ptr;

  // c_side.to_c2_set[complex, 2, PTR] VariableArray2D<Complex>
  C.complex_dp_2d_ptr.resize(n1_complex_dp_2d_ptr);
  for (auto i{0}; i < n1_complex_dp_2d_ptr; i++) C.complex_dp_2d_ptr[i].resize(n2_complex_dp_2d_ptr);
  C.complex_dp_2d_ptr << z_complex_dp_2d_ptr;

  // c_side.to_c2_set[complex, 3, PTR] VariableArray3D<Complex>
  C.complex_dp_3d_ptr.resize(n1_complex_dp_3d_ptr);
  for (size_t i = 0; i < C.complex_dp_3d_ptr.size(); i++) {
    C.complex_dp_3d_ptr[i].resize(n2_complex_dp_3d_ptr);
    for (size_t j = 0; j < C.complex_dp_3d_ptr[0].size(); j++)
      C.complex_dp_3d_ptr[i][j].resize(n3_complex_dp_3d_ptr);
  }
  C.complex_dp_3d_ptr << z_complex_dp_3d_ptr;

  // c_side.to_c2_set[complex, 1, ALLOC] VariableArray1D<Complex>

  C.complex_dp_1d_alloc.resize(n1_complex_dp_1d_alloc);
  C.complex_dp_1d_alloc << z_complex_dp_1d_alloc;

  // c_side.to_c2_set[complex, 2, ALLOC] VariableArray2D<Complex>
  C.complex_dp_2d_alloc.resize(n1_complex_dp_2d_alloc);
  for (auto i{0}; i < n1_complex_dp_2d_alloc; i++) C.complex_dp_2d_alloc[i].resize(n2_complex_dp_2d_alloc);
  C.complex_dp_2d_alloc << z_complex_dp_2d_alloc;

  // c_side.to_c2_set[complex, 3, ALLOC] VariableArray3D<Complex>
  C.complex_dp_3d_alloc.resize(n1_complex_dp_3d_alloc);
  for (size_t i = 0; i < C.complex_dp_3d_alloc.size(); i++) {
    C.complex_dp_3d_alloc[i].resize(n2_complex_dp_3d_alloc);
    for (size_t j = 0; j < C.complex_dp_3d_alloc[0].size(); j++)
      C.complex_dp_3d_alloc[i][j].resize(n3_complex_dp_3d_alloc);
  }
  C.complex_dp_3d_alloc << z_complex_dp_3d_alloc;

  // c_side.to_c2_set[integer, 0, NOT] Int
  C.int_0d = z_int_0d;
  // c_side.to_c2_set[integer, 1, NOT] FixedArray1D<Int, 3>
  C.int_1d << z_int_1d;
  // c_side.to_c2_set[integer, 2, NOT] FixedArray2D<Int, 3, 4>
  C.int_2d << z_int_2d;
  // c_side.to_c2_set[integer, 3, NOT] FixedArray3D<Int, 3, 4, 5>
  C.int_3d << z_int_3d;
  // c_side.to_c2_set[integer, 0, PTR] shared_ptr<Int>
  if (n_int_0d_ptr == 0) {
    C.int_0d_ptr = nullptr;
  } else {
    C.int_0d_ptr = make_shared<Int>();
    *C.int_0d_ptr = *z_int_0d_ptr;
  }

  // c_side.to_c2_set[integer, 1, PTR] VariableArray1D<Int>

  C.int_1d_ptr.resize(n1_int_1d_ptr);
  C.int_1d_ptr << z_int_1d_ptr;

  // c_side.to_c2_set[integer, 2, PTR] VariableArray2D<Int>
  C.int_2d_ptr.resize(n1_int_2d_ptr);
  for (auto i{0}; i < n1_int_2d_ptr; i++) C.int_2d_ptr[i].resize(n2_int_2d_ptr);
  C.int_2d_ptr << z_int_2d_ptr;

  // c_side.to_c2_set[integer, 3, PTR] VariableArray3D<Int>
  C.int_3d_ptr.resize(n1_int_3d_ptr);
  for (size_t i = 0; i < C.int_3d_ptr.size(); i++) {
    C.int_3d_ptr[i].resize(n2_int_3d_ptr);
    for (size_t j = 0; j < C.int_3d_ptr[0].size(); j++)
      C.int_3d_ptr[i][j].resize(n3_int_3d_ptr);
  }
  C.int_3d_ptr << z_int_3d_ptr;

  // c_side.to_c2_set[integer, 1, ALLOC] VariableArray1D<Int>

  C.int_1d_alloc.resize(n1_int_1d_alloc);
  C.int_1d_alloc << z_int_1d_alloc;

  // c_side.to_c2_set[integer, 2, ALLOC] VariableArray2D<Int>
  C.int_2d_alloc.resize(n1_int_2d_alloc);
  for (auto i{0}; i < n1_int_2d_alloc; i++) C.int_2d_alloc[i].resize(n2_int_2d_alloc);
  C.int_2d_alloc << z_int_2d_alloc;

  // c_side.to_c2_set[integer, 3, ALLOC] VariableArray3D<Int>
  C.int_3d_alloc.resize(n1_int_3d_alloc);
  for (size_t i = 0; i < C.int_3d_alloc.size(); i++) {
    C.int_3d_alloc[i].resize(n2_int_3d_alloc);
    for (size_t j = 0; j < C.int_3d_alloc[0].size(); j++)
      C.int_3d_alloc[i][j].resize(n3_int_3d_alloc);
  }
  C.int_3d_alloc << z_int_3d_alloc;

  // c_side.to_c2_set[integer8, 0, NOT] Int8
  C.int8_0d = z_int8_0d;
  // c_side.to_c2_set[integer8, 1, NOT] FixedArray1D<Int8, 3>
  C.int8_1d << z_int8_1d;
  // c_side.to_c2_set[integer8, 2, NOT] FixedArray2D<Int8, 3, 4>
  C.int8_2d << z_int8_2d;
  // c_side.to_c2_set[integer8, 3, NOT] FixedArray3D<Int8, 3, 4, 5>
  C.int8_3d << z_int8_3d;
  // c_side.to_c2_set[integer8, 0, PTR] shared_ptr<Int8>
  if (n_int8_0d_ptr == 0) {
    C.int8_0d_ptr = nullptr;
  } else {
    C.int8_0d_ptr = make_shared<Int8>();
    *C.int8_0d_ptr = *z_int8_0d_ptr;
  }

  // c_side.to_c2_set[integer8, 1, PTR] VariableArray1D<Int8>

  C.int8_1d_ptr.resize(n1_int8_1d_ptr);
  C.int8_1d_ptr << z_int8_1d_ptr;

  // c_side.to_c2_set[integer8, 2, PTR] VariableArray2D<Int8>
  C.int8_2d_ptr.resize(n1_int8_2d_ptr);
  for (auto i{0}; i < n1_int8_2d_ptr; i++) C.int8_2d_ptr[i].resize(n2_int8_2d_ptr);
  C.int8_2d_ptr << z_int8_2d_ptr;

  // c_side.to_c2_set[integer8, 3, PTR] VariableArray3D<Int8>
  C.int8_3d_ptr.resize(n1_int8_3d_ptr);
  for (size_t i = 0; i < C.int8_3d_ptr.size(); i++) {
    C.int8_3d_ptr[i].resize(n2_int8_3d_ptr);
    for (size_t j = 0; j < C.int8_3d_ptr[0].size(); j++)
      C.int8_3d_ptr[i][j].resize(n3_int8_3d_ptr);
  }
  C.int8_3d_ptr << z_int8_3d_ptr;

  // c_side.to_c2_set[integer8, 1, ALLOC] VariableArray1D<Int8>

  C.int8_1d_alloc.resize(n1_int8_1d_alloc);
  C.int8_1d_alloc << z_int8_1d_alloc;

  // c_side.to_c2_set[integer8, 2, ALLOC] VariableArray2D<Int8>
  C.int8_2d_alloc.resize(n1_int8_2d_alloc);
  for (auto i{0}; i < n1_int8_2d_alloc; i++) C.int8_2d_alloc[i].resize(n2_int8_2d_alloc);
  C.int8_2d_alloc << z_int8_2d_alloc;

  // c_side.to_c2_set[integer8, 3, ALLOC] VariableArray3D<Int8>
  C.int8_3d_alloc.resize(n1_int8_3d_alloc);
  for (size_t i = 0; i < C.int8_3d_alloc.size(); i++) {
    C.int8_3d_alloc[i].resize(n2_int8_3d_alloc);
    for (size_t j = 0; j < C.int8_3d_alloc[0].size(); j++)
      C.int8_3d_alloc[i][j].resize(n3_int8_3d_alloc);
  }
  C.int8_3d_alloc << z_int8_3d_alloc;

  // c_side.to_c2_set[logical, 0, NOT] Bool
  C.logical_0d = z_logical_0d;
  // c_side.to_c2_set[logical, 1, NOT] FixedArray1D<Bool, 3>
  C.logical_1d << z_logical_1d;
  // c_side.to_c2_set[logical, 2, NOT] FixedArray2D<Bool, 3, 4>
  C.logical_2d << z_logical_2d;
  // c_side.to_c2_set[logical, 3, NOT] FixedArray3D<Bool, 3, 4, 5>
  C.logical_3d << z_logical_3d;
  // c_side.to_c2_set[logical, 0, PTR] shared_ptr<Bool>
  if (n_logical_0d_ptr == 0) {
    C.logical_0d_ptr = nullptr;
  } else {
    C.logical_0d_ptr = make_shared<Bool>();
    *C.logical_0d_ptr = *z_logical_0d_ptr;
  }

  // c_side.to_c2_set[type, 0, NOT] CPP_wake_lr
  wake_lr_to_c(z_type_0d, C.type_0d);
  // c_side.to_c2_set[type, 1, NOT] FixedArray1D<CPP_wake_lr, 3>
for (size_t i = 0; i < C.type_1d.size(); i++)
{ wake_lr_to_c(z_type_1d[i], C.type_1d[i]); }
  // c_side.to_c2_set[type, 2, NOT] SharedVector2D<CPP_wake_lr>
  for (size_t i = 0; i < C.type_2d.size(); i++)  for (size_t j = 0; j < C.type_2d[0].size(); j++) 
    {auto m = 4*i + j; wake_lr_to_c(z_type_2d[m], *C.type_2d[i][j].get());}
  // c_side.to_c2_set[type, 3, NOT] SharedVector3D<CPP_wake_lr>
  for (size_t i = 0; i < C.type_3d.size(); i++)  for (size_t j = 0; j < C.type_3d[0].size(); j++)   for (size_t k = 0; k < C.type_3d[0][0].size(); k++)
    {auto m = 5*4*i + 5*j + k; wake_lr_to_c(z_type_3d[m], *C.type_3d[i][j][k].get());}
  // c_side.to_c2_set[type, 0, PTR] shared_ptr<CPP_wake_lr>
  if (n_type_0d_ptr == 0) {
    C.type_0d_ptr = nullptr;
  } else {
    C.type_0d_ptr = make_shared<CPP_wake_lr>();
    wake_lr_to_c(z_type_0d_ptr, *C.type_0d_ptr);
  }

  // c_side.to_c2_set[type, 1, PTR] VariableArray1D<CPP_wake_lr>
  C.type_1d_ptr.resize(n1_type_1d_ptr);
  for (auto i{0}; i < n1_type_1d_ptr; i++) { wake_lr_to_c(z_type_1d_ptr[i], C.type_1d_ptr[i]); }

  // c_side.to_c2_set[type, 2, PTR] VariableArray2D<CPP_wake_lr>
  C.type_2d_ptr.resize(n1_type_2d_ptr);
  for (auto i{0}; i < n1_type_2d_ptr; i++) {
    C.type_2d_ptr[i].resize(n2_type_2d_ptr);
    for (auto j{0}; j < n2_type_2d_ptr; j++) {
        auto &item = C.type_2d_ptr[i][j];
        wake_lr_to_c(z_type_2d_ptr[n2_type_2d_ptr*i+j], item);
    }
  }

  // c_side.to_c2_set[type, 3, PTR] VariableArray3D<CPP_wake_lr>

  C.type_3d_ptr.resize(n1_type_3d_ptr);
  for (auto i{0}; i < n1_type_3d_ptr; i++) {
    C.type_3d_ptr[i].resize(n2_type_3d_ptr);
    for (auto j{0}; j < n2_type_3d_ptr; j++) {
      C.type_3d_ptr[i][j].resize(n3_type_3d_ptr);
      for (auto k{0}; k < n3_type_3d_ptr; k++) {
        // C.type_3d_ptr[i][j][k] = make_shared<CPP_wake_lr>();
        wake_lr_to_c(z_type_3d_ptr[n3_type_3d_ptr*n2_type_3d_ptr*i+n3_type_3d_ptr*j+k], C.type_3d_ptr[i][j][k]);
    } } }

  // c_side.to_c2_set[type, 1, ALLOC] VariableArray1D<CPP_wake_lr>
  C.type_1d_alloc.resize(n1_type_1d_alloc);
  for (auto i{0}; i < n1_type_1d_alloc; i++) { wake_lr_to_c(z_type_1d_alloc[i], C.type_1d_alloc[i]); }

  // c_side.to_c2_set[type, 2, ALLOC] VariableArray2D<CPP_wake_lr>
  C.type_2d_alloc.resize(n1_type_2d_alloc);
  for (auto i{0}; i < n1_type_2d_alloc; i++) {
    C.type_2d_alloc[i].resize(n2_type_2d_alloc);
    for (auto j{0}; j < n2_type_2d_alloc; j++) {
        auto &item = C.type_2d_alloc[i][j];
        wake_lr_to_c(z_type_2d_alloc[n2_type_2d_alloc*i+j], item);
    }
  }

  // c_side.to_c2_set[type, 3, ALLOC] VariableArray3D<CPP_wake_lr>

  C.type_3d_alloc.resize(n1_type_3d_alloc);
  for (auto i{0}; i < n1_type_3d_alloc; i++) {
    C.type_3d_alloc[i].resize(n2_type_3d_alloc);
    for (auto j{0}; j < n2_type_3d_alloc; j++) {
      C.type_3d_alloc[i][j].resize(n3_type_3d_alloc);
      for (auto k{0}; k < n3_type_3d_alloc; k++) {
        // C.type_3d_alloc[i][j][k] = make_shared<CPP_wake_lr>();
        wake_lr_to_c(z_type_3d_alloc[n3_type_3d_alloc*n2_type_3d_alloc*i+n3_type_3d_alloc*j+k], C.type_3d_alloc[i][j][k]);
    } } }

}
