//+
// C++ classes definitions for Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY! 
//-

#ifndef CPP_BMAD_CLASSES

#include <iostream>
#include <memory>

#include "converter_templates.h"
#include "bmad_enums.h"
#include "bmad_std_typedef.h"

using namespace Bmad;
using std::shared_ptr, std::make_shared;
using std::ostream;

//--------------------------------------------------------------------
// CPP_wake_lr

class Opaque_wake_lr_class {};  // Opaque class for pointers to corresponding fortran structs.

class CPP_wake_lr: public std::enable_shared_from_this<CPP_wake_lr>  {
public:
  Int8 aaa = { None };
  Int bbb = { None };
  string file = { "" };
  Real t_ref = { 0.0 };
  Real freq_spread = { 0.0 };

  CPP_wake_lr() {
  
  }

  virtual ~CPP_wake_lr() {  }
  std::shared_ptr<CPP_wake_lr> getptr() { return shared_from_this(); }

  friend ostream& operator<<(ostream& os, const CPP_wake_lr& obj) {
    os << "CPP_wake_lr{";
    os << "aaa=" << obj.aaa << ", ";
    os << "bbb=" << obj.bbb << ", ";
    os << "file=" << obj.file << ", ";
    os << "t_ref=" << obj.t_ref << ", ";
    os << "freq_spread=" << obj.freq_spread;
    os << "}";
    return os;
  }

  std::string repr() const {
    std::ostringstream os;
    os << this;
    return os.str();
  }
    
};

extern "C" void wake_lr_to_c (const Opaque_wake_lr_class*, CPP_wake_lr&);
extern "C" void wake_lr_to_f (const CPP_wake_lr&, Opaque_wake_lr_class*);

bool operator== (const CPP_wake_lr&, const CPP_wake_lr&);
//--------------------------------------------------------------------
// CPP_wake

class Opaque_wake_class {};  // Opaque class for pointers to corresponding fortran structs.

class CPP_wake: public std::enable_shared_from_this<CPP_wake>  {
public:
  CPP_wake_lr sr;

  CPP_wake() {
  
  }

  virtual ~CPP_wake() {  }
  std::shared_ptr<CPP_wake> getptr() { return shared_from_this(); }

  friend ostream& operator<<(ostream& os, const CPP_wake& obj) {
    os << "CPP_wake{";
    os << "sr=" << obj.sr;
    os << "}";
    return os;
  }

  std::string repr() const {
    std::ostringstream os;
    os << this;
    return os.str();
  }
    
};

extern "C" void wake_to_c (const Opaque_wake_class*, CPP_wake&);
extern "C" void wake_to_f (const CPP_wake&, Opaque_wake_class*);

bool operator== (const CPP_wake&, const CPP_wake&);
//--------------------------------------------------------------------
// CPP_all_encompassing

class Opaque_all_encompassing_class {};  // Opaque class for pointers to corresponding fortran structs.

class CPP_all_encompassing: public std::enable_shared_from_this<CPP_all_encompassing>  {
public:
  Real real_rp_0d = { None };
  FixedArray1D<Real, 3> real_rp_1d = { None };
  FixedArray2D<Real, 3, 4> real_rp_2d;
  FixedArray3D<Real, 3, 4, 5> real_rp_3d;
  shared_ptr<Real> real_rp_0d_ptr = nullptr;
  VariableArray1D<Real> real_rp_1d_ptr = { None };
  VariableArray2D<Real> real_rp_2d_ptr;
  VariableArray3D<Real> real_rp_3d_ptr;
  VariableArray1D<Real> real_rp_1d_alloc = { None };
  VariableArray2D<Real> real_rp_2d_alloc;
  VariableArray3D<Real> real_rp_3d_alloc;
  Real real_dp_0d = { None };
  FixedArray1D<Real, 3> real_dp_1d = { None };
  FixedArray2D<Real, 3, 4> real_dp_2d;
  FixedArray3D<Real, 3, 4, 5> real_dp_3d;
  shared_ptr<Real> real_dp_0d_ptr = nullptr;
  VariableArray1D<Real> real_dp_1d_ptr = { None };
  VariableArray2D<Real> real_dp_2d_ptr;
  VariableArray3D<Real> real_dp_3d_ptr;
  VariableArray1D<Real> real_dp_1d_alloc = { None };
  VariableArray2D<Real> real_dp_2d_alloc;
  VariableArray3D<Real> real_dp_3d_alloc;
  Complex complex_dp_0d = { None };
  FixedArray1D<Complex, 3> complex_dp_1d = { None };
  FixedArray2D<Complex, 3, 4> complex_dp_2d;
  FixedArray3D<Complex, 3, 4, 5> complex_dp_3d;
  shared_ptr<Complex> complex_dp_0d_ptr = nullptr;
  VariableArray1D<Complex> complex_dp_1d_ptr = { None };
  VariableArray2D<Complex> complex_dp_2d_ptr;
  VariableArray3D<Complex> complex_dp_3d_ptr;
  VariableArray1D<Complex> complex_dp_1d_alloc = { None };
  VariableArray2D<Complex> complex_dp_2d_alloc;
  VariableArray3D<Complex> complex_dp_3d_alloc;
  Int int_0d = { None };
  FixedArray1D<Int, 3> int_1d = { None };
  FixedArray2D<Int, 3, 4> int_2d;
  FixedArray3D<Int, 3, 4, 5> int_3d;
  shared_ptr<Int> int_0d_ptr = nullptr;
  VariableArray1D<Int> int_1d_ptr = { None };
  VariableArray2D<Int> int_2d_ptr;
  VariableArray3D<Int> int_3d_ptr;
  VariableArray1D<Int> int_1d_alloc = { None };
  VariableArray2D<Int> int_2d_alloc;
  VariableArray3D<Int> int_3d_alloc;
  Int8 int8_0d = { None };
  FixedArray1D<Int8, 3> int8_1d = { None };
  FixedArray2D<Int8, 3, 4> int8_2d;
  FixedArray3D<Int8, 3, 4, 5> int8_3d;
  shared_ptr<Int8> int8_0d_ptr = nullptr;
  VariableArray1D<Int8> int8_1d_ptr = { None };
  VariableArray2D<Int8> int8_2d_ptr;
  VariableArray3D<Int8> int8_3d_ptr;
  VariableArray1D<Int8> int8_1d_alloc = { None };
  VariableArray2D<Int8> int8_2d_alloc;
  VariableArray3D<Int8> int8_3d_alloc;
  Bool logical_0d = { None };
  FixedArray1D<Bool, 3> logical_1d = { None };
  FixedArray2D<Bool, 3, 4> logical_2d;
  FixedArray3D<Bool, 3, 4, 5> logical_3d;
  shared_ptr<Bool> logical_0d_ptr = nullptr;
  CPP_wake_lr type_0d;
  FixedArray1D<CPP_wake_lr, 3> type_1d;
  SharedVector2D<CPP_wake_lr> type_2d;
  SharedVector3D<CPP_wake_lr> type_3d;
  shared_ptr<CPP_wake_lr> type_0d_ptr = nullptr;
  VariableArray1D<CPP_wake_lr> type_1d_ptr;
  VariableArray2D<CPP_wake_lr> type_2d_ptr;
  VariableArray3D<CPP_wake_lr> type_3d_ptr;
  VariableArray1D<CPP_wake_lr> type_1d_alloc;
  VariableArray2D<CPP_wake_lr> type_2d_alloc;
  VariableArray3D<CPP_wake_lr> type_3d_alloc;

  CPP_all_encompassing() {
  
  }

  virtual ~CPP_all_encompassing() {  }
  std::shared_ptr<CPP_all_encompassing> getptr() { return shared_from_this(); }

  friend ostream& operator<<(ostream& os, const CPP_all_encompassing& obj) {
    os << "CPP_all_encompassing{";
    os << "real_rp_0d=" << obj.real_rp_0d << ", ";
    os << "real_rp_1d=" << obj.real_rp_1d << ", ";
    os << "real_rp_2d=" << obj.real_rp_2d << ", ";
    os << "real_rp_3d=" << obj.real_rp_3d << ", ";
    os << "real_rp_0d_ptr="; if (obj.real_rp_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.real_rp_0d_ptr; }; os << ", ";
    os << "real_rp_1d_ptr=" << obj.real_rp_1d_ptr << ", ";
    os << "real_rp_2d_ptr=" << obj.real_rp_2d_ptr << ", ";
    os << "real_rp_3d_ptr=" << obj.real_rp_3d_ptr << ", ";
    os << "real_rp_1d_alloc=" << obj.real_rp_1d_alloc << ", ";
    os << "real_rp_2d_alloc=" << obj.real_rp_2d_alloc << ", ";
    os << "real_rp_3d_alloc=" << obj.real_rp_3d_alloc << ", ";
    os << "real_dp_0d=" << obj.real_dp_0d << ", ";
    os << "real_dp_1d=" << obj.real_dp_1d << ", ";
    os << "real_dp_2d=" << obj.real_dp_2d << ", ";
    os << "real_dp_3d=" << obj.real_dp_3d << ", ";
    os << "real_dp_0d_ptr="; if (obj.real_dp_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.real_dp_0d_ptr; }; os << ", ";
    os << "real_dp_1d_ptr=" << obj.real_dp_1d_ptr << ", ";
    os << "real_dp_2d_ptr=" << obj.real_dp_2d_ptr << ", ";
    os << "real_dp_3d_ptr=" << obj.real_dp_3d_ptr << ", ";
    os << "real_dp_1d_alloc=" << obj.real_dp_1d_alloc << ", ";
    os << "real_dp_2d_alloc=" << obj.real_dp_2d_alloc << ", ";
    os << "real_dp_3d_alloc=" << obj.real_dp_3d_alloc << ", ";
    os << "complex_dp_0d=" << obj.complex_dp_0d << ", ";
    os << "complex_dp_1d=" << obj.complex_dp_1d << ", ";
    os << "complex_dp_2d=" << obj.complex_dp_2d << ", ";
    os << "complex_dp_3d=" << obj.complex_dp_3d << ", ";
    os << "complex_dp_0d_ptr="; if (obj.complex_dp_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.complex_dp_0d_ptr; }; os << ", ";
    os << "complex_dp_1d_ptr=" << obj.complex_dp_1d_ptr << ", ";
    os << "complex_dp_2d_ptr=" << obj.complex_dp_2d_ptr << ", ";
    os << "complex_dp_3d_ptr=" << obj.complex_dp_3d_ptr << ", ";
    os << "complex_dp_1d_alloc=" << obj.complex_dp_1d_alloc << ", ";
    os << "complex_dp_2d_alloc=" << obj.complex_dp_2d_alloc << ", ";
    os << "complex_dp_3d_alloc=" << obj.complex_dp_3d_alloc << ", ";
    os << "int_0d=" << obj.int_0d << ", ";
    os << "int_1d=" << obj.int_1d << ", ";
    os << "int_2d=" << obj.int_2d << ", ";
    os << "int_3d=" << obj.int_3d << ", ";
    os << "int_0d_ptr="; if (obj.int_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.int_0d_ptr; }; os << ", ";
    os << "int_1d_ptr=" << obj.int_1d_ptr << ", ";
    os << "int_2d_ptr=" << obj.int_2d_ptr << ", ";
    os << "int_3d_ptr=" << obj.int_3d_ptr << ", ";
    os << "int_1d_alloc=" << obj.int_1d_alloc << ", ";
    os << "int_2d_alloc=" << obj.int_2d_alloc << ", ";
    os << "int_3d_alloc=" << obj.int_3d_alloc << ", ";
    os << "int8_0d=" << obj.int8_0d << ", ";
    os << "int8_1d=" << obj.int8_1d << ", ";
    os << "int8_2d=" << obj.int8_2d << ", ";
    os << "int8_3d=" << obj.int8_3d << ", ";
    os << "int8_0d_ptr="; if (obj.int8_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.int8_0d_ptr; }; os << ", ";
    os << "int8_1d_ptr=" << obj.int8_1d_ptr << ", ";
    os << "int8_2d_ptr=" << obj.int8_2d_ptr << ", ";
    os << "int8_3d_ptr=" << obj.int8_3d_ptr << ", ";
    os << "int8_1d_alloc=" << obj.int8_1d_alloc << ", ";
    os << "int8_2d_alloc=" << obj.int8_2d_alloc << ", ";
    os << "int8_3d_alloc=" << obj.int8_3d_alloc << ", ";
    os << "logical_0d=" << obj.logical_0d << ", ";
    os << "logical_1d=" << obj.logical_1d << ", ";
    os << "logical_2d=" << obj.logical_2d << ", ";
    os << "logical_3d=" << obj.logical_3d << ", ";
    os << "logical_0d_ptr="; if (obj.logical_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.logical_0d_ptr; }; os << ", ";
    os << "type_0d=" << obj.type_0d << ", ";
    os << "type_1d=" << obj.type_1d << ", ";
    os << "type_2d=" << obj.type_2d << ", ";
    os << "type_3d=" << obj.type_3d << ", ";
    os << "type_0d_ptr="; if (obj.type_0d_ptr == nullptr) { os << "nullptr"; } else { os << obj.type_0d_ptr; }; os << ", ";
    os << "type_1d_ptr=" << obj.type_1d_ptr << ", ";
    os << "type_2d_ptr=" << obj.type_2d_ptr << ", ";
    os << "type_3d_ptr=" << obj.type_3d_ptr << ", ";
    os << "type_1d_alloc=" << obj.type_1d_alloc << ", ";
    os << "type_2d_alloc=" << obj.type_2d_alloc << ", ";
    os << "type_3d_alloc=" << obj.type_3d_alloc;
    os << "}";
    return os;
  }

  std::string repr() const {
    std::ostringstream os;
    os << this;
    return os.str();
  }
    
};

extern "C" void all_encompassing_to_c (const Opaque_all_encompassing_class*, CPP_all_encompassing&);
extern "C" void all_encompassing_to_f (const CPP_all_encompassing&, Opaque_all_encompassing_class*);

bool operator== (const CPP_all_encompassing&, const CPP_all_encompassing&);

//--------------------------------------------------------------------

#define CPP_BMAD_CLASSES
#endif
