name = "bmad-sim-utils"

[dependencies]
openmp = "*"
# TODO: any others available on the fpm registry? As-is, these will come from the
# system - or the current conda env as in my testing
# hdf5
# fftw
# lapack
# lapack95
# gsl
# fgsl

[fortran]
implicit-external = true
source-form = "default"  # default: "free" - but we have some fixed .f files along with free .f90 files

[build]
external-modules = [
  "hdf5",
  "fftw",
  "f95_lapack",
  "lapack",
  "lapack95",
  "gsl",
  "fgsl",
  "plplot",
  "mpi",
]

[library]
source-dir = "."
include-dir = "include"

[preprocess]
[preprocess.cpp]

# NOTE: this is to be set by the user/fpm
# macros = ["CESR_NOPLOT"]
# macros = ["CESR_PGPLOT"]
# macros = ["CESR_PLPLOT"]
suffixes = ["f90"]
