name = "bmad-sim-utils"

[dependencies]
openmp = "*"
# TODO: any others available on the fpm registry? As-is, these will come from the
# system - or the current conda env as in my testing
# hdf5
# fftw
# lapack
# lapack95
# gsl
# fgsl

[fortran]
implicit-external = true
source-form = "default"  # default: "free" - but we have some fixed .f files along with free .f90 files

[build]
external-modules = [
  "hdf5",
  "fftw",
  "f95_lapack",
  "lapack",
  "lapack95",
  "gsl",
  "fgsl",
  "plplot",
]

# [dependencies.toml-f]
# git = "https://github.com/toml-f/toml-f"
# rev = "2f5eaba864ff630ba0c3791126a3f811b6e437f3"

[library]
source-dir = "code"
# NOTE: this is not supported: https://github.com/fortran-lang/fpm/pull/847
# source-dir = [
#   "file",
#   "interfaces",
#   "io",
#   "math",
#   "matrix",
#   "misc",
#   "optimizers",
#   "plot",
#   "string",
#   "geodesic_lm",
#   "special_functions",
# ]
include-dir = "include"

[preprocess]
[preprocess.cpp]

# NOTE: noplot version
# macros = ["CESR_NOPLOT"]
# macros = ["CESR_PGPLOT"]
# macros = ["CESR_PLPLOT"]
suffixes = ["f90"]
