sources:
  - source_dir: ${ACC_ROOT_DIR}/bmad
    fortran_filename: ${ACC_ROOT_DIR}/bmad/code/bmad_json.f90
    yaml_filename: yaml/bmad_structs.yaml
    python_filename: python/bmad_structs.py
    python_import_name: bmad_structs
    function_prefix: bmad_
    skip_includes:
      - fftw3.f03

  - source_dir: ${ACC_ROOT_DIR}/sim_utils
    fortran_filename: ${ACC_ROOT_DIR}/sim_utils/misc/sim_utils_json.f90
    yaml_filename: yaml/sim_utils_structs.yaml
    python_filename: python/sim_utils_structs.py
    python_import_name: sim_utils_structs
    function_prefix: sim_utils_
    skip_includes:
      - fftw3.f03

  - source_dir: ${ACC_ROOT_DIR}/tao
    fortran_filename: ${ACC_ROOT_DIR}/tao/code/tao_json.f90
    yaml_filename: yaml/tao_structs.yaml
    python_filename: python/tao_structs.py
    python_import_name: tao_structs
    function_prefix: tao_
    skip_includes:
      - mpif.h

  - source_dir: ${ACC_ROOT_DIR}/forest
    fortran_filename: ${ACC_ROOT_DIR}/forest/code/forest_json.f90
    yaml_filename: yaml/forest_structs.yaml
    python_filename: python/forest_structs.py
    python_import_name: forest_structs
    function_prefix: forest_
    skip_structures:
      - c_dascratch
      - c_dalevel
    include_dirs:
      - ${ACC_ROOT_DIR}/forest/include
    skip_includes:
      - mpif.h
# config:
#   struct_aliases:
#     genfield: ptc_spin
#     fibre: ptc_spin
#     layout: ptc_spin
#     c_damap: ptc_spin
#     c_normal_form: ptc_spin
#     c_taylor: ptc_spin
#     quaternion_8: ptc_spin
#     probe_8: ptc_spin
#     internal_state: ptc_spin
