name = "bmad"

[fortran]
implicit-external = true
implicit-typing = true

[build]
external-modules = ["xraylib", "la_precision", "h5lt"]

[library]
source-dir = "."

[dependencies]
# openmp = "*"
# mpi = "*"
bmad-forest = { path = "../forest" }
bmad-sim-utils = { path = "../sim_utils" }
