name = "tao"

[fortran]
implicit-external = true
# required for 'mpi' dependency
implicit-typing = true

[build]
link = [
  "blas",
  "fftw3",
  "fftw3_omp",
  "fgsl",
  "gsl",
  "gslcblas",
  "hdf5",
  "hdf5_fortran",
  "hdf5_hl",
  "hdf5hl_fortran",
  "lapack",
  "lapack95",
  "xrl",
  "xrlf03",
  "readline",
]
external-modules = [
  # These aren't technically external, but the source seems to be inspected
  # prior to parsing which finds a 'use pgplot_interface' that should be
  # excluded by an #if
  # "pgplot_interface",
  # "plplot_interface",
]

[library]
source-dir = "."
# NOTE: this is not supported: https://github.com/fortran-lang/fpm/pull/847
# source-dir = [
#   "bmad/code",

[dependencies]
bmad = { path = "../bmad" }
bmad-sim-utils = { path = "../sim_utils" }
# bmad-sim-utils = { path = "../sim_utils",  = [
#   "CESR_PGPLOT",
# ] }

# bmad-sim-utils = { path = "../sim_utils", preprocess.cpp.macros = [
#   "CESR_PGPLOT",
# ] }
openmp = "*"
mpi = "*"
# [[executable]]
# name = "tao-noplot"
#
# [executable.dependencies]
# bmad-sim-utils = { path = "../sim_utils" }
# bmad-sim-utils-plot-noplot = { path = "../sim_utils/plot-noplot" }

[[executable]]
name = "tao-pgplot"
link = "pgplot"

# [executable.dependencies]
# bmad-sim-utils = { path = "../sim_utils" }
# bmad-sim-utils-plot-pgplot = { path = "../sim_utils/plot-pgplot" }

[preprocess]
[preprocess.cpp]

# NOTE: noplot version
# macros = ["CESR_NOPLOT"]
# macros = ["CESR_PGPLOT"]
# macros = ["CESR_PLPLOT"]
suffixes = ["f90"]
