
//+
// C++ classes definitions for Bmad / C++ structure interface.
//
// This file is generated as part of the Bmad/C++ interface code generation.
// The code generation files can be found in cpp_bmad_interface.
//
// DO NOT EDIT THIS FILE DIRECTLY! 
//-

#include <stdio.h>
#include <iostream>
#include "cpp_bmad_classes.h"

using namespace std;
using namespace Bmad;

//--------------------------------------------------------------
//--------------------------------------------------------------

extern "C" void test2_f_wake_lr (CPP_wake_lr&, bool&);

void set_CPP_wake_lr_test_pattern (CPP_wake_lr& C, int ix_patt) {

  auto rhs = 0;
  auto offset = 100 * ix_patt;

  // c_side.test_pat[integer8, 0, NOT]
  rhs = 1 + offset; C.aaa = rhs;

  // c_side.test_pat[integer, 0, NOT]
  rhs = 2 + offset; C.bbb = rhs;

  // c_side.test_pat[character, 0, NOT]
  C.file.resize(200);
  for (size_t i = 0; i < C.file.size(); i++)
    {int rhs = 101 + i + 3 + offset; C.file[i] = 'a' + rhs % 26;}
  // c_side.test_pat[real, 0, NOT]
  rhs = 4 + offset; C.t_ref = rhs;

  // c_side.test_pat[real, 0, NOT]
  rhs = 5 + offset; C.freq_spread = rhs;


}

//--------------------------------------------------------------

extern "C" void test_c_wake_lr (Opaque_wake_lr_class* F, bool& c_ok) {

  CPP_wake_lr C, C2;

  c_ok = true;

  wake_lr_to_c (F, C);
  set_CPP_wake_lr_test_pattern (C2, 1);

  cout << "" << endl;
  if (C == C2) {
    cout << " [1] wake_lr: C side convert F->C: Good" << endl;
  } else {
    cout << " [1] wake_lr: C SIDE CONVERT F->C: FAILED!" << endl;
    cout << " [1] C  = " << C << endl;
    cout << " [1] C2 = " << C2 << endl;
    c_ok = false;
  }

  set_CPP_wake_lr_test_pattern (C2, 2);
  bool c_ok2;
  test2_f_wake_lr (C2, c_ok2);
  if (!c_ok2) c_ok = false;

  set_CPP_wake_lr_test_pattern (C, 3);
  if (C == C2) {
    cout << " [3] wake_lr: F side convert F->C: Good" << endl;
  } else {
    cout << " [3] wake_lr: F SIDE CONVERT F->C: FAILED!" << endl;
    cout << " [3] C  = " << C << endl;
    cout << " [3] C2 = " << C2 << endl;
    c_ok = false;
  }

  set_CPP_wake_lr_test_pattern (C2, 4);
  wake_lr_to_f (C2, F);

  
}

//--------------------------------------------------------------
//--------------------------------------------------------------

extern "C" void test2_f_wake (CPP_wake&, bool&);

void set_CPP_wake_test_pattern (CPP_wake& C, int ix_patt) {

  auto rhs = 0;
  auto offset = 100 * ix_patt;

  // c_side.test_pat[type, 0, NOT]
  set_CPP_wake_lr_test_pattern(C.sr, ix_patt);


}

//--------------------------------------------------------------

extern "C" void test_c_wake (Opaque_wake_class* F, bool& c_ok) {

  CPP_wake C, C2;

  c_ok = true;

  wake_to_c (F, C);
  set_CPP_wake_test_pattern (C2, 1);

  cout << "" << endl;
  if (C == C2) {
    cout << " [1] wake: C side convert F->C: Good" << endl;
  } else {
    cout << " [1] wake: C SIDE CONVERT F->C: FAILED!" << endl;
    cout << " [1] C  = " << C << endl;
    cout << " [1] C2 = " << C2 << endl;
    c_ok = false;
  }

  set_CPP_wake_test_pattern (C2, 2);
  bool c_ok2;
  test2_f_wake (C2, c_ok2);
  if (!c_ok2) c_ok = false;

  set_CPP_wake_test_pattern (C, 3);
  if (C == C2) {
    cout << " [3] wake: F side convert F->C: Good" << endl;
  } else {
    cout << " [3] wake: F SIDE CONVERT F->C: FAILED!" << endl;
    cout << " [3] C  = " << C << endl;
    cout << " [3] C2 = " << C2 << endl;
    c_ok = false;
  }

  set_CPP_wake_test_pattern (C2, 4);
  wake_to_f (C2, F);

  
}

//--------------------------------------------------------------
//--------------------------------------------------------------

extern "C" void test2_f_all_encompassing (CPP_all_encompassing&, bool&);

void set_CPP_all_encompassing_test_pattern (CPP_all_encompassing& C, int ix_patt) {

  auto rhs = 0;
  auto offset = 100 * ix_patt;

  // c_side.test_pat[real, 0, NOT]
  rhs = 1 + offset; C.real_rp_0d = rhs;

  // c_side.test_pat[real, 1, NOT]
  for (size_t i = 0; i < C.real_rp_1d.size(); i++)
    {int rhs = 101 + i + 2 + offset; C.real_rp_1d[i] = rhs;}
  // c_side.test_pat[real, 2, NOT]
  for (size_t i = 0; i < C.real_rp_2d.size(); i++)  for (size_t j = 0; j < C.real_rp_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 3 + offset; C.real_rp_2d[i][j] = rhs;}
  // c_side.test_pat[real, 3, NOT]
  for (size_t i = 0; i < C.real_rp_3d.size(); i++)  for (size_t j = 0; j < C.real_rp_3d[0].size(); j++)   for (size_t k = 0; k < C.real_rp_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 4 + offset; C.real_rp_3d[i][j][k] = rhs;}
  // c_side.test_pat[real, 0, PTR]
  if (ix_patt < 3) 
    C.real_rp_0d_ptr = nullptr;
  else {
    C.real_rp_0d_ptr = make_shared<Real>();
    rhs = 5 + offset; (*C.real_rp_0d_ptr) = rhs;
  }
  // c_side.test_pat[real, 1, PTR]
  if (ix_patt < 3) 
    C.real_rp_1d_ptr.resize(0);
  else {
    C.real_rp_1d_ptr.resize(3);
    for (size_t i = 0; i < C.real_rp_1d_ptr.size(); i++)
      {int rhs = 101 + i + 7 + offset; C.real_rp_1d_ptr[i] = rhs;}  }

  // c_side.test_pat[real, 2, PTR]
  if (ix_patt < 3) 
    C.real_rp_2d_ptr.resize(0);
  else {
    C.real_rp_2d_ptr.resize(3);
    for (size_t i = 0; i < C.real_rp_2d_ptr.size(); i++)
      C.real_rp_2d_ptr[i].resize(2);
    for (size_t i = 0; i < C.real_rp_2d_ptr.size(); i++)  for (size_t j = 0; j < C.real_rp_2d_ptr[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 9 + offset; C.real_rp_2d_ptr[i][j] = rhs;}  }

  // c_side.test_pat[real, 3, PTR]
  if (ix_patt < 3) 
    C.real_rp_3d_ptr.resize(0);
  else {
    C.real_rp_3d_ptr.resize(3);
    for (size_t i = 0; i < C.real_rp_3d_ptr.size(); i++) {
      C.real_rp_3d_ptr[i].resize(2);
      for (size_t j = 0; j < C.real_rp_3d_ptr[0].size(); j++) {
        C.real_rp_3d_ptr[i][j].resize(1);
        for (size_t k = 0; k < C.real_rp_3d_ptr[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 12 + offset;
          C.real_rp_3d_ptr[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[real, 1, ALLOC]
  if (ix_patt < 3) 
    C.real_rp_1d_alloc.resize(0);
  else {
    C.real_rp_1d_alloc.resize(3);
    for (size_t i = 0; i < C.real_rp_1d_alloc.size(); i++)
      {int rhs = 101 + i + 16 + offset; C.real_rp_1d_alloc[i] = rhs;}  }

  // c_side.test_pat[real, 2, ALLOC]
  if (ix_patt < 3) 
    C.real_rp_2d_alloc.resize(0);
  else {
    C.real_rp_2d_alloc.resize(3);
    for (size_t i = 0; i < C.real_rp_2d_alloc.size(); i++)
      C.real_rp_2d_alloc[i].resize(2);
    for (size_t i = 0; i < C.real_rp_2d_alloc.size(); i++)  for (size_t j = 0; j < C.real_rp_2d_alloc[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 18 + offset; C.real_rp_2d_alloc[i][j] = rhs;}  }

  // c_side.test_pat[real, 3, ALLOC]
  if (ix_patt < 3) 
    C.real_rp_3d_alloc.resize(0);
  else {
    C.real_rp_3d_alloc.resize(3);
    for (size_t i = 0; i < C.real_rp_3d_alloc.size(); i++) {
      C.real_rp_3d_alloc[i].resize(2);
      for (size_t j = 0; j < C.real_rp_3d_alloc[0].size(); j++) {
        C.real_rp_3d_alloc[i][j].resize(1);
        for (size_t k = 0; k < C.real_rp_3d_alloc[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 21 + offset;
          C.real_rp_3d_alloc[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[real, 0, NOT]
  rhs = 25 + offset; C.real_dp_0d = rhs;

  // c_side.test_pat[real, 1, NOT]
  for (size_t i = 0; i < C.real_dp_1d.size(); i++)
    {int rhs = 101 + i + 26 + offset; C.real_dp_1d[i] = rhs;}
  // c_side.test_pat[real, 2, NOT]
  for (size_t i = 0; i < C.real_dp_2d.size(); i++)  for (size_t j = 0; j < C.real_dp_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 27 + offset; C.real_dp_2d[i][j] = rhs;}
  // c_side.test_pat[real, 3, NOT]
  for (size_t i = 0; i < C.real_dp_3d.size(); i++)  for (size_t j = 0; j < C.real_dp_3d[0].size(); j++)   for (size_t k = 0; k < C.real_dp_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 28 + offset; C.real_dp_3d[i][j][k] = rhs;}
  // c_side.test_pat[real, 0, PTR]
  if (ix_patt < 3) 
    C.real_dp_0d_ptr = nullptr;
  else {
    C.real_dp_0d_ptr = make_shared<Real>();
    rhs = 29 + offset; (*C.real_dp_0d_ptr) = rhs;
  }
  // c_side.test_pat[real, 1, PTR]
  if (ix_patt < 3) 
    C.real_dp_1d_ptr.resize(0);
  else {
    C.real_dp_1d_ptr.resize(3);
    for (size_t i = 0; i < C.real_dp_1d_ptr.size(); i++)
      {int rhs = 101 + i + 31 + offset; C.real_dp_1d_ptr[i] = rhs;}  }

  // c_side.test_pat[real, 2, PTR]
  if (ix_patt < 3) 
    C.real_dp_2d_ptr.resize(0);
  else {
    C.real_dp_2d_ptr.resize(3);
    for (size_t i = 0; i < C.real_dp_2d_ptr.size(); i++)
      C.real_dp_2d_ptr[i].resize(2);
    for (size_t i = 0; i < C.real_dp_2d_ptr.size(); i++)  for (size_t j = 0; j < C.real_dp_2d_ptr[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 33 + offset; C.real_dp_2d_ptr[i][j] = rhs;}  }

  // c_side.test_pat[real, 3, PTR]
  if (ix_patt < 3) 
    C.real_dp_3d_ptr.resize(0);
  else {
    C.real_dp_3d_ptr.resize(3);
    for (size_t i = 0; i < C.real_dp_3d_ptr.size(); i++) {
      C.real_dp_3d_ptr[i].resize(2);
      for (size_t j = 0; j < C.real_dp_3d_ptr[0].size(); j++) {
        C.real_dp_3d_ptr[i][j].resize(1);
        for (size_t k = 0; k < C.real_dp_3d_ptr[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 36 + offset;
          C.real_dp_3d_ptr[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[real, 1, ALLOC]
  if (ix_patt < 3) 
    C.real_dp_1d_alloc.resize(0);
  else {
    C.real_dp_1d_alloc.resize(3);
    for (size_t i = 0; i < C.real_dp_1d_alloc.size(); i++)
      {int rhs = 101 + i + 40 + offset; C.real_dp_1d_alloc[i] = rhs;}  }

  // c_side.test_pat[real, 2, ALLOC]
  if (ix_patt < 3) 
    C.real_dp_2d_alloc.resize(0);
  else {
    C.real_dp_2d_alloc.resize(3);
    for (size_t i = 0; i < C.real_dp_2d_alloc.size(); i++)
      C.real_dp_2d_alloc[i].resize(2);
    for (size_t i = 0; i < C.real_dp_2d_alloc.size(); i++)  for (size_t j = 0; j < C.real_dp_2d_alloc[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 42 + offset; C.real_dp_2d_alloc[i][j] = rhs;}  }

  // c_side.test_pat[real, 3, ALLOC]
  if (ix_patt < 3) 
    C.real_dp_3d_alloc.resize(0);
  else {
    C.real_dp_3d_alloc.resize(3);
    for (size_t i = 0; i < C.real_dp_3d_alloc.size(); i++) {
      C.real_dp_3d_alloc[i].resize(2);
      for (size_t j = 0; j < C.real_dp_3d_alloc[0].size(); j++) {
        C.real_dp_3d_alloc[i][j].resize(1);
        for (size_t k = 0; k < C.real_dp_3d_alloc[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 45 + offset;
          C.real_dp_3d_alloc[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[complex, 0, NOT]
  rhs = 49 + offset; C.complex_dp_0d = Complex(rhs, 100+rhs);

  // c_side.test_pat[complex, 1, NOT]
  for (size_t i = 0; i < C.complex_dp_1d.size(); i++)
    {int rhs = 101 + i + 50 + offset; C.complex_dp_1d[i] = Complex(rhs, 100+rhs);}
  // c_side.test_pat[complex, 2, NOT]
  for (size_t i = 0; i < C.complex_dp_2d.size(); i++)  for (size_t j = 0; j < C.complex_dp_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 51 + offset; C.complex_dp_2d[i][j] = Complex(rhs, 100+rhs);}
  // c_side.test_pat[complex, 3, NOT]
  for (size_t i = 0; i < C.complex_dp_3d.size(); i++)  for (size_t j = 0; j < C.complex_dp_3d[0].size(); j++)   for (size_t k = 0; k < C.complex_dp_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 52 + offset; C.complex_dp_3d[i][j][k] = Complex(rhs, 100+rhs);}
  // c_side.test_pat[complex, 0, PTR]
  if (ix_patt < 3) 
    C.complex_dp_0d_ptr = nullptr;
  else {
    C.complex_dp_0d_ptr = make_shared<Complex>();
    rhs = 53 + offset; (*C.complex_dp_0d_ptr) = Complex(rhs, 100+rhs);
  }
  // c_side.test_pat[complex, 1, PTR]
  if (ix_patt < 3) 
    C.complex_dp_1d_ptr.resize(0);
  else {
    C.complex_dp_1d_ptr.resize(3);
    for (size_t i = 0; i < C.complex_dp_1d_ptr.size(); i++)
      {int rhs = 101 + i + 55 + offset; C.complex_dp_1d_ptr[i] = Complex(rhs, 100+rhs);}  }

  // c_side.test_pat[complex, 2, PTR]
  if (ix_patt < 3) 
    C.complex_dp_2d_ptr.resize(0);
  else {
    C.complex_dp_2d_ptr.resize(3);
    for (size_t i = 0; i < C.complex_dp_2d_ptr.size(); i++)
      C.complex_dp_2d_ptr[i].resize(2);
    for (size_t i = 0; i < C.complex_dp_2d_ptr.size(); i++)  for (size_t j = 0; j < C.complex_dp_2d_ptr[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 57 + offset; C.complex_dp_2d_ptr[i][j] = Complex(rhs, 100+rhs);}  }

  // c_side.test_pat[complex, 3, PTR]
  if (ix_patt < 3) 
    C.complex_dp_3d_ptr.resize(0);
  else {
    C.complex_dp_3d_ptr.resize(3);
    for (size_t i = 0; i < C.complex_dp_3d_ptr.size(); i++) {
      C.complex_dp_3d_ptr[i].resize(2);
      for (size_t j = 0; j < C.complex_dp_3d_ptr[0].size(); j++) {
        C.complex_dp_3d_ptr[i][j].resize(1);
        for (size_t k = 0; k < C.complex_dp_3d_ptr[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 60 + offset;
          C.complex_dp_3d_ptr[i][j][k] = Complex(rhs, 100+rhs);
        }
      }
    }
  }

  // c_side.test_pat[complex, 1, ALLOC]
  if (ix_patt < 3) 
    C.complex_dp_1d_alloc.resize(0);
  else {
    C.complex_dp_1d_alloc.resize(3);
    for (size_t i = 0; i < C.complex_dp_1d_alloc.size(); i++)
      {int rhs = 101 + i + 64 + offset; C.complex_dp_1d_alloc[i] = Complex(rhs, 100+rhs);}  }

  // c_side.test_pat[complex, 2, ALLOC]
  if (ix_patt < 3) 
    C.complex_dp_2d_alloc.resize(0);
  else {
    C.complex_dp_2d_alloc.resize(3);
    for (size_t i = 0; i < C.complex_dp_2d_alloc.size(); i++)
      C.complex_dp_2d_alloc[i].resize(2);
    for (size_t i = 0; i < C.complex_dp_2d_alloc.size(); i++)  for (size_t j = 0; j < C.complex_dp_2d_alloc[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 66 + offset; C.complex_dp_2d_alloc[i][j] = Complex(rhs, 100+rhs);}  }

  // c_side.test_pat[complex, 3, ALLOC]
  if (ix_patt < 3) 
    C.complex_dp_3d_alloc.resize(0);
  else {
    C.complex_dp_3d_alloc.resize(3);
    for (size_t i = 0; i < C.complex_dp_3d_alloc.size(); i++) {
      C.complex_dp_3d_alloc[i].resize(2);
      for (size_t j = 0; j < C.complex_dp_3d_alloc[0].size(); j++) {
        C.complex_dp_3d_alloc[i][j].resize(1);
        for (size_t k = 0; k < C.complex_dp_3d_alloc[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 69 + offset;
          C.complex_dp_3d_alloc[i][j][k] = Complex(rhs, 100+rhs);
        }
      }
    }
  }

  // c_side.test_pat[integer, 0, NOT]
  rhs = 73 + offset; C.int_0d = rhs;

  // c_side.test_pat[integer, 1, NOT]
  for (size_t i = 0; i < C.int_1d.size(); i++)
    {int rhs = 101 + i + 74 + offset; C.int_1d[i] = rhs;}
  // c_side.test_pat[integer, 2, NOT]
  for (size_t i = 0; i < C.int_2d.size(); i++)  for (size_t j = 0; j < C.int_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 75 + offset; C.int_2d[i][j] = rhs;}
  // c_side.test_pat[integer, 3, NOT]
  for (size_t i = 0; i < C.int_3d.size(); i++)  for (size_t j = 0; j < C.int_3d[0].size(); j++)   for (size_t k = 0; k < C.int_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 76 + offset; C.int_3d[i][j][k] = rhs;}
  // c_side.test_pat[integer, 0, PTR]
  if (ix_patt < 3) 
    C.int_0d_ptr = nullptr;
  else {
    C.int_0d_ptr = make_shared<Int>();
    rhs = 77 + offset; (*C.int_0d_ptr) = rhs;
  }
  // c_side.test_pat[integer, 1, PTR]
  if (ix_patt < 3) 
    C.int_1d_ptr.resize(0);
  else {
    C.int_1d_ptr.resize(3);
    for (size_t i = 0; i < C.int_1d_ptr.size(); i++)
      {int rhs = 101 + i + 79 + offset; C.int_1d_ptr[i] = rhs;}  }

  // c_side.test_pat[integer, 2, PTR]
  if (ix_patt < 3) 
    C.int_2d_ptr.resize(0);
  else {
    C.int_2d_ptr.resize(3);
    for (size_t i = 0; i < C.int_2d_ptr.size(); i++)
      C.int_2d_ptr[i].resize(2);
    for (size_t i = 0; i < C.int_2d_ptr.size(); i++)  for (size_t j = 0; j < C.int_2d_ptr[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 81 + offset; C.int_2d_ptr[i][j] = rhs;}  }

  // c_side.test_pat[integer, 3, PTR]
  if (ix_patt < 3) 
    C.int_3d_ptr.resize(0);
  else {
    C.int_3d_ptr.resize(3);
    for (size_t i = 0; i < C.int_3d_ptr.size(); i++) {
      C.int_3d_ptr[i].resize(2);
      for (size_t j = 0; j < C.int_3d_ptr[0].size(); j++) {
        C.int_3d_ptr[i][j].resize(1);
        for (size_t k = 0; k < C.int_3d_ptr[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 84 + offset;
          C.int_3d_ptr[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[integer, 1, ALLOC]
  if (ix_patt < 3) 
    C.int_1d_alloc.resize(0);
  else {
    C.int_1d_alloc.resize(3);
    for (size_t i = 0; i < C.int_1d_alloc.size(); i++)
      {int rhs = 101 + i + 88 + offset; C.int_1d_alloc[i] = rhs;}  }

  // c_side.test_pat[integer, 2, ALLOC]
  if (ix_patt < 3) 
    C.int_2d_alloc.resize(0);
  else {
    C.int_2d_alloc.resize(3);
    for (size_t i = 0; i < C.int_2d_alloc.size(); i++)
      C.int_2d_alloc[i].resize(2);
    for (size_t i = 0; i < C.int_2d_alloc.size(); i++)  for (size_t j = 0; j < C.int_2d_alloc[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 90 + offset; C.int_2d_alloc[i][j] = rhs;}  }

  // c_side.test_pat[integer, 3, ALLOC]
  if (ix_patt < 3) 
    C.int_3d_alloc.resize(0);
  else {
    C.int_3d_alloc.resize(3);
    for (size_t i = 0; i < C.int_3d_alloc.size(); i++) {
      C.int_3d_alloc[i].resize(2);
      for (size_t j = 0; j < C.int_3d_alloc[0].size(); j++) {
        C.int_3d_alloc[i][j].resize(1);
        for (size_t k = 0; k < C.int_3d_alloc[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 93 + offset;
          C.int_3d_alloc[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[integer8, 0, NOT]
  rhs = 97 + offset; C.int8_0d = rhs;

  // c_side.test_pat[integer8, 1, NOT]
  for (size_t i = 0; i < C.int8_1d.size(); i++)
    {int rhs = 101 + i + 98 + offset; C.int8_1d[i] = rhs;}
  // c_side.test_pat[integer8, 2, NOT]
  for (size_t i = 0; i < C.int8_2d.size(); i++)  for (size_t j = 0; j < C.int8_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 99 + offset; C.int8_2d[i][j] = rhs;}
  // c_side.test_pat[integer8, 3, NOT]
  for (size_t i = 0; i < C.int8_3d.size(); i++)  for (size_t j = 0; j < C.int8_3d[0].size(); j++)   for (size_t k = 0; k < C.int8_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 100 + offset; C.int8_3d[i][j][k] = rhs;}
  // c_side.test_pat[integer8, 0, PTR]
  if (ix_patt < 3) 
    C.int8_0d_ptr = nullptr;
  else {
    C.int8_0d_ptr = make_shared<Int8>();
    rhs = 101 + offset; (*C.int8_0d_ptr) = rhs;
  }
  // c_side.test_pat[integer8, 1, PTR]
  if (ix_patt < 3) 
    C.int8_1d_ptr.resize(0);
  else {
    C.int8_1d_ptr.resize(3);
    for (size_t i = 0; i < C.int8_1d_ptr.size(); i++)
      {int rhs = 101 + i + 103 + offset; C.int8_1d_ptr[i] = rhs;}  }

  // c_side.test_pat[integer8, 2, PTR]
  if (ix_patt < 3) 
    C.int8_2d_ptr.resize(0);
  else {
    C.int8_2d_ptr.resize(3);
    for (size_t i = 0; i < C.int8_2d_ptr.size(); i++)
      C.int8_2d_ptr[i].resize(2);
    for (size_t i = 0; i < C.int8_2d_ptr.size(); i++)  for (size_t j = 0; j < C.int8_2d_ptr[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 105 + offset; C.int8_2d_ptr[i][j] = rhs;}  }

  // c_side.test_pat[integer8, 3, PTR]
  if (ix_patt < 3) 
    C.int8_3d_ptr.resize(0);
  else {
    C.int8_3d_ptr.resize(3);
    for (size_t i = 0; i < C.int8_3d_ptr.size(); i++) {
      C.int8_3d_ptr[i].resize(2);
      for (size_t j = 0; j < C.int8_3d_ptr[0].size(); j++) {
        C.int8_3d_ptr[i][j].resize(1);
        for (size_t k = 0; k < C.int8_3d_ptr[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 108 + offset;
          C.int8_3d_ptr[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[integer8, 1, ALLOC]
  if (ix_patt < 3) 
    C.int8_1d_alloc.resize(0);
  else {
    C.int8_1d_alloc.resize(3);
    for (size_t i = 0; i < C.int8_1d_alloc.size(); i++)
      {int rhs = 101 + i + 112 + offset; C.int8_1d_alloc[i] = rhs;}  }

  // c_side.test_pat[integer8, 2, ALLOC]
  if (ix_patt < 3) 
    C.int8_2d_alloc.resize(0);
  else {
    C.int8_2d_alloc.resize(3);
    for (size_t i = 0; i < C.int8_2d_alloc.size(); i++)
      C.int8_2d_alloc[i].resize(2);
    for (size_t i = 0; i < C.int8_2d_alloc.size(); i++)  for (size_t j = 0; j < C.int8_2d_alloc[0].size(); j++) 
      {int rhs = 101 + i + 10*(j+1) + 114 + offset; C.int8_2d_alloc[i][j] = rhs;}  }

  // c_side.test_pat[integer8, 3, ALLOC]
  if (ix_patt < 3) 
    C.int8_3d_alloc.resize(0);
  else {
    C.int8_3d_alloc.resize(3);
    for (size_t i = 0; i < C.int8_3d_alloc.size(); i++) {
      C.int8_3d_alloc[i].resize(2);
      for (size_t j = 0; j < C.int8_3d_alloc[0].size(); j++) {
        C.int8_3d_alloc[i][j].resize(1);
        for (size_t k = 0; k < C.int8_3d_alloc[0][0].size(); k++) {
          auto rhs = 101 + i + 10*(j+1) + 100*(k+1) + 117 + offset;
          C.int8_3d_alloc[i][j][k] = rhs;
        }
      }
    }
  }

  // c_side.test_pat[logical, 0, NOT]
  rhs = 121 + offset; C.logical_0d = (rhs % 2 == 0);

  // c_side.test_pat[logical, 1, NOT]
  for (size_t i = 0; i < C.logical_1d.size(); i++)
    {int rhs = 101 + i + 122 + offset; C.logical_1d[i] = (rhs % 2 == 0);}
  // c_side.test_pat[logical, 2, NOT]
  for (size_t i = 0; i < C.logical_2d.size(); i++)  for (size_t j = 0; j < C.logical_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 123 + offset; C.logical_2d[i][j] = (rhs % 2 == 0);}
  // c_side.test_pat[logical, 3, NOT]
  for (size_t i = 0; i < C.logical_3d.size(); i++)  for (size_t j = 0; j < C.logical_3d[0].size(); j++)   for (size_t k = 0; k < C.logical_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 124 + offset; C.logical_3d[i][j][k] = (rhs % 2 == 0);}
  // c_side.test_pat[logical, 0, PTR]
  if (ix_patt < 3) 
    C.logical_0d_ptr = nullptr;
  else {
    C.logical_0d_ptr = make_shared<Bool>();
    rhs = 125 + offset; (*C.logical_0d_ptr) = (rhs % 2 == 0);
  }
  // c_side.test_pat[type, 0, NOT]
  set_CPP_wake_lr_test_pattern(C.type_0d, ix_patt);

  // c_side.test_pat[type, 1, NOT]
  for (size_t i = 0; i < C.type_1d.size(); i++)
    {int rhs = 101 + i + 128 + offset; set_CPP_wake_lr_test_pattern(C.type_1d[i], ix_patt+i+1);}
  // c_side.test_pat[type, 2, NOT]
  for (size_t i = 0; i < C.type_2d.size(); i++)  for (size_t j = 0; j < C.type_2d[0].size(); j++) 
    {int rhs = 101 + i + 10*(j+1) + 129 + offset; set_CPP_wake_lr_test_pattern(*C.type_2d[i][j], ix_patt+i+1+10*(j+1));}
  // c_side.test_pat[type, 3, NOT]
  for (size_t i = 0; i < C.type_3d.size(); i++)  for (size_t j = 0; j < C.type_3d[0].size(); j++)   for (size_t k = 0; k < C.type_3d[0][0].size(); k++)
    {int rhs = 101 + i + 10*(j+1) + 100*(k+1) + 130 + offset; set_CPP_wake_lr_test_pattern(*C.type_3d[i][j][k], ix_patt+i+1+10*(j+1)+100*(k+1));}
  // c_side.test_pat[type, 0, PTR]
  if (ix_patt < 3) 
    C.type_0d_ptr = nullptr;
  else {
    C.type_0d_ptr = make_shared<CPP_wake_lr>();
    set_CPP_wake_lr_test_pattern((*C.type_0d_ptr), ix_patt);
  }
  // c_side.test_pat[type, 1, PTR]
  if (ix_patt < 3) 
    C.type_1d_ptr.resize(0);
  else {
    C.type_1d_ptr.resize(3);
    for (size_t i = 0; i < C.type_1d_ptr.size(); i++)  {set_CPP_wake_lr_test_pattern(C.type_1d_ptr[i], ix_patt+i+1);}
  }

  // c_side.test_pat[type, 2, PTR]
  if (ix_patt < 3) 
    C.type_2d_ptr.resize(0);
  else {
    C.type_2d_ptr.resize(3);
    for (size_t i = 0; i < C.type_2d_ptr.size(); i++) {
      C.type_2d_ptr[i].resize(2);

      for (size_t j = 0; j < C.type_2d_ptr[0].size(); j++) {
        auto &item = C.type_2d_ptr[i][j];
        set_CPP_wake_lr_test_pattern(item, ix_patt+i+2*j+3);
      }
    }
  }

  // c_side.test_pat[type, 3, PTR]
  if (ix_patt < 3) 
    C.type_3d_ptr.resize(0);
  else {
    C.type_3d_ptr.resize(3);
    for (size_t i = 0; i < C.type_3d_ptr.size(); i++) {
      C.type_3d_ptr[i].resize(2);
      for (size_t j = 0; j < C.type_3d_ptr[0].size(); j++) {
        C.type_3d_ptr[i][j].resize(1);
        for (size_t k = 0; k < C.type_3d_ptr[0][0].size(); k++) {
          // C.type_3d_ptr[i][j][k] = make_shared<CPP_wake_lr>();
          set_CPP_wake_lr_test_pattern(C.type_3d_ptr[i][j][k], ix_patt+i+2*j+3*k+6);
        }
      }
    }
  }

  // c_side.test_pat[type, 1, ALLOC]
  if (ix_patt < 3) 
    C.type_1d_alloc.resize(0);
  else {
    C.type_1d_alloc.resize(3);
    for (size_t i = 0; i < C.type_1d_alloc.size(); i++)  {set_CPP_wake_lr_test_pattern(C.type_1d_alloc[i], ix_patt+i+1);}
  }

  // c_side.test_pat[type, 2, ALLOC]
  if (ix_patt < 3) 
    C.type_2d_alloc.resize(0);
  else {
    C.type_2d_alloc.resize(3);
    for (size_t i = 0; i < C.type_2d_alloc.size(); i++) {
      C.type_2d_alloc[i].resize(2);

      for (size_t j = 0; j < C.type_2d_alloc[0].size(); j++) {
        auto &item = C.type_2d_alloc[i][j];
        set_CPP_wake_lr_test_pattern(item, ix_patt+i+2*j+3);
      }
    }
  }

  // c_side.test_pat[type, 3, ALLOC]
  if (ix_patt < 3) 
    C.type_3d_alloc.resize(0);
  else {
    C.type_3d_alloc.resize(3);
    for (size_t i = 0; i < C.type_3d_alloc.size(); i++) {
      C.type_3d_alloc[i].resize(2);
      for (size_t j = 0; j < C.type_3d_alloc[0].size(); j++) {
        C.type_3d_alloc[i][j].resize(1);
        for (size_t k = 0; k < C.type_3d_alloc[0][0].size(); k++) {
          // C.type_3d_alloc[i][j][k] = make_shared<CPP_wake_lr>();
          set_CPP_wake_lr_test_pattern(C.type_3d_alloc[i][j][k], ix_patt+i+2*j+3*k+6);
        }
      }
    }
  }


}

//--------------------------------------------------------------

extern "C" void test_c_all_encompassing (Opaque_all_encompassing_class* F, bool& c_ok) {

  CPP_all_encompassing C, C2;

  c_ok = true;

  all_encompassing_to_c (F, C);
  set_CPP_all_encompassing_test_pattern (C2, 1);

  cout << "" << endl;
  if (C == C2) {
    cout << " [1] all_encompassing: C side convert F->C: Good" << endl;
  } else {
    cout << " [1] all_encompassing: C SIDE CONVERT F->C: FAILED!" << endl;
    cout << " [1] C  = " << C << endl;
    cout << " [1] C2 = " << C2 << endl;
    c_ok = false;
  }

  set_CPP_all_encompassing_test_pattern (C2, 2);
  bool c_ok2;
  test2_f_all_encompassing (C2, c_ok2);
  if (!c_ok2) c_ok = false;

  set_CPP_all_encompassing_test_pattern (C, 3);
  if (C == C2) {
    cout << " [3] all_encompassing: F side convert F->C: Good" << endl;
  } else {
    cout << " [3] all_encompassing: F SIDE CONVERT F->C: FAILED!" << endl;
    cout << " [3] C  = " << C << endl;
    cout << " [3] C2 = " << C2 << endl;
    c_ok = false;
  }

  set_CPP_all_encompassing_test_pattern (C2, 4);
  all_encompassing_to_f (C2, F);

  
}
