name = "bmad-bsim"

[library]
source-dir = "all_code"
# NOTE: this is not supported: https://github.com/fortran-lang/fpm/pull/847
# source-dir = [
#   "bmad/code",
[dependencies]
# openmp = "*"
# mpi = "*"
# bmad-forest = { path = "../forest" }
# bmad-sim-utils = { path = "../sim_utils" }
bmad = { path = "../" }

# [[executable]]
# name = "compute-pi-openmp"
