name = "bmad-forest"

[dependencies]
openmp = "*"
# hdf5
# fftw
# lapack
# lapack95
# gsl
# fgsl

[fortran]
implicit-external = true

[build]
external-modules = ["hdf5", "fftw", "lapack", "lapack95", "gsl", "fgsl"]

[library]
source-dir = "code"
include-dir = "include"
