!+
! Module tao_equality_mod
!
! This module defines a set of functions which overload the equality operator ("==").
! These functions test for equality between instances of a given structure. 
!
! This file is generated as a by product of the Bmad/C++ interface code generation
! The code generation files can be found in cpp_bmad_interface.
!
! DO NOT EDIT THIS FILE DIRECTLY! 
!- 

module tao_equality_mod
use equality_mod


interface operator (==)
  module procedure eq_tao_spin_dn_dpz, eq_tao_lat_sigma, eq_tao_spin_ele, eq_tao_plot_cache, eq_tao_spin_polarization
  module procedure eq_tao_lattice_branch, eq_tao_model_element, eq_tao_beam_branch, eq_tao_d1_data, eq_tao_lattice
  module procedure eq_tao_beam_uni, eq_tao_dynamic_aperture, eq_tao_model_branch, eq_tao_d2_data, eq_tao_spin_map
  module procedure eq_tao_data, eq_tao_ping_scale, eq_tao_universe_calc, eq_tao_universe
end interface

contains


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_spin_dn_dpz (f1, f2) result (is_eq)

use tao_struct, only: tao_spin_dn_dpz_struct
implicit none

type(tao_spin_dn_dpz_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[1D_NOT_real]
is_eq = is_eq .and. all(f1%vec == f2%vec)
!! f_side.equality_test[2D_NOT_real]
is_eq = is_eq .and. all(f1%partial == f2%partial)
!! f_side.equality_test[2D_NOT_real]
is_eq = is_eq .and. all(f1%partial2 == f2%partial2)

end function eq_tao_spin_dn_dpz


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_lat_sigma (f1, f2) result (is_eq)

use tao_struct, only: tao_lat_sigma_struct
implicit none

type(tao_lat_sigma_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[2D_NOT_real]
is_eq = is_eq .and. all(f1%mat == f2%mat)

end function eq_tao_lat_sigma


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_spin_ele (f1, f2) result (is_eq)

use tao_struct, only: tao_spin_ele_struct
implicit none

type(tao_spin_ele_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%dn_dpz == f2%dn_dpz)
!! f_side.equality_test[1D_NOT_real]
is_eq = is_eq .and. all(f1%orb_eigen_val == f2%orb_eigen_val)
!! f_side.equality_test[2D_NOT_real]
is_eq = is_eq .and. all(f1%orb_eigen_vec == f2%orb_eigen_vec)
!! f_side.equality_test[2D_NOT_real]
is_eq = is_eq .and. all(f1%spin_eigen_vec == f2%spin_eigen_vec)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%valid .eqv. f2%valid)

end function eq_tao_spin_ele


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_plot_cache (f1, f2) result (is_eq)

use tao_struct, only: tao_plot_cache_struct
implicit none

type(tao_plot_cache_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%ele_to_s == f2%ele_to_s)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%orbit == f2%orbit)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%err .eqv. f2%err)

end function eq_tao_plot_cache


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_spin_polarization (f1, f2) result (is_eq)

use tao_struct, only: tao_spin_polarization_struct
implicit none

type(tao_spin_polarization_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%tune == f2%tune)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%pol_limit_st == f2%pol_limit_st)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%pol_limit_dk == f2%pol_limit_dk)
!! f_side.equality_test[1D_NOT_real]
is_eq = is_eq .and. all(f1%pol_limit_dk_partial == f2%pol_limit_dk_partial)
!! f_side.equality_test[1D_NOT_real]
is_eq = is_eq .and. all(f1%pol_limit_dk_partial2 == f2%pol_limit_dk_partial2)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%pol_rate_bks == f2%pol_rate_bks)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%depol_rate == f2%depol_rate)
!! f_side.equality_test[1D_NOT_real]
is_eq = is_eq .and. all(f1%depol_rate_partial == f2%depol_rate_partial)
!! f_side.equality_test[1D_NOT_real]
is_eq = is_eq .and. all(f1%depol_rate_partial2 == f2%depol_rate_partial2)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%integral_bn == f2%integral_bn)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%integral_bdn == f2%integral_bdn)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%integral_1ns == f2%integral_1ns)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%integral_dn2 == f2%integral_dn2)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%valid .eqv. f2%valid)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%q_1turn == f2%q_1turn)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%q_ele) .eqv. allocated(f2%q_ele))
if (.not. is_eq) return
if (allocated(f1%q_ele)) is_eq = all(shape(f1%q_ele) == shape(f2%q_ele))
if (.not. is_eq) return
if (allocated(f1%q_ele)) is_eq = all(f1%q_ele == f2%q_ele)

end function eq_tao_spin_polarization


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_lattice_branch (f1, f2) result (is_eq)

use tao_struct, only: tao_lattice_branch_struct
implicit none

type(tao_lattice_branch_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_PTR_type]
is_eq = is_eq .and. (associated(f1%tao_lat) .eqv. associated(f2%tao_lat))
if (.not. is_eq) return
if (associated(f1%tao_lat)) is_eq = (f1%tao_lat == f2%tao_lat)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%lat_sigma) .eqv. allocated(f2%lat_sigma))
if (.not. is_eq) return
if (allocated(f1%lat_sigma)) is_eq = all(shape(f1%lat_sigma) == shape(f2%lat_sigma))
if (.not. is_eq) return
if (allocated(f1%lat_sigma)) is_eq = all(f1%lat_sigma == f2%lat_sigma)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%spin_ele) .eqv. allocated(f2%spin_ele))
if (.not. is_eq) return
if (allocated(f1%spin_ele)) is_eq = all(shape(f1%spin_ele) == shape(f2%spin_ele))
if (.not. is_eq) return
if (allocated(f1%spin_ele)) is_eq = all(f1%spin_ele == f2%spin_ele)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%bunch_params) .eqv. allocated(f2%bunch_params))
if (.not. is_eq) return
if (allocated(f1%bunch_params)) is_eq = all(shape(f1%bunch_params) == shape(f2%bunch_params))
if (.not. is_eq) return
if (allocated(f1%bunch_params)) is_eq = all(f1%bunch_params == f2%bunch_params)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%bunch_params_comb) .eqv. allocated(f2%bunch_params_comb))
if (.not. is_eq) return
if (allocated(f1%bunch_params_comb)) is_eq = all(shape(f1%bunch_params_comb) == shape(f2%bunch_params_comb))
if (.not. is_eq) return
if (allocated(f1%bunch_params_comb)) is_eq = all(f1%bunch_params_comb == f2%bunch_params_comb)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%orbit) .eqv. allocated(f2%orbit))
if (.not. is_eq) return
if (allocated(f1%orbit)) is_eq = all(shape(f1%orbit) == shape(f2%orbit))
if (.not. is_eq) return
if (allocated(f1%orbit)) is_eq = all(f1%orbit == f2%orbit)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%plot_cache) .eqv. allocated(f2%plot_cache))
if (.not. is_eq) return
if (allocated(f1%plot_cache)) is_eq = all(shape(f1%plot_cache) == shape(f2%plot_cache))
if (.not. is_eq) return
if (allocated(f1%plot_cache)) is_eq = all(f1%plot_cache == f2%plot_cache)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%spin == f2%spin)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%srdt == f2%srdt)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%orb0 == f2%orb0)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%modes_ri == f2%modes_ri)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%modes_6d == f2%modes_6d)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%ptc_normal_form == f2%ptc_normal_form)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%bmad_normal_form == f2%bmad_normal_form)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%high_E_orb) .eqv. allocated(f2%high_E_orb))
if (.not. is_eq) return
if (allocated(f1%high_E_orb)) is_eq = all(shape(f1%high_E_orb) == shape(f2%high_E_orb))
if (.not. is_eq) return
if (allocated(f1%high_E_orb)) is_eq = all(f1%high_E_orb == f2%high_E_orb)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%low_E_orb) .eqv. allocated(f2%low_E_orb))
if (.not. is_eq) return
if (allocated(f1%low_E_orb)) is_eq = all(shape(f1%low_E_orb) == shape(f2%low_E_orb))
if (.not. is_eq) return
if (allocated(f1%low_E_orb)) is_eq = all(f1%low_E_orb == f2%low_E_orb)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%cache_x_min == f2%cache_x_min)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%cache_x_max == f2%cache_x_max)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%comb_ds_save == f2%comb_ds_save)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%track_state == f2%track_state)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%cache_n_pts == f2%cache_n_pts)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_rad_int_cache == f2%ix_rad_int_cache)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%has_open_match_element .eqv. f2%has_open_match_element)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%plot_cache_valid .eqv. f2%plot_cache_valid)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%spin_map_valid .eqv. f2%spin_map_valid)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%twiss_valid .eqv. f2%twiss_valid)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%mode_flip_here .eqv. f2%mode_flip_here)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%chrom_calc_ok .eqv. f2%chrom_calc_ok)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%rad_int_calc_ok .eqv. f2%rad_int_calc_ok)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%emit_6d_calc_ok .eqv. f2%emit_6d_calc_ok)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%sigma_track_ok .eqv. f2%sigma_track_ok)

end function eq_tao_lattice_branch


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_model_element (f1, f2) result (is_eq)

use tao_struct, only: tao_model_element_struct
implicit none

type(tao_model_element_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%beam == f2%beam)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%save_beam_internally .eqv. f2%save_beam_internally)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%save_beam_to_file .eqv. f2%save_beam_to_file)

end function eq_tao_model_element


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_beam_branch (f1, f2) result (is_eq)

use tao_struct, only: tao_beam_branch_struct
implicit none

type(tao_beam_branch_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%beam_at_start == f2%beam_at_start)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%beam_init == f2%beam_init)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%beam_init_used == f2%beam_init_used)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%init_starting_distribution .eqv. f2%init_starting_distribution)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%track_start == f2%track_start)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%track_end == f2%track_end)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_branch == f2%ix_branch)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_track_start == f2%ix_track_start)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_track_end == f2%ix_track_end)

end function eq_tao_beam_branch


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_d1_data (f1, f2) result (is_eq)

use tao_struct, only: tao_d1_data_struct
implicit none

type(tao_d1_data_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%name == f2%name)
!! f_side.equality_test[0D_PTR_type]
is_eq = is_eq .and. (associated(f1%d2) .eqv. associated(f2%d2))
if (.not. is_eq) return
if (associated(f1%d2)) is_eq = (f1%d2 == f2%d2)
!! f_side.equality_test[1D_PTR_type]
is_eq = is_eq .and. (associated(f1%d) .eqv. associated(f2%d))
if (.not. is_eq) return
if (associated(f1%d)) is_eq = all(shape(f1%d) == shape(f2%d))
if (.not. is_eq) return
if (associated(f1%d)) is_eq = all(f1%d == f2%d)

end function eq_tao_d1_data


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_lattice (f1, f2) result (is_eq)

use tao_struct, only: tao_lattice_struct
implicit none

type(tao_lattice_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%name == f2%name)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%lat == f2%lat)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%high_E_lat == f2%high_E_lat)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%low_E_lat == f2%low_E_lat)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%rad_int_by_ele_ri == f2%rad_int_by_ele_ri)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%rad_int_by_ele_6d == f2%rad_int_by_ele_6d)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%tao_branch) .eqv. allocated(f2%tao_branch))
if (.not. is_eq) return
if (allocated(f1%tao_branch)) is_eq = all(shape(f1%tao_branch) == shape(f2%tao_branch))
if (.not. is_eq) return
if (allocated(f1%tao_branch)) is_eq = all(f1%tao_branch == f2%tao_branch)

end function eq_tao_lattice


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_beam_uni (f1, f2) result (is_eq)

use tao_struct, only: tao_beam_uni_struct
implicit none

type(tao_beam_uni_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%saved_at == f2%saved_at)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%dump_file == f2%dump_file)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%dump_at == f2%dump_at)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%track_beam_in_universe .eqv. f2%track_beam_in_universe)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%always_reinit .eqv. f2%always_reinit)

end function eq_tao_beam_uni


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_dynamic_aperture (f1, f2) result (is_eq)

use tao_struct, only: tao_dynamic_aperture_struct
implicit none

type(tao_dynamic_aperture_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%param == f2%param)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%scan) .eqv. allocated(f2%scan))
if (.not. is_eq) return
if (allocated(f1%scan)) is_eq = all(shape(f1%scan) == shape(f2%scan))
if (.not. is_eq) return
if (allocated(f1%scan)) is_eq = all(f1%scan == f2%scan)
!! f_side.equality_test[1D_ALLOC_real]
is_eq = is_eq .and. (allocated(f1%pz) .eqv. allocated(f2%pz))
if (.not. is_eq) return
if (allocated(f1%pz)) is_eq = all(shape(f1%pz) == shape(f2%pz))
if (.not. is_eq) return
if (allocated(f1%pz)) is_eq = all(f1%pz == f2%pz)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%ellipse_scale == f2%ellipse_scale)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%a_emit == f2%a_emit)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%b_emit == f2%b_emit)

end function eq_tao_dynamic_aperture


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_model_branch (f1, f2) result (is_eq)

use tao_struct, only: tao_model_branch_struct
implicit none

type(tao_model_branch_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%ele) .eqv. allocated(f2%ele))
if (.not. is_eq) return
if (allocated(f1%ele)) is_eq = all(shape(f1%ele) == shape(f2%ele))
if (.not. is_eq) return
if (allocated(f1%ele)) is_eq = all(f1%ele == f2%ele)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%beam == f2%beam)

end function eq_tao_model_branch


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_d2_data (f1, f2) result (is_eq)

use tao_struct, only: tao_d2_data_struct
implicit none

type(tao_d2_data_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%name == f2%name)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%data_file_name == f2%data_file_name)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%ref_file_name == f2%ref_file_name)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%data_date == f2%data_date)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%ref_date == f2%ref_date)
!! f_side.equality_test[1D_NOT_character]
is_eq = is_eq .and. all(f1%descrip == f2%descrip)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%d1) .eqv. allocated(f2%d1))
if (.not. is_eq) return
if (allocated(f1%d1)) is_eq = all(shape(f1%d1) == shape(f2%d1))
if (.not. is_eq) return
if (allocated(f1%d1)) is_eq = all(f1%d1 == f2%d1)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_universe == f2%ix_universe)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_d2_data == f2%ix_d2_data)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ref == f2%ix_ref)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%data_read_in .eqv. f2%data_read_in)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%ref_read_in .eqv. f2%ref_read_in)

end function eq_tao_d2_data


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_spin_map (f1, f2) result (is_eq)

use tao_struct, only: tao_spin_map_struct
implicit none

type(tao_spin_map_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%valid .eqv. f2%valid)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%map1 == f2%map1)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%axis_input == f2%axis_input)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%axis0 == f2%axis0)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%axis1 == f2%axis1)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ele == f2%ix_ele)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ref == f2%ix_ref)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_uni == f2%ix_uni)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_branch == f2%ix_branch)
!! f_side.equality_test[2D_NOT_real]
is_eq = is_eq .and. all(f1%mat8 == f2%mat8)

end function eq_tao_spin_map


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_data (f1, f2) result (is_eq)

use tao_struct, only: tao_data_struct
implicit none

type(tao_data_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%ele_name == f2%ele_name)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%ele_start_name == f2%ele_start_name)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%ele_ref_name == f2%ele_ref_name)
!! f_side.equality_test[0D_ALLOC_character]
is_eq = is_eq .and. (allocated(f1%data_type) .eqv. allocated(f2%data_type))
if (.not. is_eq) return
if (allocated(f1%data_type)) is_eq = (f1%data_type == f2%data_type)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%merit_type == f2%merit_type)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%id == f2%id)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%data_source == f2%data_source)
!! f_side.equality_test[0D_NOT_character]
is_eq = is_eq .and. (f1%why_invalid == f2%why_invalid)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_uni == f2%ix_uni)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_bunch == f2%ix_bunch)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_branch == f2%ix_branch)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ele == f2%ix_ele)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ele_start == f2%ix_ele_start)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ele_ref == f2%ix_ele_ref)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_ele_merit == f2%ix_ele_merit)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_d1 == f2%ix_d1)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_data == f2%ix_data)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_dModel == f2%ix_dModel)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%eval_point == f2%eval_point)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%meas_value == f2%meas_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%ref_value == f2%ref_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%model_value == f2%model_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%design_value == f2%design_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%old_value == f2%old_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%base_value == f2%base_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%error_rms == f2%error_rms)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%delta_merit == f2%delta_merit)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%weight == f2%weight)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%invalid_value == f2%invalid_value)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%merit == f2%merit)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%s == f2%s)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%s_offset == f2%s_offset)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%err_message_printed .eqv. f2%err_message_printed)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%exists .eqv. f2%exists)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_model .eqv. f2%good_model)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_base .eqv. f2%good_base)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_design .eqv. f2%good_design)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_meas .eqv. f2%good_meas)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_ref .eqv. f2%good_ref)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_user .eqv. f2%good_user)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_opt .eqv. f2%good_opt)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%good_plot .eqv. f2%good_plot)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%useit_plot .eqv. f2%useit_plot)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%useit_opt .eqv. f2%useit_opt)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%spin_map == f2%spin_map)
!! f_side.equality_test[0D_PTR_type]
is_eq = is_eq .and. (associated(f1%d1) .eqv. associated(f2%d1))
if (.not. is_eq) return
if (associated(f1%d1)) is_eq = (f1%d1 == f2%d1)

end function eq_tao_data


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_ping_scale (f1, f2) result (is_eq)

use tao_struct, only: tao_ping_scale_struct
implicit none

type(tao_ping_scale_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%a_mode_meas == f2%a_mode_meas)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%a_mode_ref == f2%a_mode_ref)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%b_mode_meas == f2%b_mode_meas)
!! f_side.equality_test[0D_NOT_real]
is_eq = is_eq .and. (f1%b_mode_ref == f2%b_mode_ref)

end function eq_tao_ping_scale


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_universe_calc (f1, f2) result (is_eq)

use tao_struct, only: tao_universe_calc_struct
implicit none

type(tao_universe_calc_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%srdt_for_data == f2%srdt_for_data)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%rad_int_for_data .eqv. f2%rad_int_for_data)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%rad_int_for_plotting .eqv. f2%rad_int_for_plotting)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%chrom_for_data .eqv. f2%chrom_for_data)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%chrom_for_plotting .eqv. f2%chrom_for_plotting)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%lat_sigma_for_data .eqv. f2%lat_sigma_for_data)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%lat_sigma_for_plotting .eqv. f2%lat_sigma_for_plotting)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%dynamic_aperture .eqv. f2%dynamic_aperture)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%one_turn_map .eqv. f2%one_turn_map)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%lattice .eqv. f2%lattice)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%twiss .eqv. f2%twiss)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%track .eqv. f2%track)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%spin_matrices .eqv. f2%spin_matrices)

end function eq_tao_universe_calc


!--------------------------------------------------------------------------------
!--------------------------------------------------------------------------------

elemental function eq_tao_universe (f1, f2) result (is_eq)

use tao_struct, only: tao_universe_struct
implicit none

type(tao_universe_struct), intent(in) :: f1, f2
logical is_eq

!

is_eq = .true.
!! f_side.equality_test[0D_PTR_type]
is_eq = is_eq .and. (associated(f1%model) .eqv. associated(f2%model))
if (.not. is_eq) return
if (associated(f1%model)) is_eq = (f1%model == f2%model)
!! f_side.equality_test[0D_PTR_type]
is_eq = is_eq .and. (associated(f1%design) .eqv. associated(f2%design))
if (.not. is_eq) return
if (associated(f1%design)) is_eq = (f1%design == f2%design)
!! f_side.equality_test[0D_PTR_type]
is_eq = is_eq .and. (associated(f1%base) .eqv. associated(f2%base))
if (.not. is_eq) return
if (associated(f1%base)) is_eq = (f1%base == f2%base)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%beam == f2%beam)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%dynamic_aperture == f2%dynamic_aperture)
!! f_side.equality_test[1D_PTR_type]
is_eq = is_eq .and. (associated(f1%model_branch) .eqv. associated(f2%model_branch))
if (.not. is_eq) return
if (associated(f1%model_branch)) is_eq = all(shape(f1%model_branch) == shape(f2%model_branch))
if (.not. is_eq) return
if (associated(f1%model_branch)) is_eq = all(f1%model_branch == f2%model_branch)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%d2_data) .eqv. allocated(f2%d2_data))
if (.not. is_eq) return
if (allocated(f1%d2_data)) is_eq = all(shape(f1%d2_data) == shape(f2%d2_data))
if (.not. is_eq) return
if (allocated(f1%d2_data)) is_eq = all(f1%d2_data == f2%d2_data)
!! f_side.equality_test[1D_ALLOC_type]
is_eq = is_eq .and. (allocated(f1%data) .eqv. allocated(f2%data))
if (.not. is_eq) return
if (allocated(f1%data)) is_eq = all(shape(f1%data) == shape(f2%data))
if (.not. is_eq) return
if (allocated(f1%data)) is_eq = all(f1%data == f2%data)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%ping_scale == f2%ping_scale)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%scratch_lat == f2%scratch_lat)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%calc == f2%calc)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%ele_order == f2%ele_order)
!! f_side.equality_test[0D_NOT_type]
is_eq = is_eq .and. (f1%spin_map == f2%spin_map)
!! f_side.equality_test[2D_ALLOC_real]
is_eq = is_eq .and. (allocated(f1%dModel_dVar) .eqv. allocated(f2%dModel_dVar))
if (.not. is_eq) return
if (allocated(f1%dModel_dVar)) is_eq = all(shape(f1%dModel_dVar) == shape(f2%dModel_dVar))
if (.not. is_eq) return
if (allocated(f1%dModel_dVar)) is_eq = all(f1%dModel_dVar == f2%dModel_dVar)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%ix_uni == f2%ix_uni)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%n_d2_data_used == f2%n_d2_data_used)
!! f_side.equality_test[0D_NOT_integer]
is_eq = is_eq .and. (f1%n_data_used == f2%n_data_used)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%is_on .eqv. f2%is_on)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%design_same_as_previous .eqv. f2%design_same_as_previous)
!! f_side.equality_test[0D_NOT_logical]
is_eq = is_eq .and. (f1%picked_uni .eqv. f2%picked_uni)

end function eq_tao_universe
end module
