name: fpm Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            fpm_target: conda-macos

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/conda-setup
        with:
          python-version: 3.12
          environment-file: .github/fpm-env.yaml

      - name: Set environment variables
        env:
          FPM_TARGET: ${{ matrix.fpm_target }}
        shell: bash -l {0}
        run: |
          echo "FPM_TARGET=${FPM_TARGET}" >> $GITHUB_ENV

      - name: Build Tao (noplot)
        shell: bash -l {0}
        working-directory: ./tao/fpm-noplot
        run: "fpm @${FPM_TARGET}"

      - name: Build Tao (pgplot)
        shell: bash -l {0}
        working-directory: ./tao/fpm-pgplot
        run: "fpm @${FPM_TARGET}"

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.fpm_target }}-noplot"
          path: ./tao/fpm-noplot/${{ matrix.fpm_target }}

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.fpm_target }}-pgplot"
          path: ./tao/fpm-pgplot/${{ matrix.fpm_target }}
