name: fpm Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            plot_variant: noplot
            fpm_target: conda-macos
            extra_packages:
          - os: macos-latest
            plot_variant: pgplot
            fpm_target: conda-macos
            extra_packages:
          # - os: macos-latest
          #   plot_variant: plplot
          #   fpm_target: conda-macos
          - os: ubuntu-latest
            plot_variant: noplot
            fpm_target: conda-linux
            extra_packages:
          - os: ubuntu-latest
            plot_variant: plplot
            fpm_target: conda-linux
            extra_packages: plplot
          - os: ubuntu-latest
            plot_variant: pgplot
            fpm_target: conda-linux
            extra_packages:
          # - os: windows-latest
          #   plot_variant: noplot
          #   fpm_target: conda-windows

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/conda-setup
        with:
          python-version: 3.12
          environment-file: .github/fpm-env.yaml

      - name: Set environment variables
        env:
          FPM_TARGET: ${{ matrix.fpm_target }}
          PLOT_VARIANT: ${{ matrix.plot_variant }}
        shell: bash -l {0}
        run: |
          echo "FPM_TARGET=${FPM_TARGET}" >> $GITHUB_ENV
          echo "PLOT_VARIANT=${PLOT_VARIANT}" >> $GITHUB_ENV

      - name: Install extra packages
        shell: bash -l {0}
        if: ${{ matrix.extra_packages != '' }}
        run: |
          conda install -y ${{ matrix.extra_packages }}

      - name: Build Tao (${{ matrix.plot_variant }})
        shell: bash -l {0}
        working-directory: ./tao/fpm-${{ matrix.plot_variant }}
        run: "fpm @${FPM_TARGET}"

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.fpm_target }}-${{ matrix.plot_variant }}"
          path: ./tao/fpm-${{ matrix.plot_variant }}/${{ matrix.fpm_target }}
