name: PyTao tests

on:
  workflow_run:
    workflows: [Bmad Ecosystem - Build & Test]
    types:
      - completed

jobs:
  build:
    name: PyTao tests (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        shared: ["Y"]
        openmp_mpi: ["N"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bmad-built-${{ matrix.os }}-${{ matrix.shared }}-${{ matrix.openmp_mpi }}-${{ github.sha }}
          path: bmad_dist.tar.gz
          run-id: ${{ github.event.workflow_run.id }}

      - name: Extract the artifact
        shell: bash -l {0}
        working-directory: ./pytao
        run: |
          tar xf bmad_dist.tar.gz

      - uses: ./.github/actions/setup-dependencies
        with:
          external-packages-version: ${{ env.EXTERNAL_PACKAGES_VERSION }}

      - uses: actions/checkout@v4
        with:
          repository: "bmad-sim/pytao"
          ref: "master"
          path: "pytao"

      - uses: ./.github/actions/conda-setup
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: pytao/dev-environment.yml

      - name: Run Tests
        shell: bash -l {0}
        working-directory: ./pytao
        run: |
          export ACC_ROOT_DIR=$GITHUB_WORKSPACE

          echo -e '## Test results\n\n```' >> "$GITHUB_STEP_SUMMARY"
          pytest -v --cov=pytao/ pytao/tests 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
